BEGIN;
-- OWNER RULING 2026-09-03: build the planned tools (bugs_open/450 instance work). Fired by portfolio_positioning AFTER the chassis roll.
-- Shape mirrors the tool-suggester's completed add_tool rows on seotools (2026-09-02 22:31Z); adopt_existing_page=true on tool-generator's save_tool step (bugs_closed/286, TL-044) attaches to the existing planned page row.
CREATE TEMP TABLE fire(site_id uuid, domain text, name text, fn text, prio int, cx text, descr text, related jsonb, tp text);
INSERT INTO fire VALUES ((SELECT id FROM sites WHERE domain='seotools.co.uk'),'seotools.co.uk','Robots.txt Tester','tool-robots-txt-tester',1,'simple','Textarea for the contents of a robots.txt file, a URL path field, and a user-agent selector (Googlebot, Googlebot-Image, Bingbot, generic *). Parse the rules per the robots exclusion protocol (user-agent groups, Allow/Disallow, longest-match wins, wildcards * and $, Sitemap lines) and report whether the path is ALLOWED or DISALLOWED for that agent, quoting the exact line that decided it. Flag syntax slips (unknown directives, missing user-agent group, conflicting Allow/Disallow of equal length) and list the Sitemap URLs found. Offer an optional ''fetch from domain'' button that tries to load https://<domain>/robots.txt and explains that most sites block cross-origin reads, so pasting is the reliable route. Runs entirely in the browser: no server, no API key, no third-party proxy. State plainly in the UI what the tool cannot see.','["tools", "technical-seo-crawlers-compared", "glossary"]'::jsonb,'tools');
INSERT INTO fire VALUES ((SELECT id FROM sites WHERE domain='seotools.co.uk'),'seotools.co.uk','Core Web Vitals Checker','tool-core-web-vitals-checker',2,'moderate','URL field plus a mobile/desktop toggle. Call the public PageSpeed Insights v5 endpoint (https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=...&strategy=...), which allows keyless browser calls at low volume, and read the loadingExperience field data: LCP, INP and CLS at the 75th percentile with their category. Show each metric as a card with the value, Google''s thresholds (LCP 2.5 s / 4 s, INP 200 ms / 500 ms, CLS 0.1 / 0.25), a pass / needs-improvement / fail verdict and the distribution bar. If no field data exists for the URL say so and offer the origin-level result instead. Handle rate limiting and errors with a readable message. Runs entirely in the browser: no server, no API key, no third-party proxy. State plainly in the UI what the tool cannot see.','["tools", "technical-seo-crawlers-compared", "blog-index"]'::jsonb,'tools');
INSERT INTO fire VALUES ((SELECT id FROM sites WHERE domain='seotools.co.uk'),'seotools.co.uk','Title Tag Scorer','tool-title-tag-scorer',3,'simple','Title tag field and an optional target-keyword field. Score the title out of 100 on: character length (ideal 50-60), pixel width measured with a canvas at 20px Arial against Google''s ~600px desktop limit, keyword present and how early it appears, duplicate words, keyword stuffing, all-caps, trailing brand separators, and generic openers. Show the score, a breakdown with one sentence per signal, and a desktop SERP-style preview that visibly truncates where Google would. Update live as the user types. Runs entirely in the browser: no server, no API key, no third-party proxy. State plainly in the UI what the tool cannot see.','["tools", "keyword-research-tools-compared", "glossary"]'::jsonb,'tools');
INSERT INTO fire VALUES ((SELECT id FROM sites WHERE domain='seotools.co.uk'),'seotools.co.uk','SERP Snippet Previewer','tool-serp-snippet-previewer',4,'simple','Fields for title, meta description and URL. Render a realistic Google result preview for desktop and mobile side by side, measuring pixel widths with a canvas (title ~600px desktop / ~920px two-line mobile; description ~920px desktop, two lines) and truncating with an ellipsis exactly where the limit falls. Show live character and pixel counts with green/amber/red bands, and a one-line tip when the title or description will be cut. Format the URL as a breadcrumb the way Google does. Runs entirely in the browser: no server, no API key, no third-party proxy. State plainly in the UI what the tool cannot see.','["tools", "keyword-research-tools-compared", "glossary"]'::jsonb,'tools');
INSERT INTO fire VALUES ((SELECT id FROM sites WHERE domain='seotools.co.uk'),'seotools.co.uk','Keyword Difficulty Estimator','tool-keyword-difficulty-estimator',5,'simple','Keyword phrase field and a market selector (UK, US, generic). Estimate a difficulty band (Easy / Medium / Hard / Very hard) from on-device heuristics with the reasoning shown: word count and specificity (long-tail vs head term), commercial modifiers (best, buy, price, near me, review), brand names, question forms, year or location qualifiers, and the likely SERP features those patterns attract. Classify search intent (informational, navigational, commercial, transactional) with one sentence of justification and suggest 5-8 related long-tail variants built from the phrase. Be explicit that this is a heuristic estimate, not live SERP data, and say what to check by hand. Runs entirely in the browser: no server, no API key, no third-party proxy. State plainly in the UI what the tool cannot see.','["tools", "keyword-research-tools-compared", "rank-trackers-compared"]'::jsonb,'tools');
INSERT INTO fire VALUES ((SELECT id FROM sites WHERE domain='seotools.co.uk'),'seotools.co.uk','Meta Tag Checker','tool-meta-tag-checker',6,'simple','Primary mode: a textarea where the user pastes a page''s HTML source (View Source). Parse and display the title tag, meta description, canonical URL, robots directives, viewport, Open Graph and Twitter card tags, hreflang links and the first H1, each with length and a pass/warn/fail check (missing, empty, too long, duplicate, noindex present, canonical pointing elsewhere). Show a Google-style snippet preview built from the title and description. Secondary mode: a URL field that attempts a browser fetch and falls back to a clear message that most sites block cross-origin reads, pointing the user to paste the source instead. Runs entirely in the browser: no server, no API key, no third-party proxy. State plainly in the UI what the tool cannot see.','["tools", "technical-seo-crawlers-compared", "glossary"]'::jsonb,'tools');
INSERT INTO fire VALUES ((SELECT id FROM sites WHERE domain='websitepromotion.co.uk'),'websitepromotion.co.uk','Promotion Channel Prioritiser','tool-channel-prioritiser',1,'simple','A short questionnaire (6-8 questions, one screen): site type (local business, online shop, SaaS, content site, personal or portfolio), audience (consumers or businesses), monthly budget band, hours per week available, current traffic band, whether the site already ranks for anything, and the main goal (sales, leads, readers, awareness). Score a fixed list of promotion channels against the answers with transparent rules - search (SEO), paid search, social organic, paid social, email, directories and listings, partnerships and PR, content and guest posting, community forums, local listings - and show a ranked shortlist of the top five with a one-sentence reason per channel, an effort/cost badge, and the channels deliberately ruled out with why. Include a ''change an answer'' path that re-ranks live. Runs entirely in the browser: no server, no API key, no third-party proxy. State plainly in the UI what the tool cannot see.','["new", "channels-index", "guides-index", "website-promotion-playbook"]'::jsonb,'new');
-- guards: sites unlocked+deployed; target planned page exists and carries NO tool-level component; no live item with this key
DO $$ DECLARE n int; BEGIN
  SELECT count(*) INTO n FROM fire f JOIN sites s ON s.id=f.site_id WHERE s.locked_at IS NULL AND s.status='deployed'; IF n<>7 THEN RAISE EXCEPTION 'site guard: % of 7', n; END IF;
  SELECT count(*) INTO n FROM fire f JOIN pages p ON p.site_id=f.site_id AND p.name=f.fn AND p.page_type='tool' AND p.status='active'
    WHERE NOT EXISTS (SELECT 1 FROM page_components pc JOIN content_components cc ON cc.id=pc.component_id WHERE pc.page_id=p.id AND pc.build_status<>'removed' AND cc.component_level='tool');
  IF n<>7 THEN RAISE EXCEPTION 'page guard: % of 7 planned tool pages exist without a tool component', n; END IF;
  SELECT count(*) INTO n FROM fire f JOIN site_work_items w ON w.site_id=f.site_id AND w.item_key='add_tool_novel_'||f.domain||'_'||f.fn AND w.status NOT IN ('complete','verified','rejected','wont_fix','failed','unresolved','cancelled');
  IF n<>0 THEN RAISE EXCEPTION 'dedup guard: % live items already carry a key', n; END IF;
  SELECT count(*) INTO n FROM content_components WHERE component_level='tool' AND is_active AND function IN (SELECT fn FROM fire); IF n<>0 THEN RAISE EXCEPTION 'library guard: % tool components already claim a function', n; END IF;
END $$;
INSERT INTO site_work_items (site_id, source, item_type, severity, summary, spec, priority, handler_agent, status, created_by, item_key, pipeline, triaged_at, approval_mode)
SELECT f.site_id, 'portfolio_positioning', 'add_tool', 'low', f.name,
  jsonb_build_object('name', f.name, 'function', f.fn, 'priority', f.prio, 'complexity', f.cx, 'description', f.descr,
                     'target_page', f.tp, 'related_pages', f.related, 'library_source', NULL, 'experience_plan', NULL, 'tool_component_id', NULL,
                     'owner_ruling', '2026-09-03 build the planned tools (bugs_open/450 instance; the plan named this page before any tool existed)'),
  120, 'tool-generator', 'triaged', 'portfolio_positioning', 'add_tool_novel_'||f.domain||'_'||f.fn, 'build', now(), 'auto'
FROM fire f;
DO $$ DECLARE n int; BEGIN SELECT count(*) INTO n FROM site_work_items WHERE created_by='portfolio_positioning' AND item_type='add_tool' AND status='triaged' AND created_at > now()-interval '1 minute'; IF n<>7 THEN RAISE EXCEPTION 'insert guard: % of 7', n; END IF; END $$;
COMMIT;
SELECT left(id::text,8) AS id, (SELECT domain FROM sites WHERE id=site_id) AS domain, summary, item_key, status FROM site_work_items WHERE created_by='portfolio_positioning' AND item_type='add_tool' ORDER BY created_at DESC LIMIT 7;
