apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ai-persona-system
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    # Alertmanager configuration
    alerting:
      alertmanagers:
        - static_configs:
            - targets: []

    # Load rules once and periodically evaluate them
    rule_files:
      - '/etc/prometheus/rules/*.yml'

    scrape_configs:
      # Scrape Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      # Kubernetes SD for pods
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - ai-persona-system
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name

  alerts.yml: |
    groups:
      - name: ai-persona-alerts
        interval: 30s
        rules:
          - alert: HighWorkflowFailureRate
            expr: rate(workflows_total{status="failed"}[5m]) > 0.1
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High workflow failure rate detected"
              description: "{{ $labels.instance }} has a workflow failure rate above 10% (current value: {{ $value }})"
          
          - alert: LowAgentAvailability
            expr: up{job="kubernetes-pods", app="agent-chassis"} < 3
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "Low agent chassis availability"
              description: "Less than 3 agent chassis pods are running"
          
          - alert: DatabaseDown
            expr: up{job="kubernetes-pods", app=~"postgres-.*|mysql-.*"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Database {{ $labels.app }} is down"
              description: "Database {{ $labels.app }} has been down for more than 1 minute"
          
          - alert: KafkaLag
            expr: kafka_consumer_lag > 1000
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High Kafka consumer lag"
              description: "Consumer group {{ $labels.group }} has lag > 1000 messages"