apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-persona-system
resources:
  - ../../../base

labels:
  - pairs:
      environment: production
      region: uk

images:
  - name: docker.io/aqls/web-search-adapter
    newTag: v1.0.1360

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: web-search-adapter
  - path: patch-env.yaml
    target:
      kind: Deployment
      name: web-search-adapter