-- playground_widget_add_tool_dispatch.sql — Phase P step 3, PATH (a) (owner, 2026-09-03 evening:
-- "a with b as fallback"): the playground chat widget GENERATED by tool-generator from a brief
-- that carries the live route's contract, landing on the EXISTING /playground.html.
--
-- Why not the library chat-input-box: single-turn {message} -> JSON, same-origin literal path,
-- no endpoint field (NOTES 2026-09-03 16:45Z). Why this lands on /playground.html and not
-- /tools/…: the live tool-generator's save_tool step has adopt_existing_page=true (measured
-- 2026-09-03 19:50Z) and resolveToolPageIdentity matches the page whose name equals the
-- function's legacy name, so function `tool-playground` -> page `playground`, attached as it
-- stands (Refresh:[]), the six sections kept, the tool component added.
--
-- The route contract below is copied from internal/tools-api/handlers/playground.go as
-- committed in 9b540c2e6 (the image serving it). If the route changes, this brief changes.
--
-- Rehearse with COMMIT -> ROLLBACK first. Verify at the served page: a real chat works end to
-- end (tokens appear as they stream; a wrong-origin call is impossible from the page; the
-- 400 messages show as the visitor-facing text; a `truncated` reply is marked). Rollback: set the
-- new page_components row is_active=false / retire the component, then a page_rerender.
\set ON_ERROR_STOP on
BEGIN;
DO $$
DECLARE
  v_site uuid := '1368e337-dd1d-4799-bbb3-8221a1b79bcc';
  v_page uuid := '4234fe60-4332-4f4a-b256-ba420716a884';   -- /playground.html
  n int;
BEGIN
  -- G1: the route answers from outside is checked by the operator (curl) — here: the page exists, deployed, name 'playground'
  SELECT count(*) INTO n FROM pages WHERE id=v_page AND site_id=v_site AND name='playground' AND status='active';
  IF n <> 1 THEN RAISE EXCEPTION 'G1: /playground.html is not an active page named playground (%)', n; END IF;
  -- G2: no tool-playground component or open add_tool on this site
  SELECT count(*) INTO n FROM content_components WHERE name LIKE 'tool-playground%' AND is_active;
  IF n <> 0 THEN RAISE EXCEPTION 'G2: a tool-playground component already exists (%)', n; END IF;
  SELECT count(*) INTO n FROM site_work_items WHERE site_id=v_site AND item_type='add_tool'
    AND status NOT IN ('complete','verified','rejected','wont_fix','failed','unresolved','cancelled','deferred');
  IF n <> 0 THEN RAISE EXCEPTION 'G2: % open add_tool item(s) on the site', n; END IF;
  -- G3: the generator's adopt flag is on (else this mints /tools/tool-playground.html)
  SELECT count(*) INTO n FROM agent_definitions d, jsonb_each(d.default_config->'workflow'->'steps') s
   WHERE d.type='tool-generator' AND d.is_active AND COALESCE(d.is_snapshot,false)=false AND d.deleted_at IS NULL
     AND s.value->>'action'='create_tool_component' AND (s.value->'config'->>'adopt_existing_page')='true';
  IF n <> 1 THEN RAISE EXCEPTION 'G3: tool-generator create step does not carry adopt_existing_page=true'; END IF;

  INSERT INTO site_work_items (site_id, page_id, source, pipeline, item_type, severity, summary, priority,
                               handler_agent, status, created_by, spec, item_key, batch_id)
  VALUES (v_site, v_page, 'owner-request', 'build', 'add_tool', 'high',
    'playground: the demo chat widget on /playground.html, generated against the live tools-api route (Phase P step 3, path a)',
    30, 'tool-generator', 'triaged', 'finetuning_uk_service_lane',
    jsonb_build_object(
      'name', 'Playground Chat',
      'function', 'tool-playground',
      'priority', 9,
      'complexity', 'medium',
      'target_page', '/playground.html',
      'related_pages', jsonb_build_array('/your-own-model.html', '/technical-details.html'),
      'library_source', NULL,
      'experience_plan', NULL,
      'tool_component_id', NULL,
      'reason', 'PLAN Phase P step 3; owner 2026-09-03: path (a). The library chat-input-box does not fit (single-turn, same-origin, JSON).',
      'description',
        'A chat box that lets a visitor talk to the free demo model: a small language model we fine-tuned, running on our own server. It is the centre of this page. ' ||
        'BEHAVIOUR. The visitor types a message and presses Send (or Enter). The box shows the visitor''s message as a bubble, then shows the model''s reply APPEARING WORD BY WORD as it streams in, then re-enables the input. The conversation continues: the box keeps the whole transcript in the page (in memory only; nothing is stored anywhere) and sends it back on every turn. A "Start again" button clears the transcript. ' ||
        'THE API, exactly. POST https://tools.apis.uk/api/v1/tools/playground/chat with header Content-Type: application/json and a JSON body {"messages":[{"role":"user","content":"..."},{"role":"assistant","content":"..."},...]}. Rules the server enforces and the box must respect before sending: at most 12 messages per request (send the LAST 12 of the transcript); each message at most 1000 characters (block longer input with a visible count); roles are only "user" and "assistant" (never "system"); the last message must be the user''s; no empty messages. Send with fetch() and mode "cors", NO credentials, no custom headers beyond Content-Type. ' ||
        'THE RESPONSE is a stream of server-sent events (Content-Type text/event-stream), read with fetch() and response.body.getReader(), decoding UTF-8 and splitting on blank lines; each event has a line "event: <name>" and a line "data: <json>". event token: data is a JSON string, one fragment of the reply; append it to the current assistant bubble immediately. event done: data is a JSON object {"eval_count":n,"eval_duration_ms":n,"load_duration_ms":n,"done_reason":"stop"|"length","truncated":true|false}; finish the bubble, and if truncated is true add a small note under it: "The demo stops replies at 150 words; ask it to continue." event error: data is {"message":"..."}; show the message in a muted bubble and re-enable the input. If the stream ends without a done event, treat it as the error "The demo model stopped before finishing". Before the first token the server may answer with a plain JSON error and an HTTP status: 400 {"error":"..."} means the box sent something invalid (show the error text); 403 means the page is not allowed to call the demo (show "The demo is not available from this page"); 429 means too many requests (show "The demo is busy; try again in a minute"); 503 means the model is offline (show "The demo model is not available right now"). One request in flight at a time; disable Send while waiting; a 90-second timeout on the client with the same "stopped before finishing" message. ' ||
        'COPY, static in the template and never generated: a heading "Try the demo model"; one line above the box: "A small model, fine-tuned by us, running on our own server. Ask it anything about how a business writes; replies are short on purpose."; a disclosure under the box: "This is an automated demo. Nothing you type is stored." Placeholder: "Ask the model something..." Button label "Send". All copy British English. ' ||
        'DESIGN. Use the site''s own colour and type variables; the transcript area scrolls, newest at the bottom; visitor bubbles right-aligned, model bubbles left-aligned; the streaming bubble shows a subtle typing indicator until the first token arrives; readable on the page''s background (check contrast). Works without any external library. Accessible: the transcript is aria-live="polite", the input has a label, Send is a real button. ' ||
        'ACCEPTANCE (what a checker can verify on the served page): the page contains exactly one form with a text input and a Send button; the script references https://tools.apis.uk/api/v1/tools/playground/chat and no other endpoint; the script reads response.body.getReader() (streaming) and handles event names token, done and error; the client caps messages at 12 and characters at 1000; no credentials are sent; the static copy above appears verbatim; no em dashes anywhere in the copy.'
    ),
    'add_tool:tool-playground:' || v_site::text, gen_random_uuid());

  SELECT count(*) INTO n FROM site_work_items WHERE site_id=v_site AND item_type='add_tool' AND status='triaged' AND spec->>'function'='tool-playground'
    AND spec->>'description' NOT LIKE '%—%' AND length(spec->>'description') > 2000;
  IF n <> 1 THEN RAISE EXCEPTION 'post: expected 1 triaged add_tool for tool-playground, found %', n; END IF;
  RAISE NOTICE 'add_tool item for tool-playground inserted (triaged) on /playground.html';
END $$;
COMMIT;
