apiVersion: v1
kind: ConfigMap
metadata:
  name: personae-dev-config
data:
  # Development Endpoints (for in-cluster services)
  kafka_brokers: "personae-kafka-cluster-kafka-bootstrap.kafka.svc:9092"
  clients_db_host: "postgres-clients.personae-dev-db.svc.cluster.local"
  templates_db_host: "postgres-templates.personae-dev-db.svc.cluster.local"
  auth_db_host: "mysql-auth.personae-dev-db.svc.cluster.local"
  minio_endpoint: "http://minio.personae-dev-db.svc.cluster.local:9000"
  core_manager_url: "http://core-manager.personae-dev-db.svc.cluster.local:8088"
  auth_service_url: "http://auth-service.personae-dev-db.svc.cluster.local:8081"

  # Development Settings
  tracing_enabled: "false"
  log_level: "debug"
  go_env: "development"