apiVersion: v1
kind: Secret
metadata:
  name: personae-dev-secrets
type: Opaque
data:
  # Base64 encoded development passwords. E.g., echo -n 'dev-password' | base64
  clients-db-password: "ZGV2LWNsaWVudHMtcGFzc3dvcmQ="
  templates-db-password: "ZGV2LXRlbXBsYXRlcy1wYXNzd29yZA=="
  auth-db-password: "YWdlbnQtY2hhc3NpczEyMyE="
  minio-access-key: "bWluaW8="      # "minio"
  secret-key: "bWluaW9hZG1pbg==" # "minioadmin"
  JWT_SECRET_KEY: "ZGV2LXNlY3JldA=="    # "dev-secret"
  # API keys can be dummy values for dev if not used
  stability-api-key: "bm90LWEtcmVhbC1rZXk="
  serp-api-key: "bm90LWEtcmVhbC1rZXk="
  # ai-persona-system-reasoning-key
  anthropic-api-key: "c2stYW50LWFwaTAzLS1NX2kwNGFFNzJBd1Vzb0gxMU93S1k3VnU5Z2JSMVRENVNvT241dU5kQUlEVWdnc3U2QTV3Q3dkSlFOdnhqbThMNHV3alAyaEtDSUpmY1hnUnViaUNBLVdvSGpSd0FB"
---
# This new secret is specifically for pulling images
apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-creds
  namespace: ai-persona-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJhcWxzIiwicGFzc3dvcmQiOiJBYUQwMjQzMjEyMyEiLCJlbWFpbCI6ImFhYUBkZXNpZ25jb25zdWx0YW5jeS5jby51ayIsImF1dGgiOiJZWEZzY3pwQllVUXdNalF6TWpFeU15RT0ifX19Cg==