-- WRITE the acceptance-criteria fence into tool-review-council-simulator's PLAN.
-- Mirrors write_doc_plan_action.go:94-110 EXACTLY: one transaction, supersede the
-- current row then insert, because idx_doc_plans_current is a partial unique index
-- on (subject_type, subject_key) WHERE is_current and would reject two current rows.
-- Generated by plan_append_acceptance_criteria.md + the original body; do not hand-edit.

UPDATE doc_plans
   SET is_current = false, superseded_at = now(), updated_at = now()
 WHERE subject_type = 'tool' AND subject_key = 'tool-review-council-simulator' AND is_current;

INSERT INTO doc_plans (subject_type, subject_key, body, source, created_by)
VALUES ('tool', 'tool-review-council-simulator', $planbody$# PLAN -- tool-review-council-simulator

## Aim

Let a visitor answer a question our own team had to answer with money: if you put a
panel of AI reviewers in front of every change, what proportion of sound work comes
back, and what does tightening or loosening the panel actually do to that number?

It exists to make one of this company's two flagship capabilities (the multi-agent
review council) legible by letting someone operate it, rather than read a page about
it. It is the third tool on fundamentallyai.com, after the LLM cost calculator and
the model-approach selector.

## Source spec

Owner instruction, 2026-07-30, verbatim in the lane handoff: "An interactive tools
page, with sliders/inputs, built on real live platform numbers (pages/sites hosted;
council decisions by verdict and by reviewer seat)", with the requirement that the
numbers be real and that the style match the two existing tool pages.

The "pages/sites hosted" half was measured and deliberately NOT used as the tool's
engine (see Deliberate decisions). The council half is the engine.

## Behaviour contract

Inputs, all live-updating on the `input` event (no calculate button; a slider that
needs a button to take effect is a broken slider):

- `blocking threshold` (range 0-2): any objection / medium and up / high only.
- `reviewer relevance` (range 10-100, step 5): the share of seats that have an
  opinion on a given change. Default 70, which is what our own runs show.
- `revision rounds` (range 1-6): how many attempts before giving up.
- a 26-row seat roster of checkboxes, each showing that seat's measured objection
  rate at the current threshold; four presets (typical 8 / minimal pair / all 26 /
  clear).

Outputs: first-round pass probability; pass-within-N-rounds; mean rounds to pass;
reviews spent; expected seats firing; a ranked blocker bar chart (top 8); and a
"reality band" placing the user's configuration against three measured figures.

Model: for each enabled seat, P(blocks) = relevance x that seat's measured rate at
the chosen threshold. P(pass) = product of (1 - P(blocks)). P(within N) =
1 - (1 - P(pass))^N.

Empty roster renders "n/a" and an explanation, never a misleading 100%.

## Data provenance

Every rate is measured, none invented. Source: `diagnosis_artifacts` where
`kind='council_report'`, 362 rows spanning 2026-07-10 to 2026-07-30, aggregated by
`body::jsonb -> 'reviews'` (each element carries `reviewer`, `verdict`,
`objections[].severity`). Queries are in the lane RUNBOOK.

The three comparison figures:
- 2.6% (4 of 154) first-round approval before 2026-07-22
- 51.0% (106 of 208) after 2026-07-22
- 30.4% (110 of 362) across all runs

The 07-22 step is the decision-rule fix in bugs_closed/057, and the data shows it
plainly, which is why the tool leads on that lever.

## Delivery mechanism

Path 1 equivalent, self-contained: the component's `html_template` holds its own
`<style>`, its markup, and its `<script>` as an IIFE **after** the markup. It uses
NO `js_snippets` entry and NO `/assets/js/snippets.js`. This matches the sibling
tool (`tool-llm-cost-calculator`, `input_schema` NULL, `template_variable_count` 0)
and it is the reason this component cannot suffer the head-loaded init failure that
cost the teaser-reveal-panel five rounds: a script placed after its own markup
cannot run before that markup exists.

A `document.readyState` guard is present anyway, so the component still works if
the template is ever bundled into a head-loaded file.

## Dependencies

- `content_components` row `tool-review-council-simulator-fundamentallyai-com`
  (`function=tool-review-council-simulator`, render_mode=template,
  category=interactive, component_level=tool).
- Page `/tools/review-council-simulator.html`, page_type=tool, three sections:
  `hero-tool`, this widget, `tool-cta`. hero-tool and tool-cta reuse the exact
  component rows the llm-cost-calculator page uses.
- The site palette CSS variables (`--color-primary`, `--color-surface`,
  `--color-border`, `--color-text`, `--color-text-muted`, `--color-accent`).
- NOT in `site_plan_sections`. Deliberate: no tool page on this site is, and adding
  one invites the plan-driven rebuild to regenerate its copy with an LLM.

## Deliberate decisions -- do NOT "fix" these

1. **The numbers are a dated snapshot, and the page says so.** This is static HTML
   with no API to call at load. Baking the figures in at build time is the only
   honest option, so the tool states the measurement date and the run count in the
   body rather than implying a live feed. Re-measure before quoting them in a month.

2. **Site/page counts were measured and left out of the engine.** 442 pages, 419
   active, 383 deployed, 14 sites, 110 tool pages. They make a fine stat band but
   they are not a *tool*: nothing a visitor could slide would change them. Using
   them as decoration on an interactive page would have been the passive dashboard
   the owner explicitly did not ask for. They are recorded here so the next thread
   knows they were considered rather than missed.

3. **Seats with under 20 recorded runs are flagged "thin" in the UI.** Four seats
   sit at 100% objection over 4 to 21 runs. Presenting that as a rate would be the
   most misleading thing on the page, so the roster marks them and a note names
   which of the user's selected seats are thin.

4. **The model's two false assumptions are printed under the results, not hidden.**
   Seats are treated as independent (they are not; a badly shaped change draws
   objections from several at once) and each round as a fresh roll (real
   resubmissions answer the objection they were given, so this understates a real
   council). The page says to read the pass rates as a floor.

5. **No `tool-guide-intro` section.** That component is render_mode=agent and would
   need an LLM pass to fill. The page is deliberately self-contained; adding the
   intro later is a content task, not a fix.

6. **No `/tools.html` link anywhere.** That index page does not exist on this site.
   The sibling page's "Explore All Tools" label has no valid target; it was not
   copied. Every URL in this page's content_data was checked against `pages` first.

## Verification contract

`scripts/probe_council_simulator.py` is the gate, and it is mutation-proven: it
fails on a no-init mutant, on a script-before-markup mutant (the exact
teaser-reveal-panel bug class), and on a dead-slider mutant. Exit 0 clean, 1 on any
failure. Run it with `--url` after any re-render. A check that has never been shown
to fail is not evidence.

## Acceptance criteria

Authored 2026-07-31 by lane `staged_component_build`. Until now this PLAN had a
Verification contract naming a local Python probe, and **no criteria fence at all** —
so a fired acceptance run resolved the page, found nothing to assert, and skipped
with `needs_criteria`. A skip is honest but it is not a failure, so the run read as
clean. That is the silent class `CHECK_naming_contract.sh` exists to find, and this
tool was its one BROKEN-B instance fleet-wide.

Every check below was watched to pass against the live URL on both profiles, and
watched to FAIL under a mutant that breaks the behaviour it names. Neither claim is
an assertion about this document: both are re-runnable, and the commands are in the
lane RUNBOOK.

```criteria
{
  "profiles": ["desktop", "mobile"],
  "container": ".tool-container[data-component=\"tool-review-council-simulator\"]",
  "checks": [
    { "id": "page-serves-200", "type": "page_status_ok" },

    { "id": "tool-container-renders", "type": "selector_exists",
      "selector": ".tool-container[data-component=\"tool-review-council-simulator\"]" },

    { "id": "roster-is-built-client-side", "type": "selector_exists",
      "selector": ".rcs-seat" },

    { "id": "default-preset-is-our-typical-eight", "type": "interaction",
      "expect": { "selector": "#rcs-seats-out", "text_matches": "^8 seats on the panel$" } },

    { "id": "threshold-starts-where-we-run-it", "type": "interaction",
      "expect": { "selector": "#rcs-threshold-out", "text_matches": "^Only high severity blocks$" } },

    { "id": "headline-is-computed-not-a-placeholder", "type": "interaction",
      "expect": { "selector": "#rcs-pass1", "text_matches": "^[0-9]+\\.[0-9]%$" } },

    { "id": "within-rounds-is-computed", "type": "interaction",
      "expect": { "selector": "#rcs-passn", "text_matches": "^[0-9]+\\.[0-9]%$" } },

    { "id": "mean-rounds-is-computed", "type": "interaction",
      "expect": { "selector": "#rcs-rounds-needed", "text_matches": "^[0-9]+\\.[0-9]$" } },

    { "id": "seats-firing-is-computed", "type": "interaction",
      "expect": { "selector": "#rcs-firing", "text_matches": "^[0-9]+\\.[0-9]$" } },

    { "id": "blocker-chart-is-ranked", "type": "interaction",
      "expect": { "selector": "#rcs-blockers-list .rcs-bar-row" } },

    { "id": "reality-band-is-drawn", "type": "interaction",
      "expect": { "selector": "#rcs-reality-legend .rcs-legend-pct" } },

    { "id": "denominator-states-what-it-counts", "type": "interaction",
      "expect": { "selector": "#rcs-denominator", "text_matches": "count ROUNDS" } },

    { "id": "threshold-lever-updates-the-readout", "type": "interaction",
      "steps": [ { "action": "fill", "selector": "#rcs-threshold", "value": "0" } ],
      "expect": { "selector": "#rcs-threshold-out", "text_matches": "^Any objection blocks$" } },

    { "id": "every-seat-preset-counts-twenty-six", "type": "interaction",
      "steps": [ { "action": "click", "selector": ".rcs-preset[data-preset=\"all\"]" } ],
      "expect": { "selector": "#rcs-seats-out", "text_matches": "^26 seats on the panel$" } },

    { "id": "no-horizontal-overflow", "type": "no_horizontal_overflow" },

    { "id": "minimal-preset-is-the-measured-pair", "type": "interaction",
      "steps": [ { "action": "click", "selector": ".rcs-preset[data-preset=\"minimal\"]" } ],
      "expect": { "selector": "#rcs-seats-out", "text_matches": "^2 seats on the panel$" } },

    { "id": "cleared-panel-refuses-to-invent-a-number", "type": "interaction",
      "steps": [ { "action": "click", "selector": ".rcs-preset[data-preset=\"none\"]" } ],
      "expect": { "selector": "#rcs-pass1", "text_matches": "^n/a$" } },

    { "id": "no-console-errors", "type": "no_console_errors" }
  ]
}
```

### What the fence asserts, and why these and not others

Each check asserts a claim this PLAN already makes, rather than a property of the
markup. The three that carry the most weight:

- **`cleared-panel-refuses-to-invent-a-number`** is the fence's best check. The
  Behaviour contract promises "empty roster renders n/a and an explanation, never a
  misleading 100%". Its mutant replaces that `n/a` with `100.0%` and the check goes
  red — so the tool's *honesty* is now a machine-checked property, not a line in a
  document.
- **`roster-is-built-client-side`** is the teaser-reveal-panel gate. `#rcs-seats` is
  served EMPTY (`<div class="rcs-seats" id="rcs-seats"></div>`) and all four result
  figures are served as `--`; every one of them is filled by the IIFE. So these
  checks pass only if the script genuinely ran in the visitor's browser, which is
  precisely what four rounds of static-markup verification failed to establish for
  `teaser-reveal-panel`.
- **`denominator-states-what-it-counts`** asserts the provenance text is actually
  rendered. The tool's numbers are a dated snapshot (Deliberate decision 1), and a
  snapshot whose denominator quietly stops being displayed is the failure that turns
  an honest figure into a misleading one.

### What it deliberately does NOT assert — all four are omissions, not oversights

1. **No `has_visible_area` check, even though the type is live in the running
   binary** (verified 2026-07-31 by long-marker grep of
   `/app/browser-runner-adapter`, build 08:53:36 UTC, with three positive
   controls). `bugs_open/157` is open and unfixed at HEAD
   (`run_checks_action.go:773-774`): the decode asserts `float64`, but
   playwright-go returns `int` for a whole number, so **any axis whose rendered
   size is an integer measures 0** and the check reports "too small to see or
   click". Adding it here would have bought a false FAIL on a correct tool. The
   bug belongs to the leopardess lane, which holds the reproducer. **Add these
   checks when 157 closes** — the 26-row roster's checkboxes are exactly the
   integer-sized controls the type exists to police.
2. **No count assertion via `selector_count`.** That type is behaviourally
   IDENTICAL to `selector_exists` — `run_checks_action.go:497` passes on `n > 0`
   and there is no expected-count field on the check. It reports the count in its
   detail line, which reads like an assertion and is not one. So every count in
   this fence (8, 26, 2 seats) is asserted through the tool's own readout text
   instead, which has the side benefit of asserting the tool can *say* what it did.
3. **`input`-versus-`change` wiring is not distinguishable by any fence.** The
   Behaviour contract says the inputs update on the `input` event. Playwright's
   `fill()` dispatches both events and the criteria vocabulary has no way to send
   one without the other, so a tool wired only to `change` would pass. This was
   found by mutation, not by reasoning: the first version of the mutant killed only
   the `input` listener and the check still passed. The check is therefore named
   `threshold-lever-updates-the-readout`, which is what it proves. The "no
   calculate button" half of the claim IS covered — no click is needed for the
   readout to change.
4. **No aesthetic check.** PLAN D2: every gate is validation, never judgement.

### Order is load-bearing

`evaluateOnPage` runs the whole fence against ONE page instance per profile, in
fence order, so interactions accumulate. The structural and default-state checks
therefore come first, then the threshold fill, then the presets in the order
all -> minimal -> none, because `none` wipes the results panel. `no_console_errors`
is forced last by the runner itself so it catches interaction-triggered errors.
**Reordering this fence changes what it tests.**

### How to re-verify (both halves — one is not evidence without the other)

```
go run docs/agent_docs/docs024_key_docs_latest/staged_component_build/scripts/try_fence.go \
  docs/agent_docs/docs024_key_docs_latest/staged_component_build/scripts/fence_tool_review_council_simulator.json \
  https://fundamentallyai.com/tools/review-council-simulator.html

go run docs/agent_docs/docs024_key_docs_latest/staged_component_build/scripts/prove_fence_can_fail.go \
  docs/agent_docs/docs024_key_docs_latest/staged_component_build/scripts/fence_tool_review_council_simulator.json \
  https://fundamentallyai.com/tools/review-council-simulator.html
```

Measured 2026-07-31: **36 of 36 check-evaluations passed** on the live URL across
desktop and mobile with zero skips and the arithmetic reconciled, and **17 of 17
mutants were caught, with all 18 checks watched red** against an all-green
baseline. Both harnesses call the platform's own `RunChecksAction`, not a
reimplementation of it.
$planbody$,
        'staged_component_build', 'operator:staged_component_build');
