# FILE: k8s/image-generator-adapter.yaml (Updated)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-generator-adapter
  namespace: ai-persona-system
  labels:
    app: image-generator-adapter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-generator-adapter
  template:
    metadata:
      labels:
        app: image-generator-adapter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      initContainers:
        # Wait for Kafka and topics
        - name: wait-for-kafka-topics
          image: confluentinc/cp-kafka:7.5.0
          command:
            - sh
            - -c
            - |
              echo "Waiting for Kafka and required topics..."
              until kafka-topics --bootstrap-server kafka-0.kafka-headless:9092 --list >/dev/null 2>&1; do
                echo "Kafka not ready, waiting..."
                sleep 5
              done
              
              required_topics="system.adapter.image.generate system.responses.image"
              for topic in $required_topics; do
                echo "Checking for topic: $topic"
                max_attempts=20
                attempt=1
                while [ $attempt -le $max_attempts ]; do
                  if kafka-topics --bootstrap-server kafka-0.kafka-headless:9092 --list | grep -q "^$topic$"; then
                    echo "Topic $topic exists!"
                    break
                  fi
                  if [ $attempt -eq $max_attempts ]; then
                    echo "Topic $topic not found after $max_attempts attempts"
                    exit 1
                  fi
                  echo "Attempt $attempt/$max_attempts - topic $topic not found..."
                  sleep 5
                  ((attempt++))
                done
              done
              echo "All required topics exist!"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

        # Wait for MinIO
        - name: wait-for-minio
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              echo "Waiting for MinIO..."
              until curl -f http://minio:9000/minio/health/live >/dev/null 2>&1; do
                echo "MinIO not ready, waiting..."
                sleep 5
              done
              echo "MinIO is ready!"
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"

      containers:
        - name: image-generator-adapter
          image: ai-persona-system/image-generator-adapter:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              name: metrics
          env:
            - name: SERVICE_NAME
              value: "image-generator-adapter"
            - name: SERVICE_VERSION
              value: "1.0.0"
            - name: SERVICE_ENVIRONMENT
              value: "production"
            - name: LOGGING_LEVEL
              value: "info"
            - name: STABILITY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-secrets
                  key: stability-api-key
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secrets
                  key: secret-key
          envFrom:
            - configMapRef:
                name: common-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1.5Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          # Security context
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL