#!/usr/bin/env python3
"""Generate register.sql (first install) and update.sql (re-apply to the live
row) from template.html + input_schema.json, so neither can drift from the
version-controlled source it is supposed to install.

update.sql exists because editing a component after registration is the common
case, and hand-writing that UPDATE is exactly where the live row stops matching
the file the harness tested."""
import json
import pathlib
import sys

comp = pathlib.Path(sys.argv[1])
html = (comp / "template.html").read_text()
schema = json.dumps(json.loads((comp / "input_schema.json").read_text()), indent=2)

for tag in ("$HTML$", "$SCHEMA$"):
    if tag in html or tag in schema:
        sys.exit(f"refusing to generate: source contains the dollar-quote tag {tag}")

sql = f"""\\set ON_ERROR_STOP on
-- evidence-chart — shared, evidence-sourced chart component.
-- GENERATED from components/evidence-chart/{{template.html,input_schema.json}}
-- by scripts/gen_component_register_sql.py. Edit those files and regenerate;
-- do not hand-edit this file.
--
-- The guarantee this component exists to make: the ONLY place a figure lives is
-- site_specs.evidence_base.facts. A chart definition names fact ids and never
-- restates a value, and both fields are system-resolved — resolved data beats
-- LLM content at render time, so the writer cannot supply a number even if it
-- tries. No evidence_base charts => the section is skipped, not invented.
BEGIN;
INSERT INTO content_components
  (id, name, function, display_name, description, category, semantic_tags,
   section_type, component_level, render_mode, is_dark_section, is_active,
   suitable_site_types, suitable_page_types, html_template, input_schema)
VALUES (
  gen_random_uuid(),
  'evidence-chart','evidence-chart','Evidence Chart',
  'Code-rendered bar charts whose values come from the site''s evidence_base register, never from the model. Chart definitions name fact ids; the figures, units and verified dates are read from the audited fact rows. Bars are drawn in CSS from the real value; the label and figure are real selectable text, so screen readers and the claims gate both see the number. Skipped entirely on a site with no audited series.',
  'data','["chart","data","evidence","code-rendered","brochure","infographic"]'::jsonb,
  'evidence-chart','section','agent',false,true,
  '["brochure","consultancy","professional-services","b2b"]'::jsonb,
  '["index","home","about","capabilities","landing","content"]'::jsonb,
  $HTML${html}$HTML$,
  $SCHEMA${schema}$SCHEMA$::jsonb
);
COMMIT;

SELECT function, section_type, component_level, is_active,
       length(html_template) AS template_bytes,
       jsonb_object_keys(input_schema->'fields') AS field
  FROM content_components WHERE function = 'evidence-chart';
"""

(comp / "register.sql").write_text(sql)
print(f"wrote {comp / 'register.sql'} ({len(sql)} bytes)")

fn = comp.name
update = f"""\\set ON_ERROR_STOP on
-- Re-apply {fn}'s template + input_schema to the LIVE content_components row.
-- GENERATED by scripts/gen_component_register_sql.py — do not hand-edit.
--
-- Config, so it is live on write: the next render of any page using this
-- component picks it up. Pages already rendered keep their stored HTML until
-- they are re-rendered (a page_rerender work item re-renders from stored
-- content_data with no LLM spend — see the RUNBOOK).
BEGIN;

DROP TABLE IF EXISTS bak_cc_{fn.replace('-', '_')}_pre_update;
CREATE TABLE bak_cc_{fn.replace('-', '_')}_pre_update AS
SELECT * FROM content_components WHERE function = '{fn}';

UPDATE content_components
   SET html_template = $HTML${html}$HTML$,
       input_schema  = $SCHEMA${schema}$SCHEMA$::jsonb
 WHERE function = '{fn}';

COMMIT;

-- Scoped to COLOUR variables that no active theme defines, because those are
-- the ones whose fallback silently defeats theming (a light literal on a dark
-- site). It matches a USAGE — 'var(--color-surface' — not the bare name, which
-- also appears in the template's explanatory comment; a check that reports a
-- defect in a comment trains you to ignore it.
--
-- --container-max-width and --spacing-section are also undefined fleet-wide and
-- are deliberately NOT flagged: a width or a gap falling back to its literal is
-- harmless and matches what stat-band already does. Colour is the case that
-- fails invisibly.
SELECT function, is_active, length(html_template) AS template_bytes,
       (html_template LIKE '%var(--color-surface%'
        OR html_template LIKE '%var(--color-background-alt%') AS uses_an_undefined_colour_var
  FROM content_components WHERE function = '{fn}';
"""
(comp / "update.sql").write_text(update)
print(f"wrote {comp / 'update.sql'} ({len(update)} bytes)")
