#!/usr/bin/env bash
# Rebundle a site's /assets/js/snippets.js after adding or changing a js_snippets row.
#
# WHY THIS EXISTS
# ---------------
# js_snippets is the ONLY working JS delivery lane for a section component
# (content_components.js_content publishes the file but injects no <script> tag —
# bugs_open/041, and it applies to section components, not just chrome). The
# bundle is regenerated by the `site-asset-renderer` agent, which has no
# site_work_items route: no row with handler_agent='site-asset-renderer' has ever
# existed, so the only manual trigger is the generic Kafka entry point. Its input
# contract is {required: [site_id], optional: [domain]}.
#
# Do NOT reach for a `needs_design` work item instead. That routes to
# webdesign-agent, which REGENERATES styles.css — and a regenerated stylesheet
# re-rolls the palette (design_intent.palette.reference_values is explicitly not a
# pin), which is how you lose a contrast repair while trying to ship a script.
#
# kcat -P -c 1 + heredoc: -c 1 reads exactly one message, sidestepping the
# kubectl-run stdin race that silently drops ~4 of 5 publishes at exit 0.
#
# Usage: rebundle_js_snippets_direct.sh <site_id> <domain>
set -euo pipefail

SITE_ID="$1"; DOMAIN="$2"
CORR=$(cat /proc/sys/kernel/random/uuid)
ORCH=$(cat /proc/sys/kernel/random/uuid)
REQ=$(cat /proc/sys/kernel/random/uuid)
MSG=$(cat /proc/sys/kernel/random/uuid)
TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "corr=$CORR site=$SITE_ID domain=$DOMAIN"

kubectl -n kafka run -i --rm "kcat-rebundle-$(date +%s)" \
  --image=edenhill/kcat:1.7.1 --restart=Never -- \
  kcat -P -c 1 \
  -b personae-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092 \
  -t system.agent.generic.requests \
  -H correlation_id=$CORR \
  -H orchestration_id=$ORCH \
  -H request_id=$REQ \
  -H message_id=$MSG \
  -H message_type=request \
  -H client_id=demo_client \
  -H action=orchestrate \
  -H sender_agent_type=cli \
  -H sender_agent_id=cli-user \
  -H responses_topic=system.agent.generic.responses \
  -H timestamp=$TS <<JSON
{"action":"orchestrate","config":{"agent_type":"site-asset-renderer"},"input_data":{"site_id":"$SITE_ID","domain":"$DOMAIN"}}
JSON

echo "CORR=$CORR"
echo
echo "Verify by the ARTEFACT, not the run: the bundle's own header counts its snippets."
echo "  curl -s https://$DOMAIN/assets/js/snippets.js | head -5"
echo "and grep for a marker string from the snippet you just added."
