apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      imagePullSecrets:
        - name: docker-hub-creds
      serviceAccountName: ai-persona-app
      containers:
        - name: auth-service
          env:
            - name: AUTH_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: personae-dev-secrets
                  key: auth-db-password