apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: personae-prod
resources:
  - ../../../base

labels:
  - pairs:
      environment: production
      region: uk

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: reasoning-agent