-- SEED — adoption-tracker / adoption-tracker-listing / protocol-tracker /
-- protocol-tracker-listing components (Phase E)
--
-- APPLY ONLY AFTER an image carrying the Phase E resolvers is deployed and
-- pod-verified (satisfied: v1.0.1165, 2026-07-26 —
-- `strings /app/agent-chassis | grep -c adoption_tracker_full` → 1, positive
-- and negative controls clean).
--
-- Shape follows SEED_directory_components.sql (the model pair) exactly:
-- component_level='section' (chrome-level JS silently dropped, bugs 041),
-- dual-layer (server html_template from query.* + js_content refreshing from
-- the published JSON), DOM built via createElement/textContent — never
-- innerHTML string-building — because entity names/summaries/quotes are
-- third-party text from a scrape+LLM pipeline (widest injection surface we
-- have). innerHTML is only ever assigned "" to clear a container.
--
-- TWO LESSONS APPLIED THAT THE MODEL PAIR LEARNED THE HARD WAY:
--   1. The <style> block ships IN html_template from day one (bugs 072: the
--      model pair rendered bare for a day because nothing else styles a
--      component; hero/call-to-action inline theirs, so do we). Class names
--      reuse the model-directory vocabulary (.model-card etc.) via a shared
--      prefix ONLY where semantics match; adoption cards get their own
--      .adoption-card classes so a later restyle of one register does not
--      silently restyle the other.
--   2. Filenames/query names here MUST match render_directory_action.go's
--      directoryPublishProfiles and queryresolve's switch exactly — a typo
--      fails only at render time, silently, so each is copied verbatim:
--      company:  query.adoption_tracker[_full], data/adoption-tracker[-full].json
--      protocol: query.protocol_tracker[_full], data/protocol-tracker[-full].json
--
-- Claim fields render raw (snake_case, e.g. roi_claimed) in both layers —
-- same as the live model directory. A display-name map is polish for BOTH
-- registers at once, later, or the layers drift.
--
-- REMINDER (brochure landmine): these rows make the components EXIST; the
-- content-gap path selects them because the check's gap spec names them
-- explicitly (check_directory.go profile Suggestion). The build-site-planner
-- prompt does NOT name them yet — a from-scratch site plan will not choose
-- them. Fine for the gap-pipeline pilot; note it before any fleet rollout.

BEGIN;

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. adoption-tracker — homepage snippet (kind='company')
-- ═══════════════════════════════════════════════════════════════════════════
INSERT INTO content_components (
    name, display_name, description, function, category, component_level,
    section_type, render_mode, suitable_site_types, suitable_page_types,
    created_from, input_schema, html_template, js_content
)
SELECT
    'AI Adoption Tracker', 'Adoption Tracker', 'Homepage snippet: cited tracker of organisations deploying AI agents (claimed results and how they were measured), server-rendered from query.adoption_tracker, refreshed client-side from data/adoption-tracker.json',
    'adoption-tracker', 'content', 'section', 'adoption-tracker', 'template',
    '["brochure"]'::jsonb, '[]'::jsonb, 'manual',
    $schema${
  "notes": "entries are server-rendered from query.adoption_tracker (Phase E, kind=company); adoption-tracker.js refreshes client-side from data/adoption-tracker.json. Resolver output is pre-escaped for the template; the JSON path is raw text, escaped client-side via textContent/createElement — never innerHTML string-building. A claim's roi_claimed and roi_basis are separate fields by design: 'stated, method not given' is the honest record.",
  "fields": {
    "entries": {
      "type": "array",
      "items": {
        "slug": {"type": "text"}, "name": {"type": "text"}, "owner": {"type": "text"},
        "summary": {"type": "text"}, "claims": {"type": "array"},
        "docs_url": {"type": "url"}, "video_urls": {"type": "array"}
      },
      "limit": 12,
      "source": "query.adoption_tracker",
      "required": false,
      "on_missing": "skip_field"
    },
    "headline": {
      "type": "text", "source": "llm", "default": "Who is actually deploying AI agents", "required": true,
      "description": "Section heading — generated by content writer, tailored to site identity"
    },
    "subheadline": {
      "type": "text", "source": "llm", "required": false,
      "description": "Optional subheading"
    }
  },
  "data_source": "/data/adoption-tracker.json",
  "render_action": "render_directory",
  "refresh_interval": "6h"
}$schema$::jsonb,
    $html$<style>
.adoption-tracker-section { padding: var(--spacing-section, 4rem 0); }
.adoption-tracker-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 1.5rem;
    margin-top: 2rem;
}
.adoption-card {
    border: 1px solid var(--section-border, var(--color-border, rgba(0,0,0,0.12)));
    border-radius: 8px;
    background: var(--section-surface, var(--color-surface, rgba(0,0,0,0.02)));
    overflow: hidden;
    transition: transform 0.2s, box-shadow 0.2s;
}
.adoption-card:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(0,0,0,0.08); }
.adoption-card-content { padding: 1.25rem 1.5rem 1.5rem; }
.adoption-card-title {
    margin: 0 0 0.5rem;
    font-size: 1.15rem;
    line-height: 1.3;
    color: var(--section-heading, var(--color-heading, inherit));
}
.adoption-card-owner {
    display: block; font-size: 0.8rem; font-weight: 500;
    letter-spacing: 0.04em; text-transform: uppercase; opacity: 0.65; margin-top: 0.25rem;
}
.adoption-card-summary { margin: 0 0 1rem; font-size: 0.95rem; line-height: 1.55; color: var(--section-text, inherit); }
.adoption-card-claims {
    list-style: none; margin: 0 0 0.5rem; padding: 0;
    border-top: 1px solid var(--section-border, rgba(0,0,0,0.08));
}
.adoption-card-claims li {
    display: flex; flex-wrap: wrap; align-items: baseline; gap: 0.4rem;
    padding: 0.5rem 0; border-bottom: 1px solid var(--section-border, rgba(0,0,0,0.08));
    font-size: 0.9rem;
}
.adoption-claim-field { flex: 1 1 45%; opacity: 0.7; text-transform: capitalize; }
.adoption-claim-value { font-weight: 600; }
.adoption-claim-source {
    font-size: 0.75rem; text-decoration: none; opacity: 0.6;
    border-bottom: 1px dotted currentColor;
}
.adoption-claim-source:hover { opacity: 1; }
.adoption-tracker-section-footer { margin-top: 2rem; text-align: center; }
.adoption-tracker-more-link {
    display: inline-block; font-weight: 600; text-decoration: none;
    color: var(--color-primary, #1e40af);
}
.adoption-tracker-more-link:hover { text-decoration: underline; }
.adoption-tracker-empty { opacity: 0.7; }
@media (max-width: 600px) { .adoption-tracker-grid { grid-template-columns: 1fr; } }
</style>
<!-- adoption-tracker component -->
<section data-component="adoption-tracker" class="adoption-tracker-section section-padding">
  <div class="container">
    <h2 class="section-heading" id="adoption-tracker-headline">{{.headline}}</h2>
    {{if .subheadline}}<p class="section-subheadline" id="adoption-tracker-subheadline">{{.subheadline}}</p>{{end}}
    <div class="adoption-tracker-grid" id="adoption-tracker-container">
      {{if .entries}}{{range .entries}}
      <article class="adoption-card"><div class="adoption-card-content">
        <h3 class="adoption-card-title">{{.name}}{{if .owner}} <span class="adoption-card-owner">{{.owner}}</span>{{end}}</h3>
        {{if .summary}}<p class="adoption-card-summary">{{.summary}}</p>{{end}}
        {{if .claims}}<ul class="adoption-card-claims">
          {{range .claims}}<li><span class="adoption-claim-field">{{.field}}</span> <span class="adoption-claim-value">{{.value}}{{if .unit}} {{.unit}}{{end}}</span>{{if .url}} <a href="{{.url}}" target="_blank" rel="noopener noreferrer" class="adoption-claim-source">source</a>{{end}}</li>{{end}}
        </ul>{{end}}
      </div></article>
      {{end}}{{else}}<noscript>
        <p class="adoption-tracker-empty">Enable JavaScript to see the adoption tracker.</p>
      </noscript>{{end}}
    </div>
    <div id="adoption-tracker-footer"></div>
  </div>
</section>
<script src="/tools/assets/adoption-tracker.js"></script>$html$,
    $js$(function() {
  function el(tag, opts) {
    var e = document.createElement(tag);
    opts = opts || {};
    if (opts.className) e.className = opts.className;
    if (opts.text) e.textContent = opts.text;
    if (opts.href) { e.href = opts.href; e.target = "_blank"; e.rel = "noopener noreferrer"; }
    return e;
  }
  function renderCard(entry) {
    var card = el("article", {className: "adoption-card"});
    var content = el("div", {className: "adoption-card-content"});
    var title = el("h3", {className: "adoption-card-title", text: entry.name || ""});
    if (entry.owner && entry.owner !== entry.name) {
      title.appendChild(el("span", {className: "adoption-card-owner", text: " " + entry.owner}));
    }
    content.appendChild(title);
    if (entry.summary) {
      content.appendChild(el("p", {className: "adoption-card-summary", text: entry.summary}));
    }
    if (entry.claims && entry.claims.length > 0) {
      var list = document.createElement("ul");
      list.className = "adoption-card-claims";
      entry.claims.forEach(function(c) {
        var li = document.createElement("li");
        li.appendChild(el("span", {className: "adoption-claim-field", text: (c.field || "").split("_").join(" ")}));
        li.appendChild(document.createTextNode(" "));
        var valueText = c.value || "";
        if (c.unit) valueText += " " + c.unit;
        li.appendChild(el("span", {className: "adoption-claim-value", text: valueText}));
        if (c.url) {
          li.appendChild(document.createTextNode(" "));
          li.appendChild(el("a", {className: "adoption-claim-source", text: "source", href: c.url}));
        }
        list.appendChild(li);
      });
      content.appendChild(list);
    }
    card.appendChild(content);
    return card;
  }
  fetch("/data/adoption-tracker.json")
    .then(function(r) { return r.json(); })
    .then(function(data) {
      var headlineEl = document.getElementById("adoption-tracker-headline");
      if (headlineEl && data.headline) headlineEl.textContent = data.headline;
      var container = document.getElementById("adoption-tracker-container");
      if (container && data.entries && data.entries.length > 0) {
        container.innerHTML = "";
        data.entries.forEach(function(entry) { container.appendChild(renderCard(entry)); });
      }
      var footer = document.getElementById("adoption-tracker-footer");
      if (footer && data.directory_url) {
        footer.innerHTML = "";
        var wrap = document.createElement("div");
        wrap.className = "adoption-tracker-section-footer";
        var link = el("a", {className: "adoption-tracker-more-link", text: data.directory_label || "See every tracked deployment"});
        link.href = data.directory_url;
        wrap.appendChild(link);
        footer.appendChild(wrap);
      }
    })
    .catch(function() {});
})();$js$
WHERE NOT EXISTS (SELECT 1 FROM content_components WHERE function = 'adoption-tracker');

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. adoption-tracker-listing — dedicated page (kind='company', full depth)
-- ═══════════════════════════════════════════════════════════════════════════
INSERT INTO content_components (
    name, display_name, description, function, category, component_level,
    section_type, render_mode, suitable_site_types, suitable_page_types,
    created_from, input_schema, html_template, js_content
)
SELECT
    'AI Adoption Tracker (full listing)', 'Adoption Tracker — Full Listing', 'Dedicated adoption-tracker page: every tracked organisation with its cited deployment claims, server-rendered from query.adoption_tracker_full, refreshed client-side from data/adoption-tracker-full.json',
    'adoption-tracker-listing', 'content', 'section', 'adoption-tracker-listing', 'template',
    '["brochure"]'::jsonb, '["adoption-tracker"]'::jsonb, 'manual',
    $schema${
  "notes": "entries are server-rendered from query.adoption_tracker_full; adoption-tracker-listing.js refreshes client-side from data/adoption-tracker-full.json. Same escaping discipline as the adoption-tracker snippet component.",
  "fields": {
    "entries": {
      "type": "array",
      "items": {
        "slug": {"type": "text"}, "name": {"type": "text"}, "owner": {"type": "text"},
        "summary": {"type": "text"}, "claims": {"type": "array"},
        "docs_url": {"type": "url"}, "video_urls": {"type": "array"}
      },
      "limit": 50,
      "source": "query.adoption_tracker_full",
      "required": false,
      "on_missing": "skip_field"
    },
    "headline": {
      "type": "text", "source": "llm", "default": "Who is actually deploying AI agents", "required": true,
      "description": "Page section heading"
    },
    "subheadline": {
      "type": "text", "source": "llm", "required": false,
      "description": "One honest sentence on what this tracker is: named organisations, cited sources, and — where the source said it — how the result was measured. No anonymous 'a Fortune 500 company' entries."
    }
  },
  "data_source": "/data/adoption-tracker-full.json",
  "render_action": "render_directory",
  "refresh_interval": "6h"
}$schema$::jsonb,
    $html$<style>
.adoption-tracker-listing-section { padding: var(--spacing-section, 4rem 0); }
.adoption-tracker-grid--full {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: 1.5rem;
    margin-top: 2rem;
}
.adoption-card {
    border: 1px solid var(--section-border, var(--color-border, rgba(0,0,0,0.12)));
    border-radius: 8px;
    background: var(--section-surface, var(--color-surface, rgba(0,0,0,0.02)));
    overflow: hidden;
    transition: transform 0.2s, box-shadow 0.2s;
}
.adoption-card:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(0,0,0,0.08); }
.adoption-card-content { padding: 1.25rem 1.5rem 1.5rem; }
.adoption-card-title { margin: 0 0 0.5rem; font-size: 1.15rem; line-height: 1.3; color: var(--section-heading, var(--color-heading, inherit)); }
.adoption-card-owner { display: block; font-size: 0.8rem; font-weight: 500; letter-spacing: 0.04em; text-transform: uppercase; opacity: 0.65; margin-top: 0.25rem; }
.adoption-card-summary { margin: 0 0 1rem; font-size: 0.95rem; line-height: 1.55; color: var(--section-text, inherit); }
.adoption-card-claims { list-style: none; margin: 0 0 0.5rem; padding: 0; border-top: 1px solid var(--section-border, rgba(0,0,0,0.08)); }
.adoption-card-claims li { display: flex; flex-wrap: wrap; align-items: baseline; gap: 0.4rem; padding: 0.5rem 0; border-bottom: 1px solid var(--section-border, rgba(0,0,0,0.08)); font-size: 0.9rem; }
.adoption-claim-field { flex: 1 1 45%; opacity: 0.7; text-transform: capitalize; }
.adoption-claim-value { font-weight: 600; }
.adoption-claim-source { font-size: 0.75rem; text-decoration: none; opacity: 0.6; border-bottom: 1px dotted currentColor; }
.adoption-claim-source:hover { opacity: 1; }
@media (max-width: 600px) { .adoption-tracker-grid--full { grid-template-columns: 1fr; } }
</style>
<!-- adoption-tracker-listing component -->
<section data-component="adoption-tracker-listing" class="adoption-tracker-listing-section section-padding">
  <div class="container">
    <h2 class="section-heading" id="adoption-tracker-full-headline">{{.headline}}</h2>
    {{if .subheadline}}<p class="section-subheadline" id="adoption-tracker-full-subheadline">{{.subheadline}}</p>{{end}}
    <div class="adoption-tracker-grid adoption-tracker-grid--full" id="adoption-tracker-full-container">
      {{if .entries}}{{range .entries}}
      <article class="adoption-card"><div class="adoption-card-content">
        <h3 class="adoption-card-title">{{.name}}{{if .owner}} <span class="adoption-card-owner">{{.owner}}</span>{{end}}</h3>
        {{if .summary}}<p class="adoption-card-summary">{{.summary}}</p>{{end}}
        {{if .claims}}<ul class="adoption-card-claims">
          {{range .claims}}<li><span class="adoption-claim-field">{{.field}}</span> <span class="adoption-claim-value">{{.value}}{{if .unit}} {{.unit}}{{end}}</span>{{if .url}} <a href="{{.url}}" target="_blank" rel="noopener noreferrer" class="adoption-claim-source">source</a>{{end}}</li>{{end}}
        </ul>{{end}}
      </div></article>
      {{end}}{{else}}<noscript>
        <p class="adoption-tracker-empty">Enable JavaScript to see the adoption tracker.</p>
      </noscript>{{end}}
    </div>
  </div>
</section>
<script src="/tools/assets/adoption-tracker-listing.js"></script>$html$,
    $js$(function() {
  function el(tag, opts) {
    var e = document.createElement(tag);
    opts = opts || {};
    if (opts.className) e.className = opts.className;
    if (opts.text) e.textContent = opts.text;
    if (opts.href) { e.href = opts.href; e.target = "_blank"; e.rel = "noopener noreferrer"; }
    return e;
  }
  function renderCard(entry) {
    var card = el("article", {className: "adoption-card"});
    var content = el("div", {className: "adoption-card-content"});
    var title = el("h3", {className: "adoption-card-title", text: entry.name || ""});
    if (entry.owner && entry.owner !== entry.name) {
      title.appendChild(el("span", {className: "adoption-card-owner", text: " " + entry.owner}));
    }
    content.appendChild(title);
    if (entry.summary) content.appendChild(el("p", {className: "adoption-card-summary", text: entry.summary}));
    if (entry.claims && entry.claims.length > 0) {
      var list = document.createElement("ul");
      list.className = "adoption-card-claims";
      entry.claims.forEach(function(c) {
        var li = document.createElement("li");
        li.appendChild(el("span", {className: "adoption-claim-field", text: (c.field || "").split("_").join(" ")}));
        li.appendChild(document.createTextNode(" "));
        var valueText = c.value || "";
        if (c.unit) valueText += " " + c.unit;
        li.appendChild(el("span", {className: "adoption-claim-value", text: valueText}));
        if (c.url) {
          li.appendChild(document.createTextNode(" "));
          li.appendChild(el("a", {className: "adoption-claim-source", text: "source", href: c.url}));
        }
        list.appendChild(li);
      });
      content.appendChild(list);
    }
    card.appendChild(content);
    return card;
  }
  fetch("/data/adoption-tracker-full.json")
    .then(function(r) { return r.json(); })
    .then(function(data) {
      var headlineEl = document.getElementById("adoption-tracker-full-headline");
      if (headlineEl && data.headline) headlineEl.textContent = data.headline;
      var container = document.getElementById("adoption-tracker-full-container");
      if (container && data.entries && data.entries.length > 0) {
        container.innerHTML = "";
        data.entries.forEach(function(entry) { container.appendChild(renderCard(entry)); });
      }
    })
    .catch(function() {});
})();$js$
WHERE NOT EXISTS (SELECT 1 FROM content_components WHERE function = 'adoption-tracker-listing');

-- ═══════════════════════════════════════════════════════════════════════════
-- 3+4. protocol-tracker / protocol-tracker-listing (kind='protocol')
-- Structurally identical; protocol entries reuse the adoption-card classes
-- (same semantics: entity + cited claims), so no third stylesheet.
-- ═══════════════════════════════════════════════════════════════════════════
INSERT INTO content_components (
    name, display_name, description, function, category, component_level,
    section_type, render_mode, suitable_site_types, suitable_page_types,
    created_from, input_schema, html_template, js_content
)
SELECT
    'Agent Protocol Tracker', 'Protocol Tracker', 'Homepage snippet: cited tracker of agent communication protocols (MCP, A2A, ACP, ...) and their uptake, server-rendered from query.protocol_tracker, refreshed client-side from data/protocol-tracker.json',
    'protocol-tracker', 'content', 'section', 'protocol-tracker', 'template',
    '["brochure"]'::jsonb, '[]'::jsonb, 'manual',
    $schema${
  "notes": "entries are server-rendered from query.protocol_tracker (Phase E, kind=protocol); protocol-tracker.js refreshes client-side from data/protocol-tracker.json. Same escaping discipline as adoption-tracker.",
  "fields": {
    "entries": {
      "type": "array",
      "items": {
        "slug": {"type": "text"}, "name": {"type": "text"}, "owner": {"type": "text"},
        "summary": {"type": "text"}, "claims": {"type": "array"}, "docs_url": {"type": "url"}
      },
      "limit": 12,
      "source": "query.protocol_tracker",
      "required": false,
      "on_missing": "skip_field"
    },
    "headline": {
      "type": "text", "source": "llm", "default": "Agent communication protocols", "required": true,
      "description": "Section heading"
    },
    "subheadline": {"type": "text", "source": "llm", "required": false}
  },
  "data_source": "/data/protocol-tracker.json",
  "render_action": "render_directory",
  "refresh_interval": "6h"
}$schema$::jsonb,
    $html$<style>
/* Own copy, not shared-by-co-location: a component that depends on a SIBLING
   component's <style> block is unstyled the day it lands on a page alone —
   the exact bugs_open/072 class this file's header says it applies. */
.adoption-tracker-section { padding: var(--spacing-section, 4rem 0); }
.adoption-tracker-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 1.5rem; margin-top: 2rem; }
.adoption-card { border: 1px solid var(--section-border, var(--color-border, rgba(0,0,0,0.12))); border-radius: 8px; background: var(--section-surface, var(--color-surface, rgba(0,0,0,0.02))); overflow: hidden; transition: transform 0.2s, box-shadow 0.2s; }
.adoption-card:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(0,0,0,0.08); }
.adoption-card-content { padding: 1.25rem 1.5rem 1.5rem; }
.adoption-card-title { margin: 0 0 0.5rem; font-size: 1.15rem; line-height: 1.3; color: var(--section-heading, var(--color-heading, inherit)); }
.adoption-card-owner { display: block; font-size: 0.8rem; font-weight: 500; letter-spacing: 0.04em; text-transform: uppercase; opacity: 0.65; margin-top: 0.25rem; }
.adoption-card-summary { margin: 0 0 1rem; font-size: 0.95rem; line-height: 1.55; color: var(--section-text, inherit); }
.adoption-card-claims { list-style: none; margin: 0 0 0.5rem; padding: 0; border-top: 1px solid var(--section-border, rgba(0,0,0,0.08)); }
.adoption-card-claims li { display: flex; flex-wrap: wrap; align-items: baseline; gap: 0.4rem; padding: 0.5rem 0; border-bottom: 1px solid var(--section-border, rgba(0,0,0,0.08)); font-size: 0.9rem; }
.adoption-claim-field { flex: 1 1 45%; opacity: 0.7; text-transform: capitalize; }
.adoption-claim-value { font-weight: 600; }
.adoption-claim-source { font-size: 0.75rem; text-decoration: none; opacity: 0.6; border-bottom: 1px dotted currentColor; }
.adoption-claim-source:hover { opacity: 1; }
.adoption-tracker-empty { opacity: 0.7; }
@media (max-width: 600px) { .adoption-tracker-grid { grid-template-columns: 1fr; } }
</style>
<!-- protocol-tracker component -->
<section data-component="protocol-tracker" class="adoption-tracker-section section-padding">
  <div class="container">
    <h2 class="section-heading" id="protocol-tracker-headline">{{.headline}}</h2>
    {{if .subheadline}}<p class="section-subheadline" id="protocol-tracker-subheadline">{{.subheadline}}</p>{{end}}
    <div class="adoption-tracker-grid" id="protocol-tracker-container">
      {{if .entries}}{{range .entries}}
      <article class="adoption-card"><div class="adoption-card-content">
        <h3 class="adoption-card-title">{{.name}}{{if .owner}} <span class="adoption-card-owner">{{.owner}}</span>{{end}}</h3>
        {{if .summary}}<p class="adoption-card-summary">{{.summary}}</p>{{end}}
        {{if .claims}}<ul class="adoption-card-claims">
          {{range .claims}}<li><span class="adoption-claim-field">{{.field}}</span> <span class="adoption-claim-value">{{.value}}{{if .unit}} {{.unit}}{{end}}</span>{{if .url}} <a href="{{.url}}" target="_blank" rel="noopener noreferrer" class="adoption-claim-source">source</a>{{end}}</li>{{end}}
        </ul>{{end}}
      </div></article>
      {{end}}{{else}}<noscript>
        <p class="adoption-tracker-empty">Enable JavaScript to see the protocol tracker.</p>
      </noscript>{{end}}
    </div>
  </div>
</section>
<script src="/tools/assets/protocol-tracker.js"></script>$html$,
    $js$(function() {
  function el(tag, opts) {
    var e = document.createElement(tag);
    opts = opts || {};
    if (opts.className) e.className = opts.className;
    if (opts.text) e.textContent = opts.text;
    if (opts.href) { e.href = opts.href; e.target = "_blank"; e.rel = "noopener noreferrer"; }
    return e;
  }
  function renderCard(entry) {
    var card = el("article", {className: "adoption-card"});
    var content = el("div", {className: "adoption-card-content"});
    var title = el("h3", {className: "adoption-card-title", text: entry.name || ""});
    if (entry.owner && entry.owner !== entry.name) {
      title.appendChild(el("span", {className: "adoption-card-owner", text: " " + entry.owner}));
    }
    content.appendChild(title);
    if (entry.summary) content.appendChild(el("p", {className: "adoption-card-summary", text: entry.summary}));
    if (entry.claims && entry.claims.length > 0) {
      var list = document.createElement("ul");
      list.className = "adoption-card-claims";
      entry.claims.forEach(function(c) {
        var li = document.createElement("li");
        li.appendChild(el("span", {className: "adoption-claim-field", text: (c.field || "").split("_").join(" ")}));
        li.appendChild(document.createTextNode(" "));
        var valueText = c.value || "";
        if (c.unit) valueText += " " + c.unit;
        li.appendChild(el("span", {className: "adoption-claim-value", text: valueText}));
        if (c.url) {
          li.appendChild(document.createTextNode(" "));
          li.appendChild(el("a", {className: "adoption-claim-source", text: "source", href: c.url}));
        }
        list.appendChild(li);
      });
      content.appendChild(list);
    }
    card.appendChild(content);
    return card;
  }
  fetch("/data/protocol-tracker.json")
    .then(function(r) { return r.json(); })
    .then(function(data) {
      var headlineEl = document.getElementById("protocol-tracker-headline");
      if (headlineEl && data.headline) headlineEl.textContent = data.headline;
      var container = document.getElementById("protocol-tracker-container");
      if (container && data.entries && data.entries.length > 0) {
        container.innerHTML = "";
        data.entries.forEach(function(entry) { container.appendChild(renderCard(entry)); });
      }
    })
    .catch(function() {});
})();$js$
WHERE NOT EXISTS (SELECT 1 FROM content_components WHERE function = 'protocol-tracker');

INSERT INTO content_components (
    name, display_name, description, function, category, component_level,
    section_type, render_mode, suitable_site_types, suitable_page_types,
    created_from, input_schema, html_template, js_content
)
SELECT
    'Agent Protocol Tracker (full listing)', 'Protocol Tracker — Full Listing', 'Dedicated protocol-tracker page: every tracked agent communication protocol with its cited facts, server-rendered from query.protocol_tracker_full, refreshed client-side from data/protocol-tracker-full.json',
    'protocol-tracker-listing', 'content', 'section', 'protocol-tracker-listing', 'template',
    '["brochure"]'::jsonb, '["protocol-tracker"]'::jsonb, 'manual',
    $schema${
  "notes": "entries are server-rendered from query.protocol_tracker_full; protocol-tracker-listing.js refreshes client-side from data/protocol-tracker-full.json.",
  "fields": {
    "entries": {
      "type": "array",
      "items": {
        "slug": {"type": "text"}, "name": {"type": "text"}, "owner": {"type": "text"},
        "summary": {"type": "text"}, "claims": {"type": "array"}, "docs_url": {"type": "url"}
      },
      "limit": 50,
      "source": "query.protocol_tracker_full",
      "required": false,
      "on_missing": "skip_field"
    },
    "headline": {
      "type": "text", "source": "llm", "default": "Agent communication protocols", "required": true,
      "description": "Page section heading"
    },
    "subheadline": {"type": "text", "source": "llm", "required": false}
  },
  "data_source": "/data/protocol-tracker-full.json",
  "render_action": "render_directory",
  "refresh_interval": "6h"
}$schema$::jsonb,
    $html$<style>
.adoption-tracker-listing-section { padding: var(--spacing-section, 4rem 0); }
.adoption-tracker-grid--full { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 1.5rem; margin-top: 2rem; }
.adoption-tracker-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 1.5rem; margin-top: 2rem; }
.adoption-card { border: 1px solid var(--section-border, var(--color-border, rgba(0,0,0,0.12))); border-radius: 8px; background: var(--section-surface, var(--color-surface, rgba(0,0,0,0.02))); overflow: hidden; transition: transform 0.2s, box-shadow 0.2s; }
.adoption-card:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(0,0,0,0.08); }
.adoption-card-content { padding: 1.25rem 1.5rem 1.5rem; }
.adoption-card-title { margin: 0 0 0.5rem; font-size: 1.15rem; line-height: 1.3; color: var(--section-heading, var(--color-heading, inherit)); }
.adoption-card-owner { display: block; font-size: 0.8rem; font-weight: 500; letter-spacing: 0.04em; text-transform: uppercase; opacity: 0.65; margin-top: 0.25rem; }
.adoption-card-summary { margin: 0 0 1rem; font-size: 0.95rem; line-height: 1.55; color: var(--section-text, inherit); }
.adoption-card-claims { list-style: none; margin: 0 0 0.5rem; padding: 0; border-top: 1px solid var(--section-border, rgba(0,0,0,0.08)); }
.adoption-card-claims li { display: flex; flex-wrap: wrap; align-items: baseline; gap: 0.4rem; padding: 0.5rem 0; border-bottom: 1px solid var(--section-border, rgba(0,0,0,0.08)); font-size: 0.9rem; }
.adoption-claim-field { flex: 1 1 45%; opacity: 0.7; text-transform: capitalize; }
.adoption-claim-value { font-weight: 600; }
.adoption-claim-source { font-size: 0.75rem; text-decoration: none; opacity: 0.6; border-bottom: 1px dotted currentColor; }
.adoption-claim-source:hover { opacity: 1; }
@media (max-width: 600px) { .adoption-tracker-grid--full, .adoption-tracker-grid { grid-template-columns: 1fr; } }
</style>
<!-- protocol-tracker-listing component -->
<section data-component="protocol-tracker-listing" class="adoption-tracker-listing-section section-padding">
  <div class="container">
    <h2 class="section-heading" id="protocol-tracker-full-headline">{{.headline}}</h2>
    {{if .subheadline}}<p class="section-subheadline" id="protocol-tracker-full-subheadline">{{.subheadline}}</p>{{end}}
    <div class="adoption-tracker-grid adoption-tracker-grid--full" id="protocol-tracker-full-container">
      {{if .entries}}{{range .entries}}
      <article class="adoption-card"><div class="adoption-card-content">
        <h3 class="adoption-card-title">{{.name}}{{if .owner}} <span class="adoption-card-owner">{{.owner}}</span>{{end}}</h3>
        {{if .summary}}<p class="adoption-card-summary">{{.summary}}</p>{{end}}
        {{if .claims}}<ul class="adoption-card-claims">
          {{range .claims}}<li><span class="adoption-claim-field">{{.field}}</span> <span class="adoption-claim-value">{{.value}}{{if .unit}} {{.unit}}{{end}}</span>{{if .url}} <a href="{{.url}}" target="_blank" rel="noopener noreferrer" class="adoption-claim-source">source</a>{{end}}</li>{{end}}
        </ul>{{end}}
      </div></article>
      {{end}}{{else}}<noscript>
        <p class="adoption-tracker-empty">Enable JavaScript to see the protocol tracker.</p>
      </noscript>{{end}}
    </div>
  </div>
</section>
<script src="/tools/assets/protocol-tracker-listing.js"></script>$html$,
    $js$(function() {
  function el(tag, opts) {
    var e = document.createElement(tag);
    opts = opts || {};
    if (opts.className) e.className = opts.className;
    if (opts.text) e.textContent = opts.text;
    if (opts.href) { e.href = opts.href; e.target = "_blank"; e.rel = "noopener noreferrer"; }
    return e;
  }
  function renderCard(entry) {
    var card = el("article", {className: "adoption-card"});
    var content = el("div", {className: "adoption-card-content"});
    var title = el("h3", {className: "adoption-card-title", text: entry.name || ""});
    if (entry.owner && entry.owner !== entry.name) {
      title.appendChild(el("span", {className: "adoption-card-owner", text: " " + entry.owner}));
    }
    content.appendChild(title);
    if (entry.summary) content.appendChild(el("p", {className: "adoption-card-summary", text: entry.summary}));
    if (entry.claims && entry.claims.length > 0) {
      var list = document.createElement("ul");
      list.className = "adoption-card-claims";
      entry.claims.forEach(function(c) {
        var li = document.createElement("li");
        li.appendChild(el("span", {className: "adoption-claim-field", text: (c.field || "").split("_").join(" ")}));
        li.appendChild(document.createTextNode(" "));
        var valueText = c.value || "";
        if (c.unit) valueText += " " + c.unit;
        li.appendChild(el("span", {className: "adoption-claim-value", text: valueText}));
        if (c.url) {
          li.appendChild(document.createTextNode(" "));
          li.appendChild(el("a", {className: "adoption-claim-source", text: "source", href: c.url}));
        }
        list.appendChild(li);
      });
      content.appendChild(list);
    }
    card.appendChild(content);
    return card;
  }
  fetch("/data/protocol-tracker-full.json")
    .then(function(r) { return r.json(); })
    .then(function(data) {
      var headlineEl = document.getElementById("protocol-tracker-full-headline");
      if (headlineEl && data.headline) headlineEl.textContent = data.headline;
      var container = document.getElementById("protocol-tracker-full-container");
      if (container && data.entries && data.entries.length > 0) {
        container.innerHTML = "";
        data.entries.forEach(function(entry) { container.appendChild(renderCard(entry)); });
      }
    })
    .catch(function() {});
})();$js$
WHERE NOT EXISTS (SELECT 1 FROM content_components WHERE function = 'protocol-tracker-listing');

SELECT function, component_level, html_template LIKE '%<style%' AS has_style
FROM content_components WHERE function IN ('adoption-tracker','adoption-tracker-listing','protocol-tracker','protocol-tracker-listing');

COMMIT;
