-- SEED — model-directory / model-directory-listing components (Phase C)
--
-- APPLY ONLY AFTER an image carrying `render_model_directory` and the
-- `query.model_directory` / `query.model_directory_full` resolvers is
-- deployed and pod-verified:
--
--   kubectl -n ai-persona-system exec <agent-chassis-pod> -- \
--     sh -c 'strings /app/agent-chassis | grep -c render_model_directory'
--
-- component_level MUST be 'section' — chrome-level JS is silently dropped
-- (bugs_open/041). js_content gets auto-deployed as
-- /tools/assets/{function}.js by the existing store_generated_component /
-- rerender_single_page machinery (store_generated_component_action.go:916,
-- rerender_single_page_action.go:186) — no separate asset deployment step.
--
-- SECURITY NOTE (deliberate divergence from the latest-news precedent): the
-- latest-news component's js_content builds card HTML via raw string
-- concatenation of feed text into innerHTML. Model/company names, summaries
-- and cited quotes here are ALSO third-party text, but researched via a
-- web-scrape + LLM-extraction pipeline rather than a curated feed, which is
-- a wider attack surface for injected markup. Both components' js_content
-- below build the DOM via createElement/textContent instead of innerHTML
-- string-building, so untrusted text can never be interpreted as markup —
-- .innerHTML is used only to CLEAR a container (assigned "", never
-- concatenated with data) before appending real nodes.
--
-- REMINDER (bit the brochure-library workstream before): naming these two
-- rows here is not enough to make them selectable. They must ALSO be named
-- in the build-site-planner / site-architect prompt
-- (brochure_component_library/HANDOFF_2026-07-21_start_here.md:141) before a
-- site plan will ever choose them — a follow-up step, not done by this file.

BEGIN;

INSERT INTO content_components (
    name, display_name, description, function, category, component_level,
    section_type, render_mode, suitable_site_types, suitable_page_types,
    created_from, input_schema, html_template, js_content
)
SELECT
    'AI Model Directory', 'Model Directory', 'Homepage snippet: cited AI model directory entries (price, licence, links), server-rendered from query.model_directory, refreshed client-side from data/model-directory.json',
    'model-directory', 'content', 'section', 'model-directory', 'template',
    '["brochure"]'::jsonb, '[]'::jsonb, 'manual',
    $schema${
  "notes": "entries are server-rendered from query.model_directory (model_directory_pipeline Phase C); model-directory.js refreshes client-side from data/model-directory.json. Resolver output is pre-escaped for the template; the JSON path is raw text, escaped client-side via textContent/createElement — never innerHTML string-building.",
  "fields": {
    "entries": {
      "type": "array",
      "items": {
        "slug": {"type": "text"}, "name": {"type": "text"}, "owner": {"type": "text"},
        "summary": {"type": "text"}, "claims": {"type": "array"},
        "docs_url": {"type": "url"}, "weights_url": {"type": "url"}, "wrapper_url": {"type": "url"}
      },
      "limit": 12,
      "source": "query.model_directory",
      "required": false,
      "on_missing": "skip_field"
    },
    "headline": {
      "type": "text", "source": "llm", "default": "AI Model Directory", "required": true,
      "description": "Section heading — generated by content writer, tailored to site identity"
    },
    "subheadline": {
      "type": "text", "source": "llm", "required": false,
      "description": "Optional subheading"
    }
  },
  "data_source": "/data/model-directory.json",
  "render_action": "render_model_directory",
  "refresh_interval": "6h"
}$schema$::jsonb,
    $html$<!-- model-directory component -->
<section data-component="model-directory" class="model-directory-section section-padding">
  <div class="container">
    <h2 class="section-heading" id="model-directory-headline">{{.headline}}</h2>
    {{if .subheadline}}<p class="section-subheadline" id="model-directory-subheadline">{{.subheadline}}</p>{{end}}
    <div class="model-directory-grid" id="model-directory-container">
      {{if .entries}}{{range .entries}}
      <article class="model-card"><div class="model-card-content">
        <h3 class="model-card-title">{{.name}}{{if .owner}} <span class="model-card-owner">{{.owner}}</span>{{end}}</h3>
        {{if .summary}}<p class="model-card-summary">{{.summary}}</p>{{end}}
        {{if .claims}}<ul class="model-card-claims">
          {{range .claims}}<li><span class="claim-field">{{.field}}</span> <span class="claim-value">{{.value}}{{if .unit}} {{.unit}}{{end}}</span>{{if .url}} <a href="{{.url}}" target="_blank" rel="noopener noreferrer" class="claim-source">source</a>{{end}}</li>{{end}}
        </ul>{{end}}
        <div class="model-card-links">
          {{if .docs_url}}<a href="{{.docs_url}}" target="_blank" rel="noopener noreferrer">Docs</a>{{end}}
          {{if .weights_url}}<a href="{{.weights_url}}" target="_blank" rel="noopener noreferrer">Weights</a>{{end}}
          {{if .wrapper_url}}<a href="{{.wrapper_url}}">Try it</a>{{end}}
        </div>
      </div></article>
      {{end}}{{else}}<noscript>
        <p class="model-directory-empty">Enable JavaScript to see the model directory.</p>
      </noscript>{{end}}
    </div>
    <div id="model-directory-footer"></div>
  </div>
</section>
<script src="/tools/assets/model-directory.js"></script>$html$,
    $js$(function() {
  function el(tag, opts) {
    var e = document.createElement(tag);
    opts = opts || {};
    if (opts.className) e.className = opts.className;
    if (opts.text) e.textContent = opts.text;
    if (opts.href) { e.href = opts.href; e.target = "_blank"; e.rel = "noopener noreferrer"; }
    return e;
  }

  function renderCard(entry) {
    var card = el("article", {className: "model-card"});
    var content = el("div", {className: "model-card-content"});
    var title = el("h3", {className: "model-card-title", text: entry.name || ""});
    if (entry.owner) {
      title.appendChild(el("span", {className: "model-card-owner", text: " " + entry.owner}));
    }
    content.appendChild(title);
    if (entry.summary) {
      content.appendChild(el("p", {className: "model-card-summary", text: entry.summary}));
    }
    if (entry.claims && entry.claims.length > 0) {
      var list = document.createElement("ul");
      list.className = "model-card-claims";
      entry.claims.forEach(function(c) {
        var li = document.createElement("li");
        li.appendChild(el("span", {className: "claim-field", text: c.field || ""}));
        li.appendChild(document.createTextNode(" "));
        var valueText = c.value || "";
        if (c.unit) valueText += " " + c.unit;
        li.appendChild(el("span", {className: "claim-value", text: valueText}));
        if (c.url) {
          li.appendChild(document.createTextNode(" "));
          li.appendChild(el("a", {className: "claim-source", text: "source", href: c.url}));
        }
        list.appendChild(li);
      });
      content.appendChild(list);
    }
    var links = document.createElement("div");
    links.className = "model-card-links";
    if (entry.docs_url) links.appendChild(el("a", {text: "Docs", href: entry.docs_url}));
    if (entry.weights_url) links.appendChild(el("a", {text: "Weights", href: entry.weights_url}));
    if (entry.wrapper_url) links.appendChild(el("a", {text: "Try it", href: entry.wrapper_url}));
    content.appendChild(links);
    card.appendChild(content);
    return card;
  }

  fetch("/data/model-directory.json")
    .then(function(r) { return r.json(); })
    .then(function(data) {
      var headlineEl = document.getElementById("model-directory-headline");
      if (headlineEl && data.headline) headlineEl.textContent = data.headline;
      var sub = document.getElementById("model-directory-subheadline");
      if (sub && data.subheadline) sub.textContent = data.subheadline;
      var container = document.getElementById("model-directory-container");
      if (container && data.entries && data.entries.length > 0) {
        container.innerHTML = "";
        data.entries.forEach(function(entry) { container.appendChild(renderCard(entry)); });
      }
      var footer = document.getElementById("model-directory-footer");
      if (footer && data.directory_url) {
        footer.innerHTML = "";
        var wrap = document.createElement("div");
        wrap.className = "model-directory-section-footer";
        var link = el("a", {className: "model-directory-more-link", text: data.directory_label || "Browse the full directory →"});
        link.href = data.directory_url;
        wrap.appendChild(link);
        footer.appendChild(wrap);
      }
    })
    .catch(function() {});
})();$js$
WHERE NOT EXISTS (SELECT 1 FROM content_components WHERE function = 'model-directory');

INSERT INTO content_components (
    name, display_name, description, function, category, component_level,
    section_type, render_mode, suitable_site_types, suitable_page_types,
    created_from, input_schema, html_template, js_content
)
SELECT
    'AI Model Directory (full listing)', 'Model Directory — Full Listing', 'Dedicated model-directory page: every cited AI model entry, server-rendered from query.model_directory_full, refreshed client-side from data/model-directory-full.json',
    'model-directory-listing', 'content', 'section', 'model-directory-listing', 'template',
    '["brochure"]'::jsonb, '["model-directory"]'::jsonb, 'manual',
    $schema${
  "notes": "entries are server-rendered from query.model_directory_full; model-directory-listing.js refreshes client-side from data/model-directory-full.json. Same escaping discipline as the model-directory snippet component.",
  "fields": {
    "entries": {
      "type": "array",
      "items": {
        "slug": {"type": "text"}, "name": {"type": "text"}, "owner": {"type": "text"},
        "summary": {"type": "text"}, "claims": {"type": "array"},
        "docs_url": {"type": "url"}, "weights_url": {"type": "url"}, "wrapper_url": {"type": "url"}
      },
      "limit": 50,
      "source": "query.model_directory_full",
      "required": false,
      "on_missing": "skip_field"
    },
    "headline": {
      "type": "text", "source": "llm", "default": "AI Model Directory", "required": true,
      "description": "Page heading — generated by content writer"
    },
    "subheadline": {
      "type": "text", "source": "llm", "required": false,
      "description": "Optional subheading"
    }
  },
  "data_source": "/data/model-directory-full.json",
  "render_action": "render_model_directory",
  "refresh_interval": "6h"
}$schema$::jsonb,
    $html$<!-- model-directory-listing component -->
<section data-component="model-directory-listing" class="model-directory-listing-section section-padding">
  <div class="container">
    <h2 class="section-heading" id="model-directory-full-headline">{{.headline}}</h2>
    {{if .subheadline}}<p class="section-subheadline" id="model-directory-full-subheadline">{{.subheadline}}</p>{{end}}
    <div class="model-directory-grid model-directory-grid--full" id="model-directory-full-container">
      {{if .entries}}{{range .entries}}
      <article class="model-card"><div class="model-card-content">
        <h3 class="model-card-title">{{.name}}{{if .owner}} <span class="model-card-owner">{{.owner}}</span>{{end}}</h3>
        {{if .summary}}<p class="model-card-summary">{{.summary}}</p>{{end}}
        {{if .claims}}<ul class="model-card-claims">
          {{range .claims}}<li><span class="claim-field">{{.field}}</span> <span class="claim-value">{{.value}}{{if .unit}} {{.unit}}{{end}}</span>{{if .url}} <a href="{{.url}}" target="_blank" rel="noopener noreferrer" class="claim-source">source</a>{{end}}</li>{{end}}
        </ul>{{end}}
        <div class="model-card-links">
          {{if .docs_url}}<a href="{{.docs_url}}" target="_blank" rel="noopener noreferrer">Docs</a>{{end}}
          {{if .weights_url}}<a href="{{.weights_url}}" target="_blank" rel="noopener noreferrer">Weights</a>{{end}}
          {{if .wrapper_url}}<a href="{{.wrapper_url}}">Try it</a>{{end}}
        </div>
      </div></article>
      {{end}}{{else}}<noscript>
        <p class="model-directory-empty">Enable JavaScript to see the model directory.</p>
      </noscript>{{end}}
    </div>
  </div>
</section>
<script src="/tools/assets/model-directory-listing.js"></script>$html$,
    $js$(function() {
  function el(tag, opts) {
    var e = document.createElement(tag);
    opts = opts || {};
    if (opts.className) e.className = opts.className;
    if (opts.text) e.textContent = opts.text;
    if (opts.href) { e.href = opts.href; e.target = "_blank"; e.rel = "noopener noreferrer"; }
    return e;
  }

  function renderCard(entry) {
    var card = el("article", {className: "model-card"});
    var content = el("div", {className: "model-card-content"});
    var title = el("h3", {className: "model-card-title", text: entry.name || ""});
    if (entry.owner) {
      title.appendChild(el("span", {className: "model-card-owner", text: " " + entry.owner}));
    }
    content.appendChild(title);
    if (entry.summary) {
      content.appendChild(el("p", {className: "model-card-summary", text: entry.summary}));
    }
    if (entry.claims && entry.claims.length > 0) {
      var list = document.createElement("ul");
      list.className = "model-card-claims";
      entry.claims.forEach(function(c) {
        var li = document.createElement("li");
        li.appendChild(el("span", {className: "claim-field", text: c.field || ""}));
        li.appendChild(document.createTextNode(" "));
        var valueText = c.value || "";
        if (c.unit) valueText += " " + c.unit;
        li.appendChild(el("span", {className: "claim-value", text: valueText}));
        if (c.url) {
          li.appendChild(document.createTextNode(" "));
          li.appendChild(el("a", {className: "claim-source", text: "source", href: c.url}));
        }
        list.appendChild(li);
      });
      content.appendChild(list);
    }
    var links = document.createElement("div");
    links.className = "model-card-links";
    if (entry.docs_url) links.appendChild(el("a", {text: "Docs", href: entry.docs_url}));
    if (entry.weights_url) links.appendChild(el("a", {text: "Weights", href: entry.weights_url}));
    if (entry.wrapper_url) links.appendChild(el("a", {text: "Try it", href: entry.wrapper_url}));
    content.appendChild(links);
    card.appendChild(content);
    return card;
  }

  fetch("/data/model-directory-full.json")
    .then(function(r) { return r.json(); })
    .then(function(data) {
      var headlineEl = document.getElementById("model-directory-full-headline");
      if (headlineEl && data.headline) headlineEl.textContent = data.headline;
      var sub = document.getElementById("model-directory-full-subheadline");
      if (sub && data.subheadline) sub.textContent = data.subheadline;
      var container = document.getElementById("model-directory-full-container");
      if (container && data.entries && data.entries.length > 0) {
        container.innerHTML = "";
        data.entries.forEach(function(entry) { container.appendChild(renderCard(entry)); });
      }
    })
    .catch(function() {});
})();$js$
WHERE NOT EXISTS (SELECT 1 FROM content_components WHERE function = 'model-directory-listing');

COMMIT;

-- ── Post-apply verification ────────────────────────────────────────────────
-- 1. Both rows exist:
--    SELECT function, component_level, render_mode FROM content_components
--    WHERE function IN ('model-directory', 'model-directory-listing');
--    Expect component_level = 'section' on both.
-- 2. Not yet selectable by a site plan — that needs the build-site-planner /
--    site-architect prompt update (separate follow-up, see the SECURITY NOTE
--    above). Until then these rows are inert data, matching the brochure
--    component library's own "registering the row is not enough" lesson.
--
-- ── Rollback ────────────────────────────────────────────────────────────────
--    DELETE FROM content_components WHERE function IN ('model-directory', 'model-directory-listing');
-- Safe only if no page_components row references either yet (check first):
--    SELECT pc.id FROM page_components pc JOIN content_components cc ON cc.id = pc.component_id
--    WHERE cc.function IN ('model-directory', 'model-directory-listing');
