BEGIN;
CREATE TEMP TABLE _hero_items(item_key text, page_name text, summary text, spec text);
INSERT INTO _hero_items VALUES
  ('needs_imagery:page:services:content_hero_services', 'services', 'Hero image missing on services — page renders the colour-band branch with no image (owner request 2026-08-26)', '{"key": "content_hero_services", "kind": "hero", "check": "emit_imagery_items", "scope": "page", "scope_ref": "services", "purpose": "hero", "asset_key": "content_hero_services", "prompt": "A hero image for the services page of finetuning.uk. several parallel routes of differing weight running left to right and converging into one clean continuous line. Abstract geometric composition, calm and precise, in an off-white paper ground (#F5F3EF) with deep navy-black forms (#1A1A2E) and a single muted bronze accent (#C8873A). Flat shapes and clean linework, soft depth, generous empty space in the upper left for overlaid headline text. It should read like well-designed infrastructure. No people, no hands, no offices, no laptops, no screens. No robots, no brains, no circuit boards, no glowing nodes, no neon, no bright gradients. No photography. No words, letters or numbers anywhere in the image.", "style_hints": {"medium": "abstract geometric illustration", "aspect_ratio": "16:9"}, "brand_update": false}'),
  ('needs_imagery:page:about:content_hero_about', 'about', 'Hero image missing on about — page renders the colour-band branch with no image (owner request 2026-08-26)', '{"key": "content_hero_about", "kind": "hero", "check": "emit_imagery_items", "scope": "page", "scope_ref": "about", "purpose": "hero", "asset_key": "content_hero_about", "prompt": "A hero image for the about page of finetuning.uk. a small number of precisely interlocking geometric plates, slightly offset from one another, resting square and casting soft shadows. Abstract geometric composition, calm and precise, in an off-white paper ground (#F5F3EF) with deep navy-black forms (#1A1A2E) and a single muted bronze accent (#C8873A). Flat shapes and clean linework, soft depth, generous empty space in the upper left for overlaid headline text. It should read like well-designed infrastructure. No people, no hands, no offices, no laptops, no screens. No robots, no brains, no circuit boards, no glowing nodes, no neon, no bright gradients. No photography. No words, letters or numbers anywhere in the image.", "style_hints": {"medium": "abstract geometric illustration", "aspect_ratio": "16:9"}, "brand_update": false}'),
  ('needs_imagery:page:approach:content_hero_approach', 'approach', 'Hero image missing on approach — page renders the colour-band branch with no image (owner request 2026-08-26)', '{"key": "content_hero_approach", "kind": "hero", "check": "emit_imagery_items", "scope": "page", "scope_ref": "approach", "purpose": "hero", "asset_key": "content_hero_approach", "prompt": "A hero image for the approach page of finetuning.uk. a left-to-right progression in which a loose scatter of small forms resolves stage by stage into an ordered lattice. Abstract geometric composition, calm and precise, in an off-white paper ground (#F5F3EF) with deep navy-black forms (#1A1A2E) and a single muted bronze accent (#C8873A). Flat shapes and clean linework, soft depth, generous empty space in the upper left for overlaid headline text. It should read like well-designed infrastructure. No people, no hands, no offices, no laptops, no screens. No robots, no brains, no circuit boards, no glowing nodes, no neon, no bright gradients. No photography. No words, letters or numbers anywhere in the image.", "style_hints": {"medium": "abstract geometric illustration", "aspect_ratio": "16:9"}, "brand_update": false}'),
  ('needs_imagery:page:contact:content_hero_contact', 'contact', 'Hero image missing on contact — page renders the colour-band branch with no image (owner request 2026-08-26)', '{"key": "content_hero_contact", "kind": "hero", "check": "emit_imagery_items", "scope": "page", "scope_ref": "contact", "purpose": "hero", "asset_key": "content_hero_contact", "prompt": "A hero image for the contact page of finetuning.uk. a single wide aperture cut through a layered geometric wall, with light passing cleanly through the opening. Abstract geometric composition, calm and precise, in an off-white paper ground (#F5F3EF) with deep navy-black forms (#1A1A2E) and a single muted bronze accent (#C8873A). Flat shapes and clean linework, soft depth, generous empty space in the upper left for overlaid headline text. It should read like well-designed infrastructure. No people, no hands, no offices, no laptops, no screens. No robots, no brains, no circuit boards, no glowing nodes, no neon, no bright gradients. No photography. No words, letters or numbers anywhere in the image.", "style_hints": {"medium": "abstract geometric illustration", "aspect_ratio": "16:9"}, "brand_update": false}'),
  ('needs_imagery:page:case-studies:content_hero_case_studies', 'case-studies', 'Hero image missing on case-studies — page renders the colour-band branch with no image (owner request 2026-08-26)', '{"key": "content_hero_case_studies", "kind": "hero", "check": "emit_imagery_items", "scope": "page", "scope_ref": "case-studies", "purpose": "hero", "asset_key": "content_hero_case_studies", "prompt": "A hero image for the case studies page of finetuning.uk. a grid of rectangular panels held at slightly different depths, each one distinct, with a single panel set forward of the rest. Abstract geometric composition, calm and precise, in an off-white paper ground (#F5F3EF) with deep navy-black forms (#1A1A2E) and a single muted bronze accent (#C8873A). Flat shapes and clean linework, soft depth, generous empty space in the upper left for overlaid headline text. It should read like well-designed infrastructure. No people, no hands, no offices, no laptops, no screens. No robots, no brains, no circuit boards, no glowing nodes, no neon, no bright gradients. No photography. No words, letters or numbers anywhere in the image.", "style_hints": {"medium": "abstract geometric illustration", "aspect_ratio": "16:9"}, "brand_update": false}'),
  ('needs_imagery:page:use-cases:content_hero_use_cases', 'use-cases', 'Hero image missing on use-cases — page renders the colour-band branch with no image (owner request 2026-08-26)', '{"key": "content_hero_use_cases", "kind": "hero", "check": "emit_imagery_items", "scope": "page", "scope_ref": "use-cases", "purpose": "hero", "asset_key": "content_hero_use_cases", "prompt": "A hero image for the use cases page of finetuning.uk. one continuous line branching into several distinct paths of equal weight, each resolving into its own simple terminal form. Abstract geometric composition, calm and precise, in an off-white paper ground (#F5F3EF) with deep navy-black forms (#1A1A2E) and a single muted bronze accent (#C8873A). Flat shapes and clean linework, soft depth, generous empty space in the upper left for overlaid headline text. It should read like well-designed infrastructure. No people, no hands, no offices, no laptops, no screens. No robots, no brains, no circuit boards, no glowing nodes, no neon, no bright gradients. No photography. No words, letters or numbers anywhere in the image.", "style_hints": {"medium": "abstract geometric illustration", "aspect_ratio": "16:9"}, "brand_update": false}'),
  ('needs_imagery:page:careers:content_hero_careers', 'careers', 'Hero image missing on careers — page renders the colour-band branch with no image (owner request 2026-08-26)', '{"key": "content_hero_careers", "kind": "hero", "check": "emit_imagery_items", "scope": "page", "scope_ref": "careers", "purpose": "hero", "asset_key": "content_hero_careers", "prompt": "A hero image for the careers page of finetuning.uk. an open geometric lattice with generous empty space, regular and unhurried, with one node deliberately left unfilled. Abstract geometric composition, calm and precise, in an off-white paper ground (#F5F3EF) with deep navy-black forms (#1A1A2E) and a single muted bronze accent (#C8873A). Flat shapes and clean linework, soft depth, generous empty space in the upper left for overlaid headline text. It should read like well-designed infrastructure. No people, no hands, no offices, no laptops, no screens. No robots, no brains, no circuit boards, no glowing nodes, no neon, no bright gradients. No photography. No words, letters or numbers anywhere in the image.", "style_hints": {"medium": "abstract geometric illustration", "aspect_ratio": "16:9"}, "brand_update": false}'),
  ('needs_imagery:page:tool-ai-readiness-checker:content_hero_tool_ai_readiness_checker', 'tool-ai-readiness-checker', 'Hero image missing on tool-ai-readiness-checker — page renders the colour-band branch with no image (owner request 2026-08-26)', '{"key": "content_hero_tool_ai_readiness_checker", "kind": "hero", "check": "emit_imagery_items", "scope": "page", "scope_ref": "tool-ai-readiness-checker", "purpose": "hero", "asset_key": "content_hero_tool_ai_readiness_checker", "prompt": "A hero image for the tool ai readiness checker page of finetuning.uk. a calibrated arc with graduated tick marks and one slender indicator resting partway along it, an abstract instrument face. Abstract geometric composition, calm and precise, in an off-white paper ground (#F5F3EF) with deep navy-black forms (#1A1A2E) and a single muted bronze accent (#C8873A). Flat shapes and clean linework, soft depth, generous empty space in the upper left for overlaid headline text. It should read like well-designed infrastructure. No people, no hands, no offices, no laptops, no screens. No robots, no brains, no circuit boards, no glowing nodes, no neon, no bright gradients. No photography. No words, letters or numbers anywhere in the image.", "style_hints": {"medium": "abstract geometric illustration", "aspect_ratio": "16:9"}, "brand_update": false}'),
  ('needs_imagery:page:model-approach-selector:content_hero_model_approach_selector', 'model-approach-selector', 'Hero image missing on model-approach-selector — page renders the colour-band branch with no image (owner request 2026-08-26)', '{"key": "content_hero_model_approach_selector", "kind": "hero", "check": "emit_imagery_items", "scope": "page", "scope_ref": "model-approach-selector", "purpose": "hero", "asset_key": "content_hero_model_approach_selector", "prompt": "A hero image for the model approach selector page of finetuning.uk. a single line arriving at a fork and dividing into three diverging paths of equal weight, each taking a different angle. Abstract geometric composition, calm and precise, in an off-white paper ground (#F5F3EF) with deep navy-black forms (#1A1A2E) and a single muted bronze accent (#C8873A). Flat shapes and clean linework, soft depth, generous empty space in the upper left for overlaid headline text. It should read like well-designed infrastructure. No people, no hands, no offices, no laptops, no screens. No robots, no brains, no circuit boards, no glowing nodes, no neon, no bright gradients. No photography. No words, letters or numbers anywhere in the image.", "style_hints": {"medium": "abstract geometric illustration", "aspect_ratio": "16:9"}, "brand_update": false}');

INSERT INTO site_work_items (site_id, page_id, source, pipeline, item_type, severity, summary,
                             priority, handler_agent, status, created_by, spec, item_key, batch_id)
SELECT s.id, p.id, 'discovery', 'build', 'needs_imagery', 'medium', h.summary,
       90, 'image-build-handler', 'triaged', 'finetuning_uk_service_lane', h.spec::jsonb, h.item_key, gen_random_uuid()
  FROM _hero_items h
  JOIN sites s ON s.domain='finetuning.uk'
  JOIN pages p ON p.site_id=s.id AND p.name=h.page_name
 WHERE NOT EXISTS (SELECT 1 FROM site_work_items w
                    WHERE w.site_id=s.id AND w.item_key=h.item_key
                      AND w.status NOT IN ('complete','verified','rejected','wont_fix','failed','unresolved','cancelled'))
ON CONFLICT DO NOTHING;

DO $$
DECLARE n int; n_pages int; n_orphan int;
BEGIN
  SELECT count(*) INTO n FROM site_work_items WHERE created_by='finetuning_uk_service_lane' AND item_type='needs_imagery';
  IF n <> 9 THEN RAISE EXCEPTION 'filed % needs_imagery items, want 9', n; END IF;
  -- every item must resolve to a real page, or the wiring step cannot find it (bugs_open/214 orphans)
  SELECT count(*) INTO n_orphan FROM site_work_items w
   WHERE w.created_by='finetuning_uk_service_lane' AND w.item_type='needs_imagery' AND w.page_id IS NULL;
  IF n_orphan <> 0 THEN RAISE EXCEPTION '% item(s) have no page_id — flag_page_image_rebuild could not wire them', n_orphan; END IF;
  SELECT count(DISTINCT w.spec->>'scope_ref') INTO n_pages FROM site_work_items w
   WHERE w.created_by='finetuning_uk_service_lane' AND w.item_type='needs_imagery';
  IF n_pages <> 9 THEN RAISE EXCEPTION 'only % distinct scope_refs — pages would share an image', n_pages; END IF;
  RAISE NOTICE 'OK: 9 needs_imagery items, 9 distinct pages, every one page-resolved';
END $$;
COMMIT;
