# FILE: k8s/web-search-adapter.yaml (Updated)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-search-adapter
  namespace: ai-persona-system
  labels:
    app: web-search-adapter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-search-adapter
  template:
    metadata:
      labels:
        app: web-search-adapter
    spec:
      initContainers:
        # Wait for Kafka and topics
        - name: wait-for-kafka-topics
          image: confluentinc/cp-kafka:7.5.0
          command:
            - sh
            - -c
            - |
              echo "Waiting for Kafka and required topics..."
              until kafka-topics --bootstrap-server kafka-0.kafka-headless:9092 --list >/dev/null 2>&1; do
                echo "Kafka not ready, waiting..."
                sleep 5
              done
              
              required_topics="system.adapter.web.search system.responses.websearch"
              for topic in $required_topics; do
                echo "Checking for topic: $topic"
                max_attempts=20
                attempt=1
                while [ $attempt -le $max_attempts ]; do
                  if kafka-topics --bootstrap-server kafka-0.kafka-headless:9092 --list | grep -q "^$topic$"; then
                    echo "Topic $topic exists!"
                    break
                  fi
                  if [ $attempt -eq $max_attempts ]; then
                    echo "Topic $topic not found after $max_attempts attempts"
                    exit 1
                  fi
                  echo "Attempt $attempt/$max_attempts - topic $topic not found..."
                  sleep 5
                  ((attempt++))
                done
              done
              echo "All required topics exist!"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

      containers:
        - name: web-search-adapter
          image: ai-persona-system/web-search-adapter:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICE_NAME
              value: "web-search-adapter"
            - name: SERVICE_VERSION
              value: "1.0.0"
            - name: SERVICE_ENVIRONMENT
              value: "production"
            - name: LOGGING_LEVEL
              value: "info"
            - name: SERP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-secrets
                  key: serp-api-key
          envFrom:
            - configMapRef:
                name: common-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          # Security context
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL