apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-search-adapter
  labels:
    app: web-search-adapter
spec:
  selector:
    matchLabels:
      app: web-search-adapter
  template:
    metadata:
      labels:
        app: web-search-adapter
    spec:
      containers:
        - name: web-search-adapter
          image: your-container-registry/web-search-adapter:latest # Patched by overlays
          envFrom:
            - configMapRef:
                name: placeholder-config # Patched by overlays
            - secretRef:
                name: placeholder-secrets # Patched by overlays
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"