#!/usr/bin/env python3
"""Build the install SQL for the gauntlet round-record page.

WHY A SCRIPT AND NOT A HAND-WRITTEN .sql WITH `\\set tmpl `cat ...``:
that form fails SILENTLY through `kubectl exec`. The backticks execute inside
the POD, which has no repo, so `cat` prints to stderr, the variable resolves to
EMPTY, and the INSERT still COMMITS — a component created with html_template=''
and every statement reporting success. `\\set ON_ERROR_STOP on` does not catch
it, because a failing shell command is not a psql error. (275's header records
the day that happened.) So the template is embedded here, locally, in a
dollar-quoted literal, and the length is asserted on both sides.

Writes the finished SQL to stdout or to the path given as argv[1].
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
TMPL = HERE / "round_record_component.html"
TAG = "grrec"  # dollar-quote tag

html = TMPL.read_text()

# The one thing that would corrupt the transaction. Assert, do not hope.
assert ("$" + TAG + "$") not in html, "dollar-quote tag collides with the template"
assert "{{" not in html, "template placeholders present — see the component header"
assert len(html) > 8000, "template is implausibly short: " + str(len(html))

SITE = "9ec3b9ee-5b08-461b-b4f8-9e1e03579c74"
FN = "gauntlet-round-record"
NAME = "gauntlet-round-record-vonc-com"
URL = "/tools/gauntlet/round.html"

sql = """-- ============================================================================
-- 279 — vonc.com: the public record page for one published Gauntlet round
--
-- Serves {URL}?r=<slug>. Companion to the island endpoints shipped in
-- v1.0.1216 (PUB-004): POST /publish issues the slug, GET /round/:slug serves
-- the round, and this page is what the slug's address resolves to.
--
-- GENERATED by round_record/build_record_page_sql.py — do not hand-edit; edit
-- round_record/round_record_component.html and regenerate, so the repo copy and
-- the database copy cannot drift.
--
-- FOUR PROPERTIES THIS FILE DEPENDS ON
--   1. ZERO template variables. That is what makes writing the SAME bytes to
--      content_components.html_template AND page_components.rendered_html
--      correct. With vars > 0 it would blank the page's copy (RUNBOOK §11, the
--      2026-07-28 incident that served a raw placeholder to the owner).
--   2. slot_name = the component FUNCTION, and the same string must appear in
--      pages.sections. 'main' is wrong and fails silently (bugs_open/095).
--   3. rebuild_policy='owned' so the generic page builder never rewrites it
--      (save_page_sections_action.go hard-refuses).
--   4. in_header/in_footer FALSE. This is a permalink target, not a
--      destination: it is reached from a shared card, never from the nav.
--      vonc has no tools index and nothing enumerates page_type='tool', so
--      nothing else will surface it (checked 2026-07-31).
--
-- REPLAY-SAFE, precisely: the three STRUCTURAL inserts (component, page, binding)
-- each carry WHERE NOT EXISTS, so re-running this file cannot raise the raw 23505
-- that reads as broken SQL and blocked the migration runner for three days
-- (bugs_open/007 Class C) — `--apply` takes EVERY pending file. The doc_plans
-- insert is the deliberate exception, noted at the statement itself. The DO block
-- below asserts the END STATE either way, which is the claim that matters: it
-- passes whether this run created the rows or found them already there.
--
-- js_content stays NULL and the JS is inline in html_template. The js_content
-- lane publishes /tools/assets/<function>.js but injects no <script> tag, which
-- is the published-but-inert class (bugs_open/041); gauntlet-interface only
-- works because its template carries the tag by hand.
-- ============================================================================

\\set ON_ERROR_STOP on

BEGIN;

-- 1. the component -----------------------------------------------------------
INSERT INTO content_components (
  name, function, display_name, description, category,
  component_level, render_mode, html_template, js_content,
  input_schema, is_active, suitable_page_types, template_variable_count,
  created_from
)
SELECT
  '{NAME}',
  '{FN}',
  'The Gauntlet: public record of one round',
  'Renders a single PUBLISHED Gauntlet round from ?r=<slug>, fetched client-side from the island API. Every field is written with textContent and the file contains no markup-assigning DOM property, because two of the fields are prose typed by a member of the public and then served to every other visitor. Shows the provocation headline and body only — the provocation also carries stats, primary_cta and secondary_cta, and stats would put numbers on the page that the page did not compute.',
  'tool',
  'section',
  'template',
  ${TAG}${HTML}${TAG}$,
  NULL,
  NULL,
  true,
  '["tool"]'::jsonb,
  0,
  'manual'
WHERE NOT EXISTS (
  SELECT 1 FROM content_components WHERE function = '{FN}'
);

-- 2. the page ----------------------------------------------------------------
INSERT INTO pages (
  site_id, name, url, title, page_type, status, build_status,
  nav_label, nav_order, in_header, in_footer, rebuild_policy, meta_description
)
SELECT
  '{SITE}',
  '{FN}',
  '{URL}',
  'A round of The Gauntlet | Vonc',
  'tool',
  'active',
  'pending',
  'Round record',
  99,
  false,
  false,
  'owned',
  'One published round of The Gauntlet: the provocation, the position argued against it, the challenge that came back, the defence, and the ruling.'
WHERE NOT EXISTS (
  SELECT 1 FROM pages WHERE site_id = '{SITE}' AND name = '{FN}'
);

-- 3. bind component to page --------------------------------------------------
UPDATE pages SET sections = '["{FN}"]'::jsonb
 WHERE site_id = '{SITE}' AND name = '{FN}';

-- rendered_html gets the SAME bytes as html_template, which is only safe
-- because the template has no variables (property 1 above). rerender assembles
-- the page from THIS column, not from content_components.
INSERT INTO page_components (page_id, component_id, position, slot_name, rendered_html, content_data, build_status)
SELECT p.id, c.id, 1, '{FN}', c.html_template, '{{}}'::jsonb, 'pending'
FROM pages p
CROSS JOIN content_components c
WHERE p.site_id = '{SITE}'
  AND p.name = '{FN}'
  AND c.function = '{FN}'
  AND c.name = '{NAME}'
  AND NOT EXISTS (
    SELECT 1 FROM page_components pc2 WHERE pc2.page_id = p.id AND pc2.slot_name = '{FN}'
  );

-- 4. travelling PLAN with acceptance criteria --------------------------------
UPDATE doc_plans SET is_current = false, superseded_at = now()
WHERE subject_type = 'tool' AND subject_key = '{FN}' AND is_current;

-- doc_plans is DELIBERATELY not guarded: supersede-then-insert is how a plan is
-- versioned here (275's convention), so a replay correctly records a new current
-- plan rather than silently keeping a stale one. It is the one statement in this
-- file that is not a no-op on replay, and that is the intended behaviour.
INSERT INTO doc_plans (subject_type, subject_key, body, source, created_by, is_current, pinned)
VALUES (
  'tool', '{FN}',
  $plan$# PLAN — The Gauntlet: public record of one round (vonc.com)

## What it is for
A visitor who finishes a round can share a card of it. The card is an image, so
the argument on it cannot be read by a machine, quoted, or followed. This page is
what the card points at: the whole round, as text, at a stable address.

## Where the address comes from
`POST /api/v1/tools/gauntlet/publish` on the island issues a 10-character slug
for a round that HAS a verdict, and is idempotent — pressing share twice returns
the same slug. `GET /api/v1/tools/gauntlet/round/<slug>` serves it. This page
reads `?r=<slug>` and calls that endpoint. Nothing else writes the address.

## What it will and will not show
Shows: provocation headline and body, the position filed, Vonc's counter and
challenge, the defence, the ruling and its reasons, and the two dates.

Does NOT show: `provocation.stats` (an array of numbers), `primary_cta` or
`secondary_cta` — arena furniture. A number on this page that the page did not
compute is exactly what the honesty rail forbids. No aggregate of any kind: no
count of published rounds, no "most argued", no leaderboard. There are no
participants to aggregate yet, and a communal view before there is a community
would be a claim about the world rather than a report of it.

Nobody is named. There are no accounts, the rounds table stores no name, and the
page says so in its own words rather than in the site footer.

## Safety
Two of the fields — position and defence — are prose typed by a member of the
public and then served to every other visitor. Every field on the page is
written with `textContent`, with no exception and no allowlist, and the file
contains no `innerHTML`, `outerHTML`, `insertAdjacentHTML` or `document.write`.
That is asserted mechanically by `round_record/verify_round_record.py`, which
also cross-checks the slug alphabet and length against the Go constants in
`internal/tools-api/store/rounds.go` so the two cannot drift apart.

## The four states
Every non-success outcome renders in one box, and it starts as "fetching"
rather than as an error, because an error before the response has arrived would
be a claim we have not earned.

| state | what the visitor is told |
|---|---|
| no `?r=` | the page needs a round's address; the link may have been cut short |
| malformed slug | the address is not the right shape, so nothing was looked up |
| 404 | no public record at that address — never published, or taken down |
| network / 429 | we could not fetch it; the round may well exist |

404 is returned identically for "never published" and "does not exist", by
design in the handler, so the page cannot tell them apart and does not pretend
to.

## Delivery
Inline — all CSS and JS ship inside html_template, render_mode='template',
js_content NULL. Zero template variables, which is what makes html_template and
page_components.rendered_html byte-identical and the delivery safe.

## Acceptance criteria

```criteria
{{ "profiles": ["desktop","mobile"],
  "container": ".gauntlet-record-section",
  "checks": [
    {{"id":"boots","type":"selector_exists","selector":".gauntlet-record-section"}},
    {{"id":"state-box-exists","type":"selector_exists","selector":"[data-gr-state]"}},
    {{"id":"round-article-exists","type":"selector_exists","selector":"[data-gr-round]"}},
    {{"id":"console","type":"no_console_errors"}},
    {{"id":"status","type":"page_status_ok"}},
    {{"id":"mobile-fit","type":"no_horizontal_overflow","profiles":["mobile"]}}
  ]
}}
```

An acceptance run fetches the bare URL with no query string, so what it sees is
the no-slug state — and that IS the honest thing to assert here. The checks
therefore prove the page boots, renders its state box, carries the round
scaffold, and logs nothing; they deliberately do NOT assert a rendered round,
because a run with no slug that showed one would mean the page was inventing it.

Deliberately NO `asset_loads` check: that criterion asserts a JS-extraction path
that was designed and never built, and failed every tool on its first sweep
(TL-016). This component has no external asset by design.

Selectors are copied from the shipped template, not invented.
$plan$,
  'manual', 'gauntlet-record-2026-07-31', true, true
);

-- 5. assert the end state ----------------------------------------------------
-- A migration that skipped for the wrong reason is indistinguishable from one
-- that worked, so this refuses to commit unless every join actually resolves.
DO $assert$
DECLARE
  v_tmpl_len   int;
  v_rendered   int;
  v_vars       int;
  v_sections   jsonb;
  v_slot       text;
  v_policy     text;
  v_nav        boolean;
BEGIN
  SELECT length(html_template) INTO v_tmpl_len
    FROM content_components WHERE function = '{FN}';
  IF v_tmpl_len IS NULL OR v_tmpl_len <> {HTMLLEN} THEN
    RAISE EXCEPTION 'html_template is % chars, expected {HTMLLEN}', COALESCE(v_tmpl_len, -1);
  END IF;

  SELECT length(pc.rendered_html), p.sections, pc.slot_name, p.rebuild_policy,
         (p.in_header OR p.in_footer)
    INTO v_rendered, v_sections, v_slot, v_policy, v_nav
    FROM page_components pc
    JOIN pages p ON p.id = pc.page_id
   WHERE p.site_id = '{SITE}' AND p.name = '{FN}';

  IF v_rendered IS NULL THEN
    RAISE EXCEPTION 'no page_components row — the CROSS JOIN matched nothing';
  END IF;
  IF v_rendered <> v_tmpl_len THEN
    RAISE EXCEPTION 'rendered_html is % chars but html_template is %', v_rendered, v_tmpl_len;
  END IF;
  IF v_slot <> '{FN}' THEN
    RAISE EXCEPTION 'slot_name is %, must equal the component function', v_slot;
  END IF;
  IF NOT (v_sections ? '{FN}') THEN
    RAISE EXCEPTION 'pages.sections does not contain the slot: %', v_sections;
  END IF;
  IF v_policy <> 'owned' THEN
    RAISE EXCEPTION 'rebuild_policy is %, must be owned', v_policy;
  END IF;
  IF v_nav THEN
    RAISE EXCEPTION 'page is in the nav; it is a permalink target, not a destination';
  END IF;

  SELECT count(*) INTO v_vars
    FROM regexp_matches((SELECT html_template FROM content_components WHERE function='{FN}'),
                        '\\{{\\{{', 'g');
  IF v_vars <> 0 THEN
    RAISE EXCEPTION 'template has % brace pairs — the copy-both-columns path is unsafe', v_vars;
  END IF;

  RAISE NOTICE 'OK: component % chars, rendered_html identical, slot %, owned, out of nav',
               v_tmpl_len, v_slot;
END
$assert$;

COMMIT;

-- ---------------------------------------------------------------------------
-- AFTER APPLY
--   1. rerender + deploy (assemble-only; safe on an `owned` page):
--        docs/agent_docs/docs024_key_docs_latest/gauntlet_dead_cta/scripts/rerender_page_vonc.sh <page_id>
--   2. verify the SERVED page, not the row:
--        round_record/verify_round_record.py --url https://vonc.com{URL}
-- ---------------------------------------------------------------------------
""".replace("{TAG}", TAG) \
   .replace("{HTMLLEN}", str(len(html))) \
   .replace("{SITE}", SITE) \
   .replace("{NAME}", NAME) \
   .replace("{URL}", URL) \
   .replace("{FN}", FN) \
   .replace("{HTML}", html) \
   .replace("{{", "{").replace("}}", "}")

out = Path(sys.argv[1]) if len(sys.argv) > 1 else None
if out:
    out.write_text(sql)
    print("wrote " + str(out) + "  (" + str(len(sql)) + " bytes, template " + str(len(html)) + ")")
else:
    sys.stdout.write(sql)
