apiVersion: v1
kind: Service
metadata:
  name: core-manager
  labels:
    app: core-manager
spec:
  ports:
    - port: 8088
      targetPort: http
      name: http
    - port: 9091
      targetPort: grpc
      name: grpc
  selector:
    app: core-manager
  type: ClusterIP