-- ============================================================================
-- 279 — vonc.com: the public record page for one published Gauntlet round
--
-- Serves /tools/gauntlet/round.html?r=<slug>. Companion to the island endpoints shipped in
-- v1.0.1216 (PUB-004): POST /publish issues the slug, GET /round/:slug serves
-- the round, and this page is what the slug's address resolves to.
--
-- GENERATED by round_record/build_record_page_sql.py — do not hand-edit; edit
-- round_record/round_record_component.html and regenerate, so the repo copy and
-- the database copy cannot drift.
--
-- FOUR PROPERTIES THIS FILE DEPENDS ON
--   1. ZERO template variables. That is what makes writing the SAME bytes to
--      content_components.html_template AND page_components.rendered_html
--      correct. With vars > 0 it would blank the page's copy (RUNBOOK §11, the
--      2026-07-28 incident that served a raw placeholder to the owner).
--   2. slot_name = the component FUNCTION, and the same string must appear in
--      pages.sections. 'main' is wrong and fails silently (bugs_open/095).
--   3. rebuild_policy='owned' so the generic page builder never rewrites it
--      (save_page_sections_action.go hard-refuses).
--   4. in_header/in_footer FALSE. This is a permalink target, not a
--      destination: it is reached from a shared card, never from the nav.
--      vonc has no tools index and nothing enumerates page_type='tool', so
--      nothing else will surface it (checked 2026-07-31).
--
-- REPLAY-SAFE, precisely: the three STRUCTURAL inserts (component, page, binding)
-- each carry WHERE NOT EXISTS, so re-running this file cannot raise the raw 23505
-- that reads as broken SQL and blocked the migration runner for three days
-- (bugs_open/007 Class C) — `--apply` takes EVERY pending file. The doc_plans
-- insert is the deliberate exception, noted at the statement itself. The DO block
-- below asserts the END STATE either way, which is the claim that matters: it
-- passes whether this run created the rows or found them already there.
--
-- js_content stays NULL and the JS is inline in html_template. The js_content
-- lane publishes /tools/assets/<function>.js but injects no <script> tag, which
-- is the published-but-inert class (bugs_open/041); gauntlet-interface only
-- works because its template carries the tag by hand.
-- ============================================================================

\set ON_ERROR_STOP on

BEGIN;

-- 1. the component -----------------------------------------------------------
INSERT INTO content_components (
  name, function, display_name, description, category,
  component_level, render_mode, html_template, js_content,
  input_schema, is_active, suitable_page_types, template_variable_count,
  created_from
)
SELECT
  'gauntlet-round-record-vonc-com',
  'gauntlet-round-record',
  'The Gauntlet: public record of one round',
  'Renders a single PUBLISHED Gauntlet round from ?r=<slug>, fetched client-side from the island API. Every field is written with textContent and the file contains no markup-assigning DOM property, because two of the fields are prose typed by a member of the public and then served to every other visitor. Shows the provocation headline and body only — the provocation also carries stats, primary_cta and secondary_cta, and stats would put numbers on the page that the page did not compute.',
  'tool',
  'section',
  'template',
  $grrec$<style>
  /* ── The Gauntlet: public record of one round ────────────────────────────
     Serves /tools/gauntlet/round.html?r=<slug>. One published round, fetched
     client-side from the island API and rendered from that response alone.

     DELIBERATELY ZERO template variables and js_content NULL. Two reasons:
       1. With vars = 0, html_template and page_components.rendered_html are
          byte-identical, so RUNBOOK §10's copy-both-columns path is safe and
          §11's substitution trap cannot bite (27 vars on gauntlet-interface
          shipped a live page showing a raw unsubstituted placeholder to the
          owner on 2026-07-28).

       2. Inline <script> means no /tools/assets/*.js publication step, so
          there is no published-but-inert failure mode (bugs_open/041).

     The placeholder syntax is not written anywhere in this file, not even
     inside a comment. A comment does not protect it: the template parser reads
     the whole string, and a malformed action in a comment fails the parse and
     silently drops the renderer back to a regex engine (LANDMINES.md, footprint
     component_library.go RenderTemplateReportingMissing).

     PALETTE, MEASURED IN THE BROWSER (2026-07-31), not read off CSS source:
       --color-primary       #6d28d9   (purple — the same value the share card
                                        draws, so card and page match already)
       --color-primary-text  #ffffff
       --color-accent        #fc5c7d   (pink)

     > CORRECTED 2026-07-31: an earlier draft of this header claimed the site
     > was red #dc2626 with an amber #fbbf24 accent, and called the card's
     > purple an off-brand mismatch. That was wrong in both halves. Those two
     > literals are the FALLBACKS in `var(--color-primary, #dc2626)` inside the
     > gauntlet component's CSS — the value that actually resolves is the
     > purple above. Caught by computing the values on the live page; reading
     > the stylesheet could never have caught it, because the fallback only
     > applies when the variable is unset, and it is set.

     EVERY text colour below is stated explicitly. Nothing inherits. The first
     render of this page put the visitor's own argument at rgb(139,133,176) on
     the purple — 2.06:1, well under the 4.5:1 floor — because `.gr-text` set
     no colour and picked one up from the site chrome's paragraph rule. The
     text a stranger typed is the whole point of the page, so it is the last
     thing that may be left to inherit. drive_round_record.py measures the
     contrast in the browser and fails under 4.5:1.
     ──────────────────────────────────────────────────────────────────────── */
  .gauntlet-record-section {
    --gr-text: #ffffff;
    --gr-muted: rgba(255, 255, 255, 0.86);
    --gr-surface: rgba(255, 255, 255, 0.06);
    --gr-border: rgba(255, 255, 255, 0.22);
    --gr-accent: var(--color-accent, #fc5c7d);
    /* The site accent (#fc5c7d) on the site primary (#6d28d9) measures 2.36:1
       — it is a BUTTON colour and fails as small text. This pale tint of the
       same hue measures 4.9:1, so the labels stay in the accent family and
       stay readable. --gr-accent keeps its job as the CTA fill, where dark
       text on it measures 5.8:1. */
    --gr-accent-text: #ffc9d6;
    background: var(--color-primary, #6d28d9);
    color: var(--gr-text);
    padding: 3rem 1rem 4rem;
  }

  .gauntlet-record-section .gr-wrap {
    max-width: 720px;
    margin: 0 auto;
  }

  .gauntlet-record-section .gr-eyebrow {
    font: 700 0.78rem/1.4 system-ui, sans-serif;
    letter-spacing: 0.14em;
    text-transform: uppercase;
    color: var(--gr-accent-text);
    margin: 0 0 0.75rem;
  }

  .gauntlet-record-section .gr-dates {
    font: 400 0.85rem/1.5 system-ui, sans-serif;
    color: var(--gr-muted);
    margin: 0 0 2rem;
  }

  .gauntlet-record-section .gr-headline {
    font: 800 clamp(1.6rem, 4.5vw, 2.35rem)/1.2 Georgia, serif;
    margin: 0 0 1rem;
    color: var(--gr-text);
  }

  .gauntlet-record-section .gr-body {
    font: 400 1.02rem/1.65 Georgia, serif;
    color: var(--gr-muted);
    margin: 0 0 2.5rem;
    white-space: pre-wrap;
  }

  .gauntlet-record-section .gr-move {
    border-left: 3px solid var(--gr-border);
    padding: 0 0 0 1.15rem;
    margin: 0 0 2.1rem;
  }

  .gauntlet-record-section .gr-move.is-mine {
    border-left-color: var(--gr-accent);
  }

  .gauntlet-record-section .gr-label {
    font: 700 0.74rem/1.4 system-ui, sans-serif;
    letter-spacing: 0.13em;
    text-transform: uppercase;
    color: var(--gr-accent-text);
    margin: 0 0 0.5rem;
  }

  .gauntlet-record-section .gr-move.is-theirs .gr-label {
    color: var(--gr-muted);
  }

  /* The visitor's own prose and Vonc's replies. Explicit white, because this
     is the argument the page exists to show. */
  .gauntlet-record-section .gr-text {
    font: 400 1.02rem/1.62 Georgia, serif;
    color: var(--gr-text);
    margin: 0;
    white-space: pre-wrap;
    overflow-wrap: anywhere;
  }

  .gauntlet-record-section .gr-ruling {
    background: var(--gr-surface);
    border: 1px solid var(--gr-border);
    border-radius: 10px;
    padding: 1.4rem 1.5rem;
    margin: 2.6rem 0 0;
  }

  .gauntlet-record-section .gr-ruling-line {
    font: 800 clamp(1.15rem, 3.2vw, 1.5rem)/1.3 system-ui, sans-serif;
    color: var(--gr-text);
    margin: 0 0 0.7rem;
  }

  .gauntlet-record-section .gr-ruling-why {
    font: 400 0.98rem/1.6 Georgia, serif;
    color: var(--gr-muted);
    margin: 0;
    white-space: pre-wrap;
  }

  .gauntlet-record-section .gr-foot {
    margin: 3rem 0 0;
    padding: 1.6rem 0 0;
    border-top: 1px solid var(--gr-border);
  }

  .gauntlet-record-section .gr-foot p {
    font: 400 0.9rem/1.6 system-ui, sans-serif;
    color: var(--gr-muted);
    margin: 0 0 1.2rem;
  }

  .gauntlet-record-section .gr-cta {
    display: inline-block;
    background: var(--gr-accent);
    color: #1a1a1a;
    font: 700 1rem/1 system-ui, sans-serif;
    text-decoration: none;
    padding: 0.9rem 1.5rem;
    border-radius: 8px;
  }

  .gauntlet-record-section .gr-cta:hover,
  .gauntlet-record-section .gr-cta:focus {
    filter: brightness(1.08);
  }

  .gauntlet-record-section .gr-state {
    background: var(--gr-surface);
    border: 1px solid var(--gr-border);
    border-radius: 10px;
    padding: 1.8rem 1.6rem;
  }

  .gauntlet-record-section .gr-state h2 {
    font: 800 1.35rem/1.3 system-ui, sans-serif;
    color: var(--gr-text);
    margin: 0 0 0.7rem;
  }

  .gauntlet-record-section .gr-state p {
    font: 400 1rem/1.6 Georgia, serif;
    color: var(--gr-muted);
    margin: 0 0 1.3rem;
  }

  .gauntlet-record-section [hidden] {
    display: none !important;
  }
</style>

<section class="gauntlet-record-section" aria-label="A published Gauntlet round">
  <div class="gr-wrap">

    <p class="gr-eyebrow">The Gauntlet &middot; public record</p>

    <!-- The state box carries every non-success outcome and is the ONLY thing
         rendered until a real response arrives. It starts as "loading" rather
         than as an error, because an error before the fetch has returned would
         be a claim we have not earned. -->
    <div class="gr-state" data-gr-state>
      <h2 data-gr-state-head>Fetching this round&hellip;</h2>
      <p data-gr-state-body>One moment.</p>
      <a class="gr-cta" href="/tools/gauntlet/index.html" hidden data-gr-state-cta>Argue your own round</a>
    </div>

    <article hidden data-gr-round>
      <p class="gr-dates" data-gr-dates></p>
      <h1 class="gr-headline" data-gr-headline></h1>
      <p class="gr-body" data-gr-provocation></p>

      <div class="gr-move is-mine">
        <p class="gr-label">The position filed</p>
        <p class="gr-text" data-gr-position></p>
      </div>

      <div class="gr-move is-theirs">
        <p class="gr-label">Vonc answered</p>
        <p class="gr-text" data-gr-counter></p>
      </div>

      <div class="gr-move is-theirs">
        <p class="gr-label">And challenged</p>
        <p class="gr-text" data-gr-challenge></p>
      </div>

      <div class="gr-move is-mine">
        <p class="gr-label">The defence</p>
        <p class="gr-text" data-gr-defence></p>
      </div>

      <div class="gr-ruling">
        <p class="gr-ruling-line" data-gr-verdict></p>
        <p class="gr-ruling-why" data-gr-reasons></p>
      </div>

      <div class="gr-foot">
        <p>
          This is one round of The Gauntlet, published by the person who argued
          it when they shared their card. Nobody is named and no account exists:
          the record keeps the argument, not the arguer.
        </p>
        <a class="gr-cta" href="/tools/gauntlet/index.html">Argue your own round</a>
      </div>
    </article>

  </div>
</section>

<script>
  (function () {
    "use strict";

    var API = "https://tools.apis.uk";

    // Mirrors store.ValidSlug / SlugAlphabet / SlugLength in the island engine
    // (internal/tools-api/store/rounds.go). Kept here so a malformed address
    // never becomes a request, and so the page's own "no such record" copy is
    // reached without a round trip. The server still validates: this is a
    // courtesy, not the boundary.
    var SLUG_ALPHABET = "abcdefghjkmnpqrstuvwxyz23456789_";
    var SLUG_LENGTH = 10;

    function validSlug(s) {
      if (typeof s !== "string" || s.length !== SLUG_LENGTH) return false;
      for (var i = 0; i < s.length; i++) {
        if (SLUG_ALPHABET.indexOf(s.charAt(i)) === -1) return false;
      }
      return true;
    }

    var section = document.querySelector(".gauntlet-record-section");
    if (!section) return;

    var el = {
      state: section.querySelector("[data-gr-state]"),
      stateHead: section.querySelector("[data-gr-state-head]"),
      stateBody: section.querySelector("[data-gr-state-body]"),
      stateCta: section.querySelector("[data-gr-state-cta]"),
      round: section.querySelector("[data-gr-round]"),
      dates: section.querySelector("[data-gr-dates]"),
      headline: section.querySelector("[data-gr-headline]"),
      provocation: section.querySelector("[data-gr-provocation]"),
      position: section.querySelector("[data-gr-position]"),
      counter: section.querySelector("[data-gr-counter]"),
      challenge: section.querySelector("[data-gr-challenge]"),
      defence: section.querySelector("[data-gr-defence]"),
      verdict: section.querySelector("[data-gr-verdict]"),
      reasons: section.querySelector("[data-gr-reasons]")
    };

    // EVERY field on this page is written with textContent, with no exception
    // and no allowlist. Two of them (position, defence) are prose typed by a
    // member of the public and then served to every other visitor, so the page
    // has exactly one rule about untrusted text, and the rule is auditable by
    // grep: the markup-assigning DOM properties must not appear in this file at
    // all. verify_round_record.py asserts a count of zero for each of them.
    function put(node, value) {
      if (node) node.textContent = value == null ? "" : String(value);
    }

    // The provocation's headline carries inline markup (<em>) because it is
    // rendered as HTML on the arena page. Here it is stripped rather than
    // allowed, so the record and the share card show the same string — the
    // card does the same thing (buildVerdictCard in gauntlet-interface.js).
    function plain(value) {
      return value == null ? "" : String(value).replace(/<[^>]*>/g, "").trim();
    }

    function showState(head, body, offerCta) {
      put(el.stateHead, head);
      put(el.stateBody, body);
      if (el.stateCta) el.stateCta.hidden = !offerCta;
      if (el.state) el.state.hidden = false;
      if (el.round) el.round.hidden = true;
    }

    function fmtDate(iso) {
      if (!iso) return "";
      var d = new Date(iso);
      if (isNaN(d.getTime())) return "";
      return d.toLocaleDateString("en-GB", {
        day: "numeric", month: "long", year: "numeric"
      });
    }

    function render(r) {
      var prov = r.provocation || {};
      var counter = r.counter || {};
      var verdict = r.verdict || {};

      // Only headline and body are taken from the provocation. It also carries
      // `stats` (an array), `primary_cta` and `secondary_cta` — marketing
      // furniture for the arena page. `stats` in particular would put numbers
      // on a record page, and a number this page did not compute is exactly
      // what the honesty rail forbids.
      put(el.headline, plain(prov.headline));
      put(el.provocation, plain(prov.body));

      put(el.position, r.position);
      put(el.counter, counter.counter_position);
      put(el.challenge, counter.challenge);
      put(el.defence, r.defence);

      var ruling = plain(verdict.verdict);
      put(el.verdict, ruling ? "The judge ruled: " + ruling + "." : "The judge ruled.");
      put(el.reasons, verdict.reasons);

      var argued = fmtDate(r.argued_at);
      var published = fmtDate(r.published_at);
      var line = "";
      if (argued) line = "Argued " + argued;
      if (published && published !== argued) {
        line = line ? line + " · published " + published : "Published " + published;
      }
      put(el.dates, line);

      if (el.state) el.state.hidden = true;
      if (el.round) el.round.hidden = false;
    }

    function slugFromLocation() {
      var m = /[?&]r=([^&#]*)/.exec(window.location.search);
      if (!m) return "";
      try { return decodeURIComponent(m[1]); } catch (e) { return m[1]; }
    }

    var slug = slugFromLocation();

    if (!slug) {
      showState(
        "This page shows one published round",
        "It needs the address of a round to show. If you followed a link here, " +
        "the address may have been cut short somewhere along the way.",
        true
      );
      return;
    }

    if (!validSlug(slug)) {
      showState(
        "That is not a round address",
        "The address in the link is not the right shape, so there is nothing to " +
        "look up. Nothing was found or lost — the link is simply wrong.",
        true
      );
      return;
    }

    fetch(API + "/api/v1/tools/gauntlet/round/" + encodeURIComponent(slug), {
      method: "GET",
      headers: { Accept: "application/json" }
    })
      .then(function (res) {
        if (res.status === 404) {
          var e404 = new Error("not found");
          e404.status = 404;
          throw e404;
        }
        if (!res.ok) {
          var err = new Error("HTTP " + res.status);
          err.status = res.status;
          throw err;
        }
        return res.json();
      })
      .then(render)
      .catch(function (err) {
        // 404 is returned for a round that was never published and for one that
        // does not exist, identically and on purpose — the page cannot tell
        // them apart, so it does not pretend to.
        if (err && err.status === 404) {
          showState(
            "No public record at that address",
            "Either nothing was ever published here, or whoever published it has " +
            "since taken it down.",
            true
          );
          return;
        }
        if (err && err.status === 429) {
          showState(
            "Too many requests just now",
            "The record service is rate limited and has asked us to wait. Give it " +
            "a minute and reload — the round is still there.",
            false
          );
          return;
        }
        showState(
          "Could not reach the record",
          "The round may well exist; we could not fetch it just now. Reloading " +
          "in a moment is worth a try.",
          false
        );
      });
  })();
</script>
$grrec$,
  NULL,
  NULL,
  true,
  '["tool"]'::jsonb,
  0,
  'manual'
WHERE NOT EXISTS (
  SELECT 1 FROM content_components WHERE function = 'gauntlet-round-record'
);

-- 2. the page ----------------------------------------------------------------
INSERT INTO pages (
  site_id, name, url, title, page_type, status, build_status,
  nav_label, nav_order, in_header, in_footer, rebuild_policy, meta_description
)
SELECT
  '9ec3b9ee-5b08-461b-b4f8-9e1e03579c74',
  'gauntlet-round-record',
  '/tools/gauntlet/round.html',
  'A round of The Gauntlet | Vonc',
  'tool',
  'active',
  'pending',
  'Round record',
  99,
  false,
  false,
  'owned',
  'One published round of The Gauntlet: the provocation, the position argued against it, the challenge that came back, the defence, and the ruling.'
WHERE NOT EXISTS (
  SELECT 1 FROM pages WHERE site_id = '9ec3b9ee-5b08-461b-b4f8-9e1e03579c74' AND name = 'gauntlet-round-record'
);

-- 3. bind component to page --------------------------------------------------
UPDATE pages SET sections = '["gauntlet-round-record"]'::jsonb
 WHERE site_id = '9ec3b9ee-5b08-461b-b4f8-9e1e03579c74' AND name = 'gauntlet-round-record';

-- rendered_html gets the SAME bytes as html_template, which is only safe
-- because the template has no variables (property 1 above). rerender assembles
-- the page from THIS column, not from content_components.
INSERT INTO page_components (page_id, component_id, position, slot_name, rendered_html, content_data, build_status)
SELECT p.id, c.id, 1, 'gauntlet-round-record', c.html_template, '{}'::jsonb, 'pending'
FROM pages p
CROSS JOIN content_components c
WHERE p.site_id = '9ec3b9ee-5b08-461b-b4f8-9e1e03579c74'
  AND p.name = 'gauntlet-round-record'
  AND c.function = 'gauntlet-round-record'
  AND c.name = 'gauntlet-round-record-vonc-com'
  AND NOT EXISTS (
    SELECT 1 FROM page_components pc2 WHERE pc2.page_id = p.id AND pc2.slot_name = 'gauntlet-round-record'
  );

-- 4. travelling PLAN with acceptance criteria --------------------------------
UPDATE doc_plans SET is_current = false, superseded_at = now()
WHERE subject_type = 'tool' AND subject_key = 'gauntlet-round-record' AND is_current;

-- doc_plans is DELIBERATELY not guarded: supersede-then-insert is how a plan is
-- versioned here (275's convention), so a replay correctly records a new current
-- plan rather than silently keeping a stale one. It is the one statement in this
-- file that is not a no-op on replay, and that is the intended behaviour.
INSERT INTO doc_plans (subject_type, subject_key, body, source, created_by, is_current, pinned)
VALUES (
  'tool', 'gauntlet-round-record',
  $plan$# PLAN — The Gauntlet: public record of one round (vonc.com)

## What it is for
A visitor who finishes a round can share a card of it. The card is an image, so
the argument on it cannot be read by a machine, quoted, or followed. This page is
what the card points at: the whole round, as text, at a stable address.

## Where the address comes from
`POST /api/v1/tools/gauntlet/publish` on the island issues a 10-character slug
for a round that HAS a verdict, and is idempotent — pressing share twice returns
the same slug. `GET /api/v1/tools/gauntlet/round/<slug>` serves it. This page
reads `?r=<slug>` and calls that endpoint. Nothing else writes the address.

## What it will and will not show
Shows: provocation headline and body, the position filed, Vonc's counter and
challenge, the defence, the ruling and its reasons, and the two dates.

Does NOT show: `provocation.stats` (an array of numbers), `primary_cta` or
`secondary_cta` — arena furniture. A number on this page that the page did not
compute is exactly what the honesty rail forbids. No aggregate of any kind: no
count of published rounds, no "most argued", no leaderboard. There are no
participants to aggregate yet, and a communal view before there is a community
would be a claim about the world rather than a report of it.

Nobody is named. There are no accounts, the rounds table stores no name, and the
page says so in its own words rather than in the site footer.

## Safety
Two of the fields — position and defence — are prose typed by a member of the
public and then served to every other visitor. Every field on the page is
written with `textContent`, with no exception and no allowlist, and the file
contains no `innerHTML`, `outerHTML`, `insertAdjacentHTML` or `document.write`.
That is asserted mechanically by `round_record/verify_round_record.py`, which
also cross-checks the slug alphabet and length against the Go constants in
`internal/tools-api/store/rounds.go` so the two cannot drift apart.

## The four states
Every non-success outcome renders in one box, and it starts as "fetching"
rather than as an error, because an error before the response has arrived would
be a claim we have not earned.

| state | what the visitor is told |
|---|---|
| no `?r=` | the page needs a round's address; the link may have been cut short |
| malformed slug | the address is not the right shape, so nothing was looked up |
| 404 | no public record at that address — never published, or taken down |
| network / 429 | we could not fetch it; the round may well exist |

404 is returned identically for "never published" and "does not exist", by
design in the handler, so the page cannot tell them apart and does not pretend
to.

## Delivery
Inline — all CSS and JS ship inside html_template, render_mode='template',
js_content NULL. Zero template variables, which is what makes html_template and
page_components.rendered_html byte-identical and the delivery safe.

## Acceptance criteria

```criteria
{ "profiles": ["desktop","mobile"],
  "container": ".gauntlet-record-section",
  "checks": [
    {"id":"boots","type":"selector_exists","selector":".gauntlet-record-section"},
    {"id":"state-box-exists","type":"selector_exists","selector":"[data-gr-state]"},
    {"id":"round-article-exists","type":"selector_exists","selector":"[data-gr-round]"},
    {"id":"console","type":"no_console_errors"},
    {"id":"status","type":"page_status_ok"},
    {"id":"mobile-fit","type":"no_horizontal_overflow","profiles":["mobile"]}
  ]
}
```

An acceptance run fetches the bare URL with no query string, so what it sees is
the no-slug state — and that IS the honest thing to assert here. The checks
therefore prove the page boots, renders its state box, carries the round
scaffold, and logs nothing; they deliberately do NOT assert a rendered round,
because a run with no slug that showed one would mean the page was inventing it.

Deliberately NO `asset_loads` check: that criterion asserts a JS-extraction path
that was designed and never built, and failed every tool on its first sweep
(TL-016). This component has no external asset by design.

Selectors are copied from the shipped template, not invented.
$plan$,
  'manual', 'gauntlet-record-2026-07-31', true, true
);

-- 5. assert the end state ----------------------------------------------------
-- A migration that skipped for the wrong reason is indistinguishable from one
-- that worked, so this refuses to commit unless every join actually resolves.
DO $assert$
DECLARE
  v_tmpl_len   int;
  v_rendered   int;
  v_vars       int;
  v_sections   jsonb;
  v_slot       text;
  v_policy     text;
  v_nav        boolean;
BEGIN
  SELECT length(html_template) INTO v_tmpl_len
    FROM content_components WHERE function = 'gauntlet-round-record';
  IF v_tmpl_len IS NULL OR v_tmpl_len <> 15758 THEN
    RAISE EXCEPTION 'html_template is % chars, expected 15758', COALESCE(v_tmpl_len, -1);
  END IF;

  SELECT length(pc.rendered_html), p.sections, pc.slot_name, p.rebuild_policy,
         (p.in_header OR p.in_footer)
    INTO v_rendered, v_sections, v_slot, v_policy, v_nav
    FROM page_components pc
    JOIN pages p ON p.id = pc.page_id
   WHERE p.site_id = '9ec3b9ee-5b08-461b-b4f8-9e1e03579c74' AND p.name = 'gauntlet-round-record';

  IF v_rendered IS NULL THEN
    RAISE EXCEPTION 'no page_components row — the CROSS JOIN matched nothing';
  END IF;
  IF v_rendered <> v_tmpl_len THEN
    RAISE EXCEPTION 'rendered_html is % chars but html_template is %', v_rendered, v_tmpl_len;
  END IF;
  IF v_slot <> 'gauntlet-round-record' THEN
    RAISE EXCEPTION 'slot_name is %, must equal the component function', v_slot;
  END IF;
  IF NOT (v_sections ? 'gauntlet-round-record') THEN
    RAISE EXCEPTION 'pages.sections does not contain the slot: %', v_sections;
  END IF;
  IF v_policy <> 'owned' THEN
    RAISE EXCEPTION 'rebuild_policy is %, must be owned', v_policy;
  END IF;
  IF v_nav THEN
    RAISE EXCEPTION 'page is in the nav; it is a permalink target, not a destination';
  END IF;

  SELECT count(*) INTO v_vars
    FROM regexp_matches((SELECT html_template FROM content_components WHERE function='gauntlet-round-record'),
                        '\{\{', 'g');
  IF v_vars <> 0 THEN
    RAISE EXCEPTION 'template has % brace pairs — the copy-both-columns path is unsafe', v_vars;
  END IF;

  RAISE NOTICE 'OK: component % chars, rendered_html identical, slot %, owned, out of nav',
               v_tmpl_len, v_slot;
END
$assert$;

COMMIT;

-- ---------------------------------------------------------------------------
-- AFTER APPLY
--   1. rerender + deploy (assemble-only; safe on an `owned` page):
--        docs/agent_docs/docs024_key_docs_latest/gauntlet_dead_cta/scripts/rerender_page_vonc.sh <page_id>
--   2. verify the SERVED page, not the row:
--        round_record/verify_round_record.py --url https://vonc.com/tools/gauntlet/round.html
-- ---------------------------------------------------------------------------
