-- 745_loancash_restore_disclaimer_third_page.sql
--
-- ** SUPERSEDED BY MIGRATION 743 REVISION 2. NEVER APPLIED. DO NOT RUN. **
--
-- 745 was written to restore the disclaimer on the third page
-- (/guides/check-your-lender-is-authorised.html) after it completed at 14:43:43 UTC under
-- migration 739's defective spec — exactly as 743 revision 1's header predicted it would.
--
-- It is superseded because 743's own council round (corr 4718725c) returned REVISE, and the fix
-- for the objections applies identically to all three affected pages: the restored text is now
-- recovered VERBATIM from `page_component_history` rather than reconstructed by instruction, the
-- items carry `approval_mode='manual'`, and the guard now asserts the `edit_live` literal against
-- page-build-handler's own config rather than merely checking the action is wired somewhere.
-- Splitting three identical repairs across two migrations would have meant two review trails for
-- one decision, so 743 rev 2 covers all three and this file is left as a marker rather than
-- deleted — the number is spent, and a reader who finds it referenced elsewhere should land here.
--
-- Nothing was applied from this file. There is nothing to roll back.
--
-- See: docs/agent_docs/sql_for_agents/743_loancash_restore_content_dropped_by_the_739_rewrite.sql
