-- 745_..._ROLLBACK.sql — SUPERSEDED, NEVER APPLIED, NOTHING TO ROLL BACK.
-- See 743_loancash_restore_content_dropped_by_the_739_rewrite.sql (revision 2), which covers all
-- three affected pages including this one.
