# FILE: configs/image-adapter.yaml
service_info:
  name: "image-generator-adapter"
  version: "1.0.0"
  environment: "development"

server:
  port: "8084"

logging:
  level: "info"

infrastructure:
  kafka_brokers:
    - "kafka-0.kafka-headless:9092"
    - "kafka-1.kafka-headless:9092"
    - "kafka-2.kafka-headless:9092"

  clients_database: {}
  templates_database: {}
  auth_database: {}

  object_storage:
    provider: "s3"
    endpoint: "http://minio:9000"
    bucket: "agent-artifacts"
    access_key_env_var: "MINIO_ACCESS_KEY"
    secret_key_env_var: "MINIO_SECRET_KEY"

custom:
  image_provider: "stability_ai"
  default_model: "stable-diffusion-xl-1024-v1-0"
  timeout_seconds: 90
