# This is a template - DO NOT apply directly
# Use the setup.sh script or create manually
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: ai-persona-system
type: Opaque
stringData:
  clients-db-password: "CHANGE_ME"
  templates-db-password: "CHANGE_ME"
  auth-db-password: "CHANGE_ME"
  mysql-root-password: "CHANGE_ME"

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: ai-persona-system
type: Opaque
stringData:
  access-key: "CHANGE_ME"
  secret-key: "CHANGE_ME"

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: ai-persona-system
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME"

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-secrets
  namespace: ai-persona-system
type: Opaque
stringData:
  anthropic-api-key: "CHANGE_ME"
  stability-api-key: "CHANGE_ME"
  serp-api-key: "CHANGE_ME"

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: ai-persona-system
type: Opaque
stringData:
  admin-password: "CHANGE_ME"