-- ============================================================================
-- L3_fork_palette.sql — give leopardessconsulting.co.uk its OWN palette/theme/
-- collection so its specialised slots (card/header/footer/cta) stop leaking from
-- the shared 'professional-dark' seed (which dresses 4 sites — DO NOT edit it).
--
-- Chain built (leopardess-owned):  sites.style_collection_id
--   -> style_collections(new) -> css_themes(new) -> palettes(new)
-- The new theme reuses the seed's layout (a9001f12 brochure-formal) and
-- typography (31fc3a77 sans-modern); the new collection reuses the seed's
-- header (e99b0dfa) and footer (09034086) components. Only the PALETTE differs.
--
-- Palette is dark-chrome / light-reading (owner decision A4), two-tone gold
-- (bright #C8A951 only on dark; bronze #836E32 for links on light). Every pair
-- WCAG-validated 2026-07-10 (see RUNNING_NOTES turn 10) — the platform does NOT
-- check specialised-slot contrast, so this was done by hand with color_util's
-- formula.
--
-- Deterministic-render note: render_css_from_spec merges design_spec (LLM) over
-- the theme palette for CORE slots only. With NO design_spec present the palette
-- fully determines output. The re-render+deploy is deferred to L9 (one coherent
-- pass), so this script changes the SOURCE only — the live CSS is unchanged until
-- then.
-- ============================================================================
\set ON_ERROR_STOP on
BEGIN;

INSERT INTO palettes (id, name, display_name, description, colours, category,
                      is_active, origin, needs_review, source_site_id, source_domain)
VALUES ('6a1fca38-381c-4e0f-8024-1bd107e3300a','leopardess-dark-gold','Leopardess Dark Gold',
 'Dark chrome, light reading surfaces. Bright gold #C8A951 on dark only; bronze #836E32 links on light (WCAG AA). Forked for leopardessconsulting.co.uk — not shared.',
 '{
   "background":"#FAF8F4","surface":"#FFFFFF","text":"#1A1A1A","text_muted":"#5A5751",
   "accent":"#836E32","primary":"#0D0D0D","secondary":"#F5F0E8","border":"#E4DFD5",
   "heading":"#0D0D0D","primary_hover":"#A8843C",
   "header_bg":"#0D0D0D","header_text":"#F5F0E8",
   "footer_bg":"#0D0D0D","footer_text":"#B9B3A6",
   "card_bg":"#FFFFFF",
   "cta_bg":"#C8A951","cta_text":"#0D0D0D",
   "hero_title":"#F5F0E8","hero_subtitle":"#B9B3A6",
   "primary_text":"#F5F0E8","secondary_text":"#0D0D0D","secondary_hover":"#A8843C"
 }'::jsonb,
 'professional', true, 'site-fork', false, '4851f6fc-71cf-4160-a270-e03d6d3e0732','leopardessconsulting.co.uk');

-- css_content is NOT NULL; clone the seed's as a placeholder. It is fully
-- regenerated by render_css_from_spec at deploy time (L9), so its initial value
-- is never served.
INSERT INTO css_themes (id, name, display_name, description, category,
                        palette_id, layout_id, typography_set_id, css_content,
                        is_active, origin, needs_review, source_site_id, source_domain)
SELECT 'dddea84f-b174-49ef-a24e-6265159effc1','leopardess-dark-gold','Leopardess Dark Gold',
 'Seed brochure-formal layout + sans-modern typography, leopardess palette.',
 'professional', '6a1fca38-381c-4e0f-8024-1bd107e3300a', t.layout_id, t.typography_set_id, t.css_content,
 true, 'site-fork', false, '4851f6fc-71cf-4160-a270-e03d6d3e0732','leopardessconsulting.co.uk'
FROM css_themes t WHERE t.id='fecb962d-3ace-4c19-b08f-088eba46ea53';

INSERT INTO style_collections (id, name, display_name, description,
                               header_component_id, header_home_component_id, footer_component_id,
                               css_theme_id, category, is_active, origin, needs_review,
                               source_site_id, source_domain)
SELECT '2bf359de-4639-4d74-96d7-5f27228c6aaf','leopardess-dark-gold','Leopardess Dark Gold',
 'Leopardess-owned composition. Seed header/footer components, own dark-gold palette.',
 c.header_component_id, c.header_home_component_id, c.footer_component_id,
 'dddea84f-b174-49ef-a24e-6265159effc1','professional', true, 'site-fork', false, '4851f6fc-71cf-4160-a270-e03d6d3e0732','leopardessconsulting.co.uk'
FROM style_collections c WHERE c.id='3196d966-24ef-4415-9dc8-1afbc02166ca';

UPDATE sites SET style_collection_id='2bf359de-4639-4d74-96d7-5f27228c6aaf', updated_at=now() WHERE id='4851f6fc-71cf-4160-a270-e03d6d3e0732';

COMMIT;

-- verify the chain resolves leopardess-only
SELECT s.domain, s.style_collection_id=c.id AS points_to_fork,
       p.name AS palette, p.colours->>'card_bg' AS card_bg,
       p.colours->>'header_bg' AS header_bg, p.colours->>'cta_bg' AS cta_bg,
       p.colours->>'accent' AS accent
FROM sites s
JOIN style_collections c ON c.id=s.style_collection_id
JOIN css_themes t ON t.id=c.css_theme_id
JOIN palettes p ON p.id=t.palette_id
WHERE s.id='4851f6fc-71cf-4160-a270-e03d6d3e0732';
