# FILE: deployments/kustomize/services/content-creator-agent/overlays/production/uk_001/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-persona-system
resources:
  - ../../../base # Reference the base deployment for this agent
  - configs/configmap-content-creator.yaml # Include the agent's specific configmap

labels:
  - pairs:
      environment: production
      region: uk

images:
  - name: docker.io/aqls/content-creator-agent
    newTag: v1.0.1361

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: content-creator-agent