apiVersion: apps/v1
kind: Deployment
metadata:
  name: reasoning-agent
  labels:
    app: reasoning-agent
spec:
  selector:
    matchLabels:
      app: reasoning-agent
  template:
    metadata:
      labels:
        app: reasoning-agent
    spec:
      containers:
        - name: reasoning-agent
          image: your-container-registry/reasoning-agent:latest # Patched by overlays
          env: []
          envFrom:
            - configMapRef:
                name: placeholder-config # Patched by overlays
            - secretRef:
                name: placeholder-secrets # Patched by overlays
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "2Gi"