apiVersion: v1
kind: Service
metadata:
  name: ollama-eval
  labels:
    app: ollama-eval
spec:
  type: ClusterIP
  selector:
    app: ollama-eval
  ports:
    - port: 11434
      targetPort: 11434
      name: http
