apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-manager
spec:
  template:
    spec:
      serviceAccountName: ai-persona-app
      imagePullSecrets:
        - name: docker-hub-creds
      containers:
        - name: core-manager
          env:
            - name: TEMPLATES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: personae-dev-secrets
                  key: templates-db-password
            - name: CLIENTS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: personae-dev-secrets
                  key: clients-db-password
            - name: KAFKA_TOPIC_CREATION_ENABLED
              value: "true"
            - name: KAFKA_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TOPIC_DEFAULT_PARTITIONS
              value: "1"