apiVersion: v1
kind: Service
metadata:
  name: ollama-adapter
  labels:
    app: ollama-adapter
spec:
  type: ClusterIP
  selector:
    app: ollama-adapter
  ports:
    - port: 11434
      targetPort: 11434
      name: http
