-- R4f (2026-07-20) — give MatchMatrix a DURABLE SOURCE in the database.
--
-- The tool was deployed straight to gqls/sites (commit 0a6dc426) and is live,
-- but it had NO row in content_components / page_components. That is a real
-- exposure, not a tidiness point: `pages.tool-matchmatrix` still read
-- build_status='planned' with zero components, so any rebuild of that page
-- would have produced an empty shell and overwritten a working tool — the
-- /bugs_open/001 and /bugs_open/038 class exactly.
--
-- Wiring copied from the live reference implementation on this site
-- (tool-gripper-payload-calculator, verified 2026-07-20):
--   content_components: function=tool-<slug>, render_mode='template',
--                       component_level='tool', category='interactive',
--                       input_schema NULL, name=tool-<slug>-robot-hands-com
--   page_components:    position 2, slot_name=tool-<slug>, content_data '{}'
--
-- Deviation, deliberate: the three existing tool components carry is_active=f.
-- Nothing depends on that (renderAndStoreSiteComponent ignores is_active — the
-- R1 finding), and creating a brand-new component pre-deactivated would be
-- copying an artefact of some past cleanup. This one is created active.
--
-- Apply:  kubectl -n ai-persona-system exec -i postgres-clients-0 -- \
--           psql -U clients_user -d clients_db < THIS_FILE

\set site '00ff3af5-dad8-4770-9f70-3edc267a3c92'

BEGIN;

INSERT INTO content_components
  (name, display_name, description, function, html_template, render_mode,
   component_level, category, is_active)
VALUES
  ('tool-matchmatrix-robot-hands-com',
   'MatchMatrix — Gripper Selection Matrix',
   'Interactive gripper selection tool. Computes the minimum holding force an '
   'application requires, F=(m*a*S)/(mu*n), then tests it against the grippers '
   'held in products (category=gripper), showing each manufacturer figure as '
   'published and marking unpublished parameters rather than inferring them. '
   'Hand-authored 2026-07-20 — NOT generated by tool-generator, which has no '
   'fake-data rule and would invent a catalogue (bugs_open/020).',
   'tool-matchmatrix',
   $MMTOOL$<style>
  .tool-container {
    max-width: 760px;
    margin: 0 auto;
    padding: 1.5rem;
    background: var(--color-surface);
    border: 1px solid var(--color-border);
    border-radius: 8px;
    font-family: inherit;
    color: var(--color-text);
  }

  .tool-container h2 {
    margin: 0 0 0.5rem 0;
    font-size: 1.4rem;
    color: var(--color-primary);
  }

  .tool-description {
    margin: 0 0 1.5rem 0;
    font-size: 0.9rem;
    color: var(--color-text-muted);
    line-height: 1.5;
  }

  .tool-container fieldset {
    border: 1px solid var(--color-border);
    border-radius: 6px;
    padding: 1rem 1rem 0.5rem 1rem;
    margin: 0 0 1.25rem 0;
  }

  .tool-container legend {
    font-size: 0.85rem;
    font-weight: 600;
    color: var(--color-text-muted);
    text-transform: uppercase;
    letter-spacing: 0.04em;
    padding: 0 0.4rem;
  }

  .form-row {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1rem;
    margin-bottom: 1rem;
  }

  .form-group {
    display: flex;
    flex-direction: column;
    gap: 0.35rem;
  }

  .form-group label {
    font-size: 0.875rem;
    font-weight: 500;
    color: var(--color-text);
  }

  .form-group .hint {
    font-size: 0.75rem;
    color: var(--color-text-muted);
  }

  .input-unit-wrap {
    display: flex;
    align-items: stretch;
    border: 1px solid var(--color-border);
    border-radius: 5px;
    overflow: hidden;
    background: var(--color-background);
  }

  .input-unit-wrap input {
    flex: 1;
    min-width: 0;
    border: none;
    background: transparent;
    color: var(--color-text);
    padding: 0.55rem 0.7rem;
    font-size: 0.95rem;
    font-family: inherit;
  }

  .input-unit-wrap input:focus {
    outline: 2px solid var(--color-primary);
    outline-offset: -2px;
  }

  .unit-label {
    display: flex;
    align-items: center;
    padding: 0 0.7rem;
    font-size: 0.8rem;
    color: var(--color-text-muted);
    background: var(--color-surface);
    border-left: 1px solid var(--color-border);
  }

  .form-group select {
    border: 1px solid var(--color-border);
    border-radius: 5px;
    background: var(--color-background);
    color: var(--color-text);
    padding: 0.55rem 0.7rem;
    font-size: 0.95rem;
    font-family: inherit;
  }

  .form-group select:focus {
    outline: 2px solid var(--color-primary);
    outline-offset: -2px;
  }

  .error-msg {
    display: none;
    font-size: 0.75rem;
    color: #f87171;
  }

  .form-group.invalid .error-msg { display: block; }

  .tool-actions {
    display: flex;
    gap: 0.75rem;
    flex-wrap: wrap;
    margin-bottom: 1.25rem;
  }

  .btn-run, .btn-reset {
    font-family: inherit;
    font-size: 0.95rem;
    font-weight: 600;
    padding: 0.65rem 1.4rem;
    border-radius: 5px;
    cursor: pointer;
    border: 1px solid var(--color-border);
  }

  .btn-run {
    background: var(--color-primary);
    color: var(--color-background);
    border-color: var(--color-primary);
  }

  .btn-reset {
    background: transparent;
    color: var(--color-text-muted);
  }

  .btn-run:focus-visible, .btn-reset:focus-visible {
    outline: 2px solid var(--color-primary);
    outline-offset: 2px;
  }

  .requirement-panel {
    display: none;
    border: 1px solid var(--color-border);
    border-radius: 6px;
    padding: 1rem;
    margin-bottom: 1.25rem;
    background: var(--color-background);
  }

  .requirement-panel.visible { display: block; }

  .requirement-headline {
    font-size: 1.1rem;
    font-weight: 600;
    color: var(--color-text);
    margin-bottom: 0.5rem;
  }

  .requirement-headline strong { color: var(--color-primary); }

  .requirement-formula {
    font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    font-size: 0.8rem;
    color: var(--color-text-muted);
    line-height: 1.7;
  }

  .results-list { display: none; flex-direction: column; gap: 0.85rem; }
  .results-list.visible { display: flex; }

  .match-card {
    border: 1px solid var(--color-border);
    border-radius: 6px;
    padding: 0.9rem 1rem;
    background: var(--color-background);
  }

  .match-card.verdict-match { border-left: 3px solid #4ade80; }
  .match-card.verdict-marginal { border-left: 3px solid #fbbf24; }
  .match-card.verdict-unknown { border-left: 3px solid var(--color-text-muted); }
  .match-card.verdict-fail { border-left: 3px solid #f87171; }

  .match-head {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    gap: 0.75rem;
    flex-wrap: wrap;
    margin-bottom: 0.15rem;
  }

  .match-name { font-size: 1rem; font-weight: 600; color: var(--color-text); }
  .match-maker { font-size: 0.78rem; color: var(--color-text-muted); margin-bottom: 0.6rem; }

  .verdict-badge {
    font-size: 0.7rem;
    font-weight: 700;
    letter-spacing: 0.05em;
    text-transform: uppercase;
    padding: 0.2rem 0.5rem;
    border-radius: 3px;
    white-space: nowrap;
  }

  .verdict-match .verdict-badge { background: #4ade80; color: #06240f; }
  .verdict-marginal .verdict-badge { background: #fbbf24; color: #2b1d00; }
  .verdict-unknown .verdict-badge { background: var(--color-text-muted); color: var(--color-background); }
  .verdict-fail .verdict-badge { background: #f87171; color: #2d0606; }

  .criteria-table { width: 100%; border-collapse: collapse; font-size: 0.82rem; }
  .criteria-table th {
    text-align: left;
    font-weight: 500;
    color: var(--color-text-muted);
    padding: 0.3rem 0.6rem 0.3rem 0;
    width: 8.5rem;
    vertical-align: top;
  }
  .criteria-table td { padding: 0.3rem 0; color: var(--color-text); vertical-align: top; }
  .criteria-table tr + tr th, .criteria-table tr + tr td { border-top: 1px solid var(--color-border); }

  .crit-flag { font-weight: 600; margin-left: 0.4rem; font-size: 0.75rem; }
  .crit-pass { color: #4ade80; }
  .crit-fail { color: #f87171; }
  .crit-none { color: var(--color-text-muted); font-style: italic; }

  .conflict-note {
    margin: 0.7rem 0 0 0;
    padding: 0.55rem 0.7rem;
    border-radius: 4px;
    background: var(--color-surface);
    border-left: 2px solid #fbbf24;
    font-size: 0.78rem;
    line-height: 1.55;
    color: var(--color-text-muted);
  }

  .scope-note {
    margin-top: 1.5rem;
    padding-top: 1rem;
    border-top: 1px solid var(--color-border);
    font-size: 0.78rem;
    color: var(--color-text-muted);
    line-height: 1.6;
  }

  .scope-note strong { color: var(--color-text); }

  @media (max-width: 560px) {
    .form-row { grid-template-columns: 1fr; }
    .criteria-table th { width: 7rem; }
  }
</style>

<div class="tool-container">
  <h2>MatchMatrix &mdash; Gripper Selection Matrix</h2>
  <p class="tool-description">
    Enter your workpiece, duty cycle and environment. MatchMatrix calculates the minimum holding
    force the application requires, then tests every gripper in the index against it &mdash; showing
    exactly which criterion passes, which fails, and where a manufacturer publishes no figure at all.
  </p>

  <form id="mmForm" novalidate>

    <fieldset>
      <legend>Workpiece</legend>
      <div class="form-row">
        <div class="form-group" id="fg-mass">
          <label for="mmMass">Workpiece Mass</label>
          <div class="input-unit-wrap">
            <input type="number" id="mmMass" min="0.001" step="any" placeholder="e.g. 2.5" required>
            <span class="unit-label">kg</span>
          </div>
          <span class="error-msg">Enter a mass greater than zero.</span>
        </div>
        <div class="form-group" id="fg-travel">
          <label for="mmTravel">Required Jaw Travel</label>
          <div class="input-unit-wrap">
            <input type="number" id="mmTravel" min="0" step="any" placeholder="e.g. 40" required>
            <span class="unit-label">mm</span>
          </div>
          <span class="hint">Total opening needed across the part</span>
          <span class="error-msg">Enter a travel of zero or more.</span>
        </div>
      </div>
      <div class="form-row">
        <div class="form-group">
          <label for="mmSurface">Surface Material</label>
          <select id="mmSurface">
            <option value="0.10">Glass, smooth (&mu; 0.10)</option>
            <option value="0.15" selected>Steel, dry (&mu; 0.15)</option>
            <option value="0.20">Aluminium, machined (&mu; 0.20)</option>
            <option value="0.25">Plastic / ABS (&mu; 0.25)</option>
            <option value="0.30">Cardboard (&mu; 0.30)</option>
            <option value="0.50">Rubber (&mu; 0.50)</option>
          </select>
          <span class="hint">Sets the friction coefficient &mu;</span>
        </div>
        <div class="form-group">
          <label for="mmSurfaces">Gripping Surfaces</label>
          <select id="mmSurfaces">
            <option value="2" selected>2 &mdash; parallel two-jaw</option>
            <option value="3">3 &mdash; three-jaw centric</option>
          </select>
          <span class="hint">Number of jaws in friction contact</span>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Motion &amp; Duty</legend>
      <div class="form-row">
        <div class="form-group" id="fg-accel">
          <label for="mmAccel">Peak Acceleration</label>
          <div class="input-unit-wrap">
            <input type="number" id="mmAccel" min="0" step="any" value="9.81" required>
            <span class="unit-label">m/s&sup2;</span>
          </div>
          <span class="hint">Gravity (9.81) plus robot acceleration</span>
          <span class="error-msg">Enter a value of zero or more.</span>
        </div>
        <div class="form-group" id="fg-safety">
          <label for="mmSafety">Safety Factor</label>
          <div class="input-unit-wrap">
            <input type="number" id="mmSafety" min="1" step="any" value="2" required>
            <span class="unit-label">&times;</span>
          </div>
          <span class="hint">2 static &middot; 3&ndash;4 dynamic or overhead</span>
          <span class="error-msg">Enter a factor of 1 or more.</span>
        </div>
      </div>
    </fieldset>

    <fieldset>
      <legend>Environment</legend>
      <div class="form-row">
        <div class="form-group">
          <label for="mmIp">Minimum IP Rating</label>
          <select id="mmIp">
            <option value="0" selected>No requirement</option>
            <option value="30">IP30 &mdash; tool-protected</option>
            <option value="54">IP54 &mdash; dust / splash</option>
            <option value="64">IP64 &mdash; dust-tight / splash</option>
            <option value="67">IP67 &mdash; dust-tight / immersion</option>
          </select>
          <span class="hint">Grippers with no published rating are flagged, not excluded</span>
        </div>
        <div class="form-group">
          <label for="mmPayloadCheck">Payload Rating</label>
          <select id="mmPayloadCheck">
            <option value="1" selected>Check against published payload</option>
            <option value="0">Ignore &mdash; force calculation only</option>
          </select>
          <span class="hint">Only 3 of 5 publish a payload figure</span>
        </div>
      </div>
    </fieldset>

    <div class="tool-actions">
      <button type="submit" class="btn-run">Run MatchMatrix</button>
      <button type="button" class="btn-reset" id="mmReset">Reset</button>
    </div>
  </form>

  <div class="requirement-panel" id="mmRequirement" role="status" aria-live="polite"></div>
  <div class="results-list" id="mmResults"></div>

  <div class="scope-note">
    <p><strong>What this index covers.</strong> MatchMatrix tests your requirement against the
    <strong>5 grippers currently held in the robot-hands.com index</strong>, listed below with the
    figures their manufacturers publish. This is the complete index &mdash; it is not a survey of the
    gripper market, and a &ldquo;no match&rdquo; result means nothing in this index fits, not that no
    such gripper exists.</p>
    <p style="margin-top:0.6rem;">Specifications are reproduced as published by Schunk, OnRobot,
    Robotiq, Zimmer Group and Festo. Where a field is blank, that manufacturer does not publish the
    figure &mdash; MatchMatrix marks it <em>not published</em> and never infers a value. Always confirm
    against the current manufacturer datasheet before purchase.</p>
  </div>
</div>

<script>
(function () {
  'use strict';

  // Specifications as published by each manufacturer. `text` is the published
  // string verbatim; the numeric field is that same figure normalised for
  // comparison. A null block means the manufacturer publishes no such figure —
  // it is never inferred. Per-jaw strokes are doubled to a total opening so all
  // travel figures compare like for like.
  var GRIPPERS = [
    {
      name: 'Schunk EGP 40-N-S-B', maker: 'Schunk',
      force: { n: 30, text: '30 N' },
      stroke: { mm: 12, text: '6 mm per jaw (12 mm total)' },
      payload: { kg: 0.15, text: '0.15 kg (recommended workpiece weight)' },
      ip: { v: 30, text: 'IP30' },
      extras: [['Weight', '0.3 kg'], ['Supply', '24 V DC'], ['Interface', 'Digital I/O']]
    },
    {
      name: 'OnRobot 2FG7', maker: 'OnRobot',
      force: { n: 140, text: '20 N to 140 N' },
      stroke: { mm: 73, text: 'up to 73 mm external grip range' },
      payload: { kg: 11, text: '11 kg (24.3 lb)' },
      ip: { v: 67, text: 'IP67' },
      extras: []
    },
    {
      name: 'Robotiq 2F-85', maker: 'Robotiq',
      force: { n: 235, text: '20 to 235 N' },
      stroke: { mm: 85, text: '85 mm' },
      payload: { kg: 5, text: '5 kg' },
      ip: null,
      extras: [['Weight', '925 g'], ['Supply', '24 V DC ±10%']]
    },
    {
      name: 'Zimmer Group GEP5010IO-00-A', maker: 'Zimmer Group',
      force: { n: 1520, text: '1520 N' },
      stroke: { mm: 20, text: '10 mm per jaw (20 mm total)' },
      payload: null,
      ip: { v: 64, text: 'IP64' },
      extras: [['Weight', '1.6 kg'], ['Supply', '24 V'], ['Interface', 'I/O (IO-Link option)']]
    },
    {
      name: 'Festo EHPS-20-A-LK', maker: 'Festo',
      force: { n: 218, text: '218 N' },
      stroke: { mm: 26, text: '13 mm per jaw (26 mm total)' },
      payload: null, ip: null,
      extras: []
    }
  ];

  var form = document.getElementById('mmForm');
  var reqPanel = document.getElementById('mmRequirement');
  var results = document.getElementById('mmResults');
  if (!form) { return; }

  function esc(s) {
    return String(s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }

  function setInvalid(id, bad) {
    var g = document.getElementById(id);
    if (g) { g.classList.toggle('invalid', !!bad); }
  }

  function readInputs() {
    var mass = parseFloat(document.getElementById('mmMass').value);
    var travel = parseFloat(document.getElementById('mmTravel').value);
    var accel = parseFloat(document.getElementById('mmAccel').value);
    var safety = parseFloat(document.getElementById('mmSafety').value);

    var bad = false;
    if (!isFinite(mass) || mass <= 0) { setInvalid('fg-mass', true); bad = true; } else { setInvalid('fg-mass', false); }
    if (!isFinite(travel) || travel < 0) { setInvalid('fg-travel', true); bad = true; } else { setInvalid('fg-travel', false); }
    if (!isFinite(accel) || accel < 0) { setInvalid('fg-accel', true); bad = true; } else { setInvalid('fg-accel', false); }
    if (!isFinite(safety) || safety < 1) { setInvalid('fg-safety', true); bad = true; } else { setInvalid('fg-safety', false); }
    if (bad) { return null; }

    return {
      mass: mass,
      travel: travel,
      accel: accel,
      safety: safety,
      mu: parseFloat(document.getElementById('mmSurface').value),
      n: parseFloat(document.getElementById('mmSurfaces').value),
      ip: parseInt(document.getElementById('mmIp').value, 10),
      checkPayload: document.getElementById('mmPayloadCheck').value === '1'
    };
  }

  // Minimum holding force for a friction grip:
  //   F = (m * a * S) / (mu * n)
  function requiredForce(v) {
    return (v.mass * v.accel * v.safety) / (v.mu * v.n);
  }

  function assess(g, v, fReq) {
    var rows = [];
    var failed = false;
    var unknown = false;

    // Gripping force — always assessed.
    if (g.force) {
      var ok = g.force.n >= fReq;
      if (!ok) { failed = true; }
      var margin = fReq > 0 ? ((g.force.n - fReq) / fReq) * 100 : 0;
      rows.push({
        label: 'Gripping force', text: g.force.text,
        flag: ok ? 'pass' : 'fail',
        note: ok ? (margin >= 0 ? '+' + margin.toFixed(0) + '% margin' : '') : 'needs ' + fReq.toFixed(1) + ' N'
      });
    } else {
      unknown = true;
      rows.push({ label: 'Gripping force', text: null, flag: 'none', note: '' });
    }

    // Jaw travel — assessed whenever a travel was requested.
    if (g.stroke) {
      var okS = g.stroke.mm >= v.travel;
      if (!okS) { failed = true; }
      rows.push({
        label: 'Jaw travel', text: g.stroke.text,
        flag: okS ? 'pass' : 'fail',
        note: okS ? '' : 'needs ' + v.travel + ' mm'
      });
    } else {
      unknown = true;
      rows.push({ label: 'Jaw travel', text: null, flag: 'none', note: '' });
    }

    // Payload — only when the user asked for it to be checked.
    if (v.checkPayload) {
      if (g.payload) {
        var okP = g.payload.kg >= v.mass;
        if (!okP) { failed = true; }
        rows.push({
          label: 'Rated payload', text: g.payload.text,
          flag: okP ? 'pass' : 'fail',
          note: okP ? '' : 'needs ' + v.mass + ' kg'
        });
      } else {
        unknown = true;
        rows.push({ label: 'Rated payload', text: null, flag: 'none', note: '' });
      }
    } else if (g.payload) {
      rows.push({ label: 'Rated payload', text: g.payload.text, flag: '', note: 'not checked' });
    }

    // IP rating — only when the user set a requirement.
    if (v.ip > 0) {
      if (g.ip) {
        var okI = g.ip.v >= v.ip;
        if (!okI) { failed = true; }
        rows.push({
          label: 'IP rating', text: g.ip.text,
          flag: okI ? 'pass' : 'fail',
          note: okI ? '' : 'needs IP' + v.ip
        });
      } else {
        unknown = true;
        rows.push({ label: 'IP rating', text: null, flag: 'none', note: '' });
      }
    } else if (g.ip) {
      rows.push({ label: 'IP rating', text: g.ip.text, flag: '', note: 'no requirement set' });
    }

    // A gripper can pass on its published payload rating and still fail the
    // force calculation, because headline payload figures assume the
    // manufacturer's own friction assumptions. Say so rather than leaving the
    // user to reconcile two rows that appear to contradict each other.
    var conflict = null;
    if (g.force && g.payload && g.force.n < fReq && g.payload.kg >= v.mass) {
      // What this gripper's published force actually holds on the user's
      // surface, and what friction the headline payload rating assumes.
      var holds = (g.force.n * v.mu * v.n) / (v.accel * v.safety);
      var impliedMu = (g.payload.kg * v.accel * v.safety) / (g.force.n * v.n);
      conflict = 'Rated for ' + g.payload.text + ', but ' + g.force.n +
        ' N holds only ' + holds.toFixed(1) + ' kg on your surface (μ ' + v.mu +
        '). That payload rating implies μ ≈ ' + impliedMu.toFixed(2) +
        ' — high-friction or form-fit fingers, not a bare machined surface.';
    }

    var verdict, rank;
    if (failed) {
      verdict = 'No match'; rank = 3;
    } else if (unknown) {
      verdict = 'Insufficient data'; rank = 2;
    } else if (g.force && g.force.n < fReq * 1.25) {
      verdict = 'Marginal'; rank = 1;
    } else {
      verdict = 'Match'; rank = 0;
    }

    var cls = ['verdict-match', 'verdict-marginal', 'verdict-unknown', 'verdict-fail'][rank];
    var headroom = (g.force && fReq > 0) ? g.force.n / fReq : 0;
    return { g: g, rows: rows, verdict: verdict, rank: rank, cls: cls,
             headroom: headroom, conflict: conflict };
  }

  function renderRow(r) {
    var value = r.text === null
      ? '<span class="crit-none">Not published by manufacturer</span>'
      : esc(r.text);
    var flag = '';
    if (r.flag === 'pass') { flag = '<span class="crit-flag crit-pass">PASS</span>'; }
    else if (r.flag === 'fail') { flag = '<span class="crit-flag crit-fail">FAIL</span>'; }
    var note = r.note ? ' <span class="crit-none">' + esc(r.note) + '</span>' : '';
    return '<tr><th scope="row">' + esc(r.label) + '</th><td>' + value + flag + note + '</td></tr>';
  }

  function renderCard(a) {
    var extras = a.g.extras && a.g.extras.length
      ? a.g.extras.map(function (e) {
          return '<tr><th scope="row">' + esc(e[0]) + '</th><td>' + esc(e[1]) + '</td></tr>';
        }).join('')
      : '';
    var conflict = a.conflict
      ? '<p class="conflict-note">' + esc(a.conflict) + '</p>'
      : '';
    return '<div class="match-card ' + a.cls + '">' +
      '<div class="match-head">' +
        '<span class="match-name">' + esc(a.g.name) + '</span>' +
        '<span class="verdict-badge">' + esc(a.verdict) + '</span>' +
      '</div>' +
      '<div class="match-maker">' + esc(a.g.maker) + '</div>' +
      '<table class="criteria-table"><tbody>' +
        a.rows.map(renderRow).join('') + extras +
      '</tbody></table>' + conflict +
    '</div>';
  }

  form.addEventListener('submit', function (ev) {
    ev.preventDefault();
    var v = readInputs();
    if (!v) {
      reqPanel.classList.remove('visible');
      results.classList.remove('visible');
      return;
    }

    var fReq = requiredForce(v);

    reqPanel.innerHTML =
      '<div class="requirement-headline">Minimum holding force required: <strong>' +
        fReq.toFixed(1) + ' N</strong></div>' +
      '<div class="requirement-formula">' +
        'F = (m &times; a &times; S) &divide; (&mu; &times; n)<br>' +
        'F = (' + v.mass + ' kg &times; ' + v.accel + ' m/s&sup2; &times; ' + v.safety +
        ') &divide; (' + v.mu + ' &times; ' + v.n + ') = ' + fReq.toFixed(1) + ' N' +
      '</div>';
    reqPanel.classList.add('visible');

    var assessed = GRIPPERS.map(function (g) { return assess(g, v, fReq); });
    assessed.sort(function (a, b) {
      if (a.rank !== b.rank) { return a.rank - b.rank; }
      return b.headroom - a.headroom;
    });

    var matches = assessed.filter(function (a) { return a.rank === 0 || a.rank === 1; }).length;
    var summary = matches === 0
      ? '<div class="match-maker" style="margin-bottom:0.25rem;">No gripper in this index meets the requirement. The closest are shown first.</div>'
      : '<div class="match-maker" style="margin-bottom:0.25rem;">' + matches + ' of ' + GRIPPERS.length +
        ' indexed grippers meet the requirement.</div>';

    results.innerHTML = summary + assessed.map(renderCard).join('');
    results.classList.add('visible');
  });

  document.getElementById('mmReset').addEventListener('click', function () {
    form.reset();
    ['fg-mass', 'fg-travel', 'fg-accel', 'fg-safety'].forEach(function (id) { setInvalid(id, false); });
    reqPanel.classList.remove('visible');
    results.classList.remove('visible');
    results.innerHTML = '';
  });
})();
</script>
$MMTOOL$,
   'template', 'tool', 'interactive', true)
ON CONFLICT DO NOTHING;

INSERT INTO page_components
  (page_id, component_id, position, slot_name, rendered_html, content_data, build_status)
SELECT p.id, cc.id, 2, 'tool-matchmatrix',
       cc.html_template, '{}'::jsonb, 'deployed'
FROM pages p
CROSS JOIN content_components cc
WHERE p.site_id = :'site' AND p.name = 'tool-matchmatrix'
  AND cc.name = 'tool-matchmatrix-robot-hands-com'
  AND NOT EXISTS (SELECT 1 FROM page_components x WHERE x.page_id = p.id);

UPDATE pages
   SET build_status = 'deployed', deployed_at = now(), updated_at = now()
 WHERE site_id = :'site' AND name = 'tool-matchmatrix';

\echo '--- MatchMatrix now has a source (expect 1 component, length ~20k) ---'
SELECT p.name, p.build_status, cc.name, cc.function, cc.render_mode,
       length(pc.rendered_html) AS len
FROM pages p JOIN page_components pc ON pc.page_id = p.id
JOIN content_components cc ON cc.id = pc.component_id
WHERE p.site_id = :'site' AND p.name = 'tool-matchmatrix';

COMMIT;
