apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-chassis
  labels:
    app: agent-chassis
spec:
  selector:
    matchLabels:
      app: agent-chassis
  template:
    metadata:
      labels:
        app: agent-chassis
    spec:
      containers:
        - name: agent-chassis
          image: your-container-registry/agent-chassis:latest # Patched by overlays
          envFrom:
            - configMapRef:
                name: placeholder-config # Patched by overlays
            - secretRef:
                name: placeholder-secrets # Patched by overlays
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"