// FILE: platform/orchestration/datahelpers/element_refs.go
//
// OrphanElementRefs — the element ids a page's own JavaScript addresses that
// exist nowhere in that page's HTML and are never created by the script.
//
// WHY THIS EXISTS. webdesign.co.uk's 63 tools were PORTED from two other sites
// as HTML blobs rather than born through the generator. Whatever trimmed them
// dropped markup the scripts need, and the result ships a page whose script
// throws on the first line that touches a missing element:
//
//	TypeError: Cannot read properties of null (reading 'getContext')
//	TypeError: Cannot set properties of null (setting 'innerHTML')
//
// The visitor sees a tool with no inputs. Nothing in the platform saw anything:
// the page renders, deploys, returns 200, and every existing check passes it.
// Measured 2026-07-29 — 10 live pages fleet-wide are in this state and the
// oldest has been broken since it was ported.
//
// WHY IT IS DECIDABLE STATICALLY, unlike its neighbours. check_dead_controls
// deliberately refuses to judge "<button> with no handler" from source, because
// JS binds handlers at runtime and absence of evidence is not evidence. This is
// the opposite case: the script names the id as a STRING LITERAL, the id is
// either in the document text or it is not, and no runtime behaviour can
// conjure one that the page never writes. The claim is about the artefact, not
// about what the artefact will do.
//
// EVERY RULE BELOW EXISTS TO AVOID A FALSE POSITIVE, because a wrong finding
// here sends a fixer at a working tool:
//
//   - present ids are harvested from the WHOLE page text, INCLUDING inside
//     script string literals. A tool that builds its own markup with
//     `out.innerHTML = '<input id="qty">'` has that id counted as present. This
//     over-counts on purpose: a name that appears anywhere is never reported.
//   - an id assigned dynamically (`el.id = 'x'`, `setAttribute('id','x')`)
//     counts as present.
//   - a page that INTERPOLATES ids from data (`id="${f.name}"`) has an id set
//     that cannot be known statically, so on such a page any referenced id that
//     also appears as a quoted string somewhere OTHER than a lookup argument is
//     treated as present. See the correction below — this rule was added
//     because its absence produced a false positive on a working tool.
//   - only bare `#id` selectors are read from querySelector. A compound or
//     descendant selector is ignored rather than half-parsed.
//   - the caller passes the WHOLE page — every component plus the site chrome —
//     so a script legitimately reaching a nav element is not flagged.
//
// CORRECTED 2026-07-29, SAME DAY, BY THE BROWSER. The first version of this
// file claimed 10 of 98 flagged with all 10 confirmed broken. That was wrong:
// the confirmation had been run against a URL I CONSTRUCTED (/tools/x.html)
// rather than the one the database gives (/tools/x/index.html), so one of the
// ten was "confirmed" against a 404 page. Re-adjudicated properly — load each
// live page, ask whether each flagged id resolves after load — the true score
// was 9 true positives and ONE FALSE POSITIVE: css-filter-playground, whose six
// sliders are generated by
//
//	group.innerHTML = `<input type="range" id="${f.name}" ...>`
//
// from an array of filter descriptors. Every slider is present in the browser;
// none is present in the source. The dynamic-interpolation rule above closes
// exactly that hole, and the 9 real findings survive it unchanged.
//
// Two lessons worth keeping, because both were mine: a verdict from a URL you
// built is a verdict about a page you invented, and a static id set is only
// knowable when the page does not compute it.
//
// MEASURED PRECISION, re-measured after the correction (2026-07-29, live DB):
//
//	98 deployed script-carrying pages fleet-wide → 9 flagged, all 9 on
//	webdesign.co.uk, all 9 adjudicated in a real browser at the URL the
//	database gives: every flagged id fails to resolve after load.
//	32 library tool templates → 0 flagged.
//
// The 0-of-32 is what makes a hard pre-deploy refusal safe (deploy_tool_action):
// it cannot fire on anything that exists today.
//
// KNOWN AND DELIBERATE FALSE NEGATIVES. This finds one defect class, not all of
// them. Two tools that throw the same null-reference error are NOT flagged
// (blueprint-compiler, micro-cms) because they address elements by class or by
// a compound selector. Widening the selector parse would trade the precision
// above for coverage; the browser tier is where that coverage belongs.

package datahelpers

import (
	"regexp"
	"sort"
)

var (
	// document.getElementById('foo') — the id is a string literal.
	refByIDRe = regexp.MustCompile(`getElementById\(\s*['"]([A-Za-z0-9_\-:.]+)['"]\s*\)`)

	// querySelector('#foo') / querySelectorAll('#foo') — bare id selectors only.
	// A compound selector ('#foo .bar', '#foo, #baz') does not match and is
	// therefore never judged.
	refQuerySelRe = regexp.MustCompile(`querySelector(?:All)?\(\s*['"]#([A-Za-z0-9_\-]+)['"]\s*\)`)

	// id="foo" anywhere in the page text, markup or string literal alike.
	presentIDRe = regexp.MustCompile(`\bid\s*=\s*["']([^"']+)["']`)

	// el.id = 'foo' / setAttribute('id', 'foo') — created at runtime.
	dynamicIDRe = regexp.MustCompile(`(?:\.id\s*=|setAttribute\(\s*["']id["']\s*,)\s*["']([A-Za-z0-9_\-:.]+)["']`)

	// id="${...}" — the page COMPUTES its ids, so its id set is not statically
	// knowable and the rules below have to loosen for that page only.
	dynamicIDTemplateRe = regexp.MustCompile(`\bid\s*=\s*["'][^"']*\$\{`)

	// Any quoted bareword. Used only on a dynamic-id page, and only after the
	// lookup arguments have been blanked out, to ask "could this name have come
	// from the data that feeds the template?".
	quotedWordRe = regexp.MustCompile(`['"]([A-Za-z0-9_\-:.]+)['"]`)
)

// DocumentIDs is one document's evidence about which element ids it has. It is
// the SHARED answer to "does this page contain or create an element with this
// id", used by two consumers that must never disagree about what an id is:
//
//   - OrphanElementRefs (below) — a SCRIPT names an id the page lacks;
//   - the dead_fragment_link arm of check_phantom_internal_links — a LINK names
//     an id the page lacks.
//
// They ask the same question from opposite ends, and every conservatism in the
// presence test was paid for by a false positive on a working tool (see the
// 2026-07-29 correction in this file's header). A second implementation would
// re-buy that lesson at the price of sending a fixer at a page that works.
//
// Build it once per document with NewDocumentIDs and ask it as many times as
// there are references — the regex scans are the expensive part, and a page's
// links are many while its id set is one.
type DocumentIDs struct {
	// present holds ids the document declares (id="x") or assigns at runtime
	// (el.id = 'x', setAttribute('id','x')).
	present map[string]struct{}
	// loose holds every quoted bareword outside a lookup argument, and is
	// populated ONLY for a document that interpolates its ids from data — where
	// the real id set is computed and cannot be read off the source at all.
	loose map[string]struct{}
}

// NewDocumentIDs scans a WHOLE page — every component's rendered HTML plus the
// site chrome — for its id evidence. Passing one component in isolation makes
// every id in its siblings look absent, which is a false positive by
// construction, in both consumers.
func NewDocumentIDs(pageHTML string) DocumentIDs {
	d := DocumentIDs{present: map[string]struct{}{}}
	for _, m := range presentIDRe.FindAllStringSubmatch(pageHTML, -1) {
		d.present[m[1]] = struct{}{}
	}
	for _, m := range dynamicIDRe.FindAllStringSubmatch(pageHTML, -1) {
		d.present[m[1]] = struct{}{}
	}

	// On a page that interpolates ids from data, the id set is computed and
	// cannot be read off the source. Rather than refuse to judge the page at
	// all — which would have cost coverage on four genuinely broken tools that
	// ALSO build markup dynamically — the test loosens just enough: a name that
	// appears as a quoted string anywhere other than a lookup argument could be
	// one of the values feeding the template, so it is treated as present.
	//
	// Blanking the lookup arguments first is the load-bearing half. Without it
	// every referenced id trivially appears as a quoted string — inside its own
	// getElementById call — and the check would silently pass everything.
	if dynamicIDTemplateRe.MatchString(pageHTML) {
		d.loose = map[string]struct{}{}
		stripped := refQuerySelRe.ReplaceAllString(
			refByIDRe.ReplaceAllString(pageHTML, "getElementById()"), "querySelector()")
		for _, m := range quotedWordRe.FindAllStringSubmatch(stripped, -1) {
			d.loose[m[1]] = struct{}{}
		}
	}
	return d
}

// Satisfies reports whether an element with this id exists in the document or
// is created by it. It answers TRUE when in doubt: every caller's wrong answer
// is a finding against a page that works.
func (d DocumentIDs) Satisfies(id string) bool {
	if id == "" {
		return false
	}
	if _, ok := d.present[id]; ok {
		return true
	}
	if d.loose != nil {
		if _, ok := d.loose[id]; ok {
			return true
		}
	}
	return false
}

// InterpolatesIDs reports whether the document computes its ids from data
// (id="${...}"), so its true id set is not statically knowable and Satisfies
// has fallen back to the loose test. A caller that needs to say WHY it is not
// judging — or to decline to judge at all — asks this rather than re-deriving it.
func (d DocumentIDs) InterpolatesIDs() bool { return d.loose != nil }

// OrphanElementRefs returns the sorted, de-duplicated ids that pageHTML's
// scripts address but that pageHTML never contains or creates. An empty result
// means the check found nothing to say — which is the common case and the only
// safe default.
//
// pageHTML must be the WHOLE page: every component's rendered HTML plus the
// site chrome. Passing one component in isolation will report ids that live in
// its siblings, which is a false positive by construction.
func OrphanElementRefs(pageHTML string) []string {
	referenced := map[string]struct{}{}
	for _, m := range refByIDRe.FindAllStringSubmatch(pageHTML, -1) {
		referenced[m[1]] = struct{}{}
	}
	for _, m := range refQuerySelRe.FindAllStringSubmatch(pageHTML, -1) {
		referenced[m[1]] = struct{}{}
	}
	if len(referenced) == 0 {
		return nil
	}

	ids := NewDocumentIDs(pageHTML)
	orphans := make([]string, 0, len(referenced))
	for id := range referenced {
		if ids.Satisfies(id) {
			continue
		}
		orphans = append(orphans, id)
	}
	if len(orphans) == 0 {
		return nil
	}
	sort.Strings(orphans)
	return orphans
}
