// FILE: platform/orchestration/datahelpers/fetch_provenance.go
//
// Provenance for stored observations, taken from the component that performed the
// fetch — never from a model's account of its own evidence.
//
// bugs_open/100: StoreBusinessVerificationAction read source_url/source_type/
// source_name out of the LLM's own output object. The prompt never asked for them,
// so all 2,970 rows in business_intel.data_observations carried empty provenance —
// and the obvious repair (ask the model for the URL) is the wrong one: it makes
// provenance an assertion generated by the same call that generated the facts, with
// nothing to check it against. This estate was remediated in July for exactly that
// class of AI-asserted claim (bugs_closed/043, bugs_closed/061).
//
// The fetcher already knows the answer and already writes it down: every webscrape
// provider result carries "url" and "captured_at", set beside the HTTP call
// (internal/adapters/webscrape/providers/firecrawl.go). This file is the reader for
// that record, so any vertical's writer can take provenance from the fetch rather
// than re-deriving it — or worse, asking for it.

package datahelpers

import (
	"net/url"
	"strings"
)

// FetchProvenance is where an observation came from, as recorded by the fetch.
type FetchProvenance struct {
	// SourceURL is the URL actually retrieved. Empty means "not recorded" — it
	// must never be back-filled from a model's output.
	SourceURL string

	// SourceName is the host, for display and grouping (e.g. "example.co.uk").
	SourceName string

	// SourceType names the mechanism, not the vertical (e.g. "website_scrape").
	SourceType string

	// CapturedAt is the fetch time as recorded by the fetcher, RFC3339. Empty if
	// the provider did not stamp it.
	CapturedAt string
}

// SourceTypeWebsiteScrape is the mechanism recorded for anything retrieved by the
// webscrape adapter. It is deliberately about HOW the data was obtained, not what
// it was about — a per-vertical value here would make provenance unqueryable
// across verticals.
const SourceTypeWebsiteScrape = "website_scrape"

// scrapeResultPaths are the shapes a scrape result arrives in by the time a later
// step reads it out of collected_data. A reader that only understands one shape
// FAILS OPEN — it finds no URL and reads as "there was no provenance" rather than
// "I could not parse it". Checked in order, first hit wins.
//
// "data.url" is the CONFIRMED live shape for the webscrape adapter, traced through
// the code rather than sampled (no run with a scraped_data payload survives —
// vet collection has been off since 2026-03-18 and orchestration_states is on a
// retention clock):
//
//	adapter sendSuccessResponse → body: {success, body: {data: <provider result>}, …}
//	types.ResponseBody.Body     → {data: <provider result>}
//	coordinator.parseResponseBody → CleanDataMap of that
//	applyResponseToState        → collected_data[output_field] = {data: {url, captured_at, …}}
//
// The others are kept because that chain has several unwrap points (output_mapping
// short-circuits it entirely, and spawn/call paths unwrap differently), and being
// wrong here means silently storing an unsourced row — the failure this whole file
// exists to prevent. [UNVERIFIED] which non-"data.url" shapes occur in practice.
var scrapeResultPaths = []string{
	"url",
	"data.url",
	"body.data.url",
	"body.body.data.url",
	"result.url",
	"scraped_data.url",
}

// ExtractFetchProvenance pulls provenance out of a scrape result.
//
// The bool reports whether a source URL was found. It is the discriminating
// return: an empty FetchProvenance with false means the fetch record could not be
// read, which is a wiring fault to surface — NOT permission to store the
// observation unsourced, and NOT an invitation to substitute the model's claim.
func ExtractFetchProvenance(scraped interface{}) (FetchProvenance, bool) {
	m, ok := scraped.(map[string]interface{})
	if !ok || len(m) == 0 {
		return FetchProvenance{}, false
	}

	var fetchedURL string
	for _, path := range scrapeResultPaths {
		if v := ExtractNestedField(m, path); v != nil {
			if s, ok := v.(string); ok && strings.TrimSpace(s) != "" {
				fetchedURL = strings.TrimSpace(s)
				break
			}
		}
	}
	if fetchedURL == "" {
		return FetchProvenance{}, false
	}

	prov := FetchProvenance{
		SourceURL:  fetchedURL,
		SourceType: SourceTypeWebsiteScrape,
		SourceName: hostOf(fetchedURL),
	}

	for _, path := range []string{"captured_at", "data.captured_at", "body.data.captured_at", "body.body.data.captured_at"} {
		if v := ExtractNestedField(m, path); v != nil {
			if s, ok := v.(string); ok && strings.TrimSpace(s) != "" {
				prov.CapturedAt = strings.TrimSpace(s)
				break
			}
		}
	}

	return prov, true
}

// hostOf returns the host of a URL, without the leading "www.". Falls back to the
// raw string when it will not parse — a source name is for display, and losing it
// is never a reason to lose the URL.
func hostOf(raw string) string {
	u, err := url.Parse(raw)
	if err != nil || u.Host == "" {
		return raw
	}
	return strings.TrimPrefix(u.Host, "www.")
}
