-- SEED — finance directory components (Phase B, DIR-001): six rows, a
-- snippet + listing pair per kind (mortgage-lender, savings-provider,
-- health-insurer). GENERATED by gen_finance_components.sh from one template
-- so the six rows cannot drift from each other — edit the generator, not a
-- row, if a shared change is needed.
--
-- ⚠ APPLY ONLY AFTER the Phase B image is live and pod-verified (the
-- queryresolve arms for query.<kind>_directory[_full] ship in that binary;
-- a server render on the old binary fails at render time, silently, per the
-- adoption seed's own lesson). Gate: the same pod-grep as the researcher
-- tasks' enable-gate ("per kind (Phase B kind-scoped keys)").
--
-- Shape follows SEED_adoption_components.sql exactly: component_level
-- 'section' (chrome-level JS silently dropped, bugs 041); the <style> block
-- ships IN html_template (bugs 072 — nothing else styles a component);
-- dual-layer render (server html_template from query.*, js_content
-- refreshing from the published JSON); DOM built via createElement/
-- textContent, never innerHTML string-building — researched third-party
-- text is the widest injection surface we have; innerHTML only ever clears.
--
-- CLASS NAMES: the three finance kinds share one .findir-* vocabulary,
-- DELIBERATELY diverging from the donor's one-prefix-per-register lesson in
-- the narrow case only: these three registers are one portfolio family and
-- SHOULD restyle together, while .findir-* keeps them isolated from
-- .model-card/.adoption-card exactly as that lesson requires.
--
-- Claim fields render raw (snake_case → spaces client-side) — same as both
-- donor pairs. NON-PRICE facts only: the vocabulary is closed at
-- registration (financeKindFieldAllowlist, directory_claims.go), so no
-- price-shaped claim can exist to render.
--
-- REMINDER (brochure landmine, donor header): these rows make the
-- components EXIST; the build-site-planner prompt does NOT name them yet —
-- that is migration B3e, and until it lands no from-scratch plan selects
-- them (the content-gap path can, via the check profiles' Suggestion).

BEGIN;

-- ═══════════════════════════════════════════════════════════════════════════
-- mortgage-lender-directory (homepage snippet, kind=mortgage-lender)
-- ═══════════════════════════════════════════════════════════════════════════
INSERT INTO content_components (
    name, display_name, description, function, category, component_level,
    section_type, render_mode, suitable_site_types, suitable_page_types,
    created_from, input_schema, html_template, js_content
)
SELECT
    'UK Mortgage Lender Directory', 'Mortgage Lender Directory', 'Homepage snippet: cited directory of UK mortgage lenders (regulator status, product types, lender type — non-price facts only), server-rendered from query.mortgage_lender_directory, refreshed client-side from data/mortgage-lender-directory.json',
    'mortgage-lender-directory', 'content', 'section', 'mortgage-lender-directory', 'template',
    '["brochure"]'::jsonb, '[]'::jsonb, 'manual',
    $schema${
  "notes": "entries are server-rendered from query.mortgage_lender_directory (Phase B, DIR-001); mortgage-lender-directory.js refreshes client-side from data/mortgage-lender-directory.json. Resolver output is pre-escaped for the template; the JSON path is raw text, escaped client-side via textContent/createElement — never innerHTML string-building (researched third-party text). NON-PRICE facts only: the closed per-kind field vocabulary is enforced at registration (financeKindFieldAllowlist), so no price-shaped claim can reach these cards.",
  "fields": {
    "entries": {
      "type": "array",
      "items": {
        "slug": {"type": "text"}, "name": {"type": "text"}, "owner": {"type": "text"},
        "summary": {"type": "text"}, "claims": {"type": "array"},
        "docs_url": {"type": "url"}, "video_urls": {"type": "array"}
      },
      "limit": 12,
      "source": "query.mortgage_lender_directory",
      "required": false,
      "on_missing": "skip_field"
    },
    "headline": {
      "type": "text", "source": "llm", "default": "UK mortgage lenders, with cited facts", "required": true,
      "description": "Section heading — generated by content writer, tailored to site identity"
    },
    "subheadline": {
      "type": "text", "source": "llm", "required": false,
      "description": "One honest sentence on what this directory is: named UK lenders, every fact cited to its source. Never mention rates or prices — the directory carries none by design. May carry the honesty clause: a citation proves where a fact came from, not that it is correct."
    }
  },
  "data_source": "/data/mortgage-lender-directory.json",
  "render_action": "render_directory",
  "refresh_interval": "6h"
}$schema$::jsonb,
    $html$<style>
.findir-section { padding: var(--spacing-section, 4rem 0); }
.findir-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 1.5rem;
    margin-top: 2rem;
}
.findir-card {
    border: 1px solid var(--section-border, var(--color-border, rgba(0,0,0,0.12)));
    border-radius: 8px;
    background: var(--section-surface, var(--color-surface, rgba(0,0,0,0.02)));
    overflow: hidden;
    transition: transform 0.2s, box-shadow 0.2s;
}
.findir-card:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(0,0,0,0.08); }
.findir-card-content { padding: 1.25rem 1.5rem 1.5rem; }
.findir-card-title {
    margin: 0 0 0.5rem;
    font-size: 1.15rem;
    line-height: 1.3;
    color: var(--section-heading, var(--color-heading, inherit));
}
.findir-card-owner {
    display: block; font-size: 0.8rem; font-weight: 500;
    letter-spacing: 0.04em; text-transform: uppercase; opacity: 0.65; margin-top: 0.25rem;
}
.findir-card-summary { margin: 0 0 1rem; font-size: 0.95rem; line-height: 1.55; color: var(--section-text, inherit); }
.findir-card-claims {
    list-style: none; margin: 0 0 0.5rem; padding: 0;
    border-top: 1px solid var(--section-border, rgba(0,0,0,0.08));
}
.findir-card-claims li {
    display: flex; flex-wrap: wrap; align-items: baseline; gap: 0.4rem;
    padding: 0.5rem 0; border-bottom: 1px solid var(--section-border, rgba(0,0,0,0.08));
    font-size: 0.9rem;
}
.findir-claim-field { flex: 1 1 45%; opacity: 0.7; text-transform: capitalize; }
.findir-claim-value { font-weight: 600; }
.findir-claim-source {
    font-size: 0.75rem; text-decoration: none; opacity: 0.6;
    border-bottom: 1px dotted currentColor;
}
.findir-claim-source:hover { opacity: 1; }
.findir-section-footer { margin-top: 2rem; text-align: center; }
.findir-more-link {
    display: inline-block; font-weight: 600; text-decoration: none;
    color: var(--color-primary, #1e40af);
}
.findir-more-link:hover { text-decoration: underline; }
.findir-empty { opacity: 0.7; }
@media (max-width: 600px) { .findir-grid { grid-template-columns: 1fr; } }
</style>
<!-- mortgage-lender-directory component -->
<section data-component="mortgage-lender-directory" class="findir-section section-padding">
  <div class="container">
    <h2 class="section-heading" id="mortgage-lender-directory-headline">{{.headline}}</h2>
    {{if .subheadline}}<p class="section-subheadline" id="mortgage-lender-directory-subheadline">{{.subheadline}}</p>{{end}}
    <div class="findir-grid" id="mortgage-lender-directory-container">
      {{if .entries}}{{range .entries}}
      <article class="findir-card"><div class="findir-card-content">
        <h3 class="findir-card-title">{{.name}}{{if .owner}} <span class="findir-card-owner">{{.owner}}</span>{{end}}</h3>
        {{if .summary}}<p class="findir-card-summary">{{.summary}}</p>{{end}}
        {{if .claims}}<ul class="findir-card-claims">
          {{range .claims}}<li><span class="findir-claim-field">{{.field}}</span> <span class="findir-claim-value">{{.value}}{{if .unit}} {{.unit}}{{end}}</span>{{if .url}} <a href="{{.url}}" target="_blank" rel="noopener noreferrer" class="findir-claim-source">source</a>{{end}}</li>{{end}}
        </ul>{{end}}
      </div></article>
      {{end}}{{else}}<noscript>
        <p class="findir-empty">Enable JavaScript to see this directory.</p>
      </noscript>{{end}}
    </div>
    <div id="mortgage-lender-directory-footer"></div>
  </div>
</section>
<script src="/tools/assets/mortgage-lender-directory.js"></script>$html$,
    $js$(function() {
  function el(tag, opts) {
    var e = document.createElement(tag);
    opts = opts || {};
    if (opts.className) e.className = opts.className;
    if (opts.text) e.textContent = opts.text;
    if (opts.href) { e.href = opts.href; e.target = "_blank"; e.rel = "noopener noreferrer"; }
    return e;
  }
  function renderCard(entry) {
    var card = el("article", {className: "findir-card"});
    var content = el("div", {className: "findir-card-content"});
    var title = el("h3", {className: "findir-card-title", text: entry.name || ""});
    if (entry.owner && entry.owner !== entry.name) {
      title.appendChild(el("span", {className: "findir-card-owner", text: " " + entry.owner}));
    }
    content.appendChild(title);
    if (entry.summary) {
      content.appendChild(el("p", {className: "findir-card-summary", text: entry.summary}));
    }
    if (entry.claims && entry.claims.length > 0) {
      var list = document.createElement("ul");
      list.className = "findir-card-claims";
      entry.claims.forEach(function(c) {
        var li = document.createElement("li");
        li.appendChild(el("span", {className: "findir-claim-field", text: (c.field || "").split("_").join(" ")}));
        li.appendChild(document.createTextNode(" "));
        var valueText = c.value || "";
        if (c.unit) valueText += " " + c.unit;
        li.appendChild(el("span", {className: "findir-claim-value", text: valueText}));
        if (c.url) {
          li.appendChild(document.createTextNode(" "));
          li.appendChild(el("a", {className: "findir-claim-source", text: "source", href: c.url}));
        }
        list.appendChild(li);
      });
      content.appendChild(list);
    }
    card.appendChild(content);
    return card;
  }
  fetch("/data/mortgage-lender-directory.json")
    .then(function(r) { return r.json(); })
    .then(function(data) {
      var headlineEl = document.getElementById("mortgage-lender-directory-headline");
      if (headlineEl && data.headline) headlineEl.textContent = data.headline;
      var container = document.getElementById("mortgage-lender-directory-container");
      if (container && data.entries && data.entries.length > 0) {
        container.innerHTML = "";
        data.entries.forEach(function(entry) { container.appendChild(renderCard(entry)); });
      }
      var footer = document.getElementById("mortgage-lender-directory-footer");
      if (footer && data.directory_url) {
        footer.innerHTML = "";
        var wrap = document.createElement("div");
        wrap.className = "findir-section-footer";
        var link = el("a", {className: "findir-more-link", text: data.directory_label || "Browse the full directory"});
        link.href = data.directory_url;
        wrap.appendChild(link);
        footer.appendChild(wrap);
      }
    })
    .catch(function() {});
})();$js$
WHERE NOT EXISTS (SELECT 1 FROM content_components WHERE function = 'mortgage-lender-directory');

-- ═══════════════════════════════════════════════════════════════════════════
-- mortgage-lender-directory-listing (dedicated page, kind=mortgage-lender, full depth)
-- ═══════════════════════════════════════════════════════════════════════════
INSERT INTO content_components (
    name, display_name, description, function, category, component_level,
    section_type, render_mode, suitable_site_types, suitable_page_types,
    created_from, input_schema, html_template, js_content
)
SELECT
    'UK Mortgage Lender Directory (full listing)', 'Mortgage Lender Directory — Full Listing', 'Dedicated mortgage-lenders page: every listed UK lender with its cited non-price facts, server-rendered from query.mortgage_lender_directory_full, refreshed client-side from data/mortgage-lender-directory-full.json',
    'mortgage-lender-directory-listing', 'content', 'section', 'mortgage-lender-directory-listing', 'template',
    '["brochure"]'::jsonb, '["mortgage-lenders"]'::jsonb, 'manual',
    $schema${
  "notes": "entries are server-rendered from query.mortgage_lender_directory_full (Phase B, DIR-001); mortgage-lender-directory-listing.js refreshes client-side from data/mortgage-lender-directory-full.json. Resolver output is pre-escaped for the template; the JSON path is raw text, escaped client-side via textContent/createElement — never innerHTML string-building (researched third-party text). NON-PRICE facts only: the closed per-kind field vocabulary is enforced at registration (financeKindFieldAllowlist), so no price-shaped claim can reach these cards.",
  "fields": {
    "entries": {
      "type": "array",
      "items": {
        "slug": {"type": "text"}, "name": {"type": "text"}, "owner": {"type": "text"},
        "summary": {"type": "text"}, "claims": {"type": "array"},
        "docs_url": {"type": "url"}, "video_urls": {"type": "array"}
      },
      "limit": 50,
      "source": "query.mortgage_lender_directory_full",
      "required": false,
      "on_missing": "skip_field"
    },
    "headline": {
      "type": "text", "source": "llm", "default": "UK mortgage lenders, with cited facts", "required": true,
      "description": "Section heading — generated by content writer, tailored to site identity"
    },
    "subheadline": {
      "type": "text", "source": "llm", "required": false,
      "description": "One honest sentence on what this directory is: named UK lenders, every fact cited to its source. Never mention rates or prices — the directory carries none by design. May carry the honesty clause: a citation proves where a fact came from, not that it is correct."
    }
  },
  "data_source": "/data/mortgage-lender-directory-full.json",
  "render_action": "render_directory",
  "refresh_interval": "6h"
}$schema$::jsonb,
    $html$<style>
.findir-section { padding: var(--spacing-section, 4rem 0); }
.findir-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 1.5rem;
    margin-top: 2rem;
}
.findir-card {
    border: 1px solid var(--section-border, var(--color-border, rgba(0,0,0,0.12)));
    border-radius: 8px;
    background: var(--section-surface, var(--color-surface, rgba(0,0,0,0.02)));
    overflow: hidden;
    transition: transform 0.2s, box-shadow 0.2s;
}
.findir-card:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(0,0,0,0.08); }
.findir-card-content { padding: 1.25rem 1.5rem 1.5rem; }
.findir-card-title {
    margin: 0 0 0.5rem;
    font-size: 1.15rem;
    line-height: 1.3;
    color: var(--section-heading, var(--color-heading, inherit));
}
.findir-card-owner {
    display: block; font-size: 0.8rem; font-weight: 500;
    letter-spacing: 0.04em; text-transform: uppercase; opacity: 0.65; margin-top: 0.25rem;
}
.findir-card-summary { margin: 0 0 1rem; font-size: 0.95rem; line-height: 1.55; color: var(--section-text, inherit); }
.findir-card-claims {
    list-style: none; margin: 0 0 0.5rem; padding: 0;
    border-top: 1px solid var(--section-border, rgba(0,0,0,0.08));
}
.findir-card-claims li {
    display: flex; flex-wrap: wrap; align-items: baseline; gap: 0.4rem;
    padding: 0.5rem 0; border-bottom: 1px solid var(--section-border, rgba(0,0,0,0.08));
    font-size: 0.9rem;
}
.findir-claim-field { flex: 1 1 45%; opacity: 0.7; text-transform: capitalize; }
.findir-claim-value { font-weight: 600; }
.findir-claim-source {
    font-size: 0.75rem; text-decoration: none; opacity: 0.6;
    border-bottom: 1px dotted currentColor;
}
.findir-claim-source:hover { opacity: 1; }
.findir-section-footer { margin-top: 2rem; text-align: center; }
.findir-more-link {
    display: inline-block; font-weight: 600; text-decoration: none;
    color: var(--color-primary, #1e40af);
}
.findir-more-link:hover { text-decoration: underline; }
.findir-empty { opacity: 0.7; }
@media (max-width: 600px) { .findir-grid { grid-template-columns: 1fr; } }
</style>
<!-- mortgage-lender-directory-listing component -->
<section data-component="mortgage-lender-directory-listing" class="findir-section section-padding">
  <div class="container">
    <h2 class="section-heading" id="mortgage-lender-directory-listing-headline">{{.headline}}</h2>
    {{if .subheadline}}<p class="section-subheadline" id="mortgage-lender-directory-listing-subheadline">{{.subheadline}}</p>{{end}}
    <div class="findir-grid" id="mortgage-lender-directory-listing-container">
      {{if .entries}}{{range .entries}}
      <article class="findir-card"><div class="findir-card-content">
        <h3 class="findir-card-title">{{.name}}{{if .owner}} <span class="findir-card-owner">{{.owner}}</span>{{end}}</h3>
        {{if .summary}}<p class="findir-card-summary">{{.summary}}</p>{{end}}
        {{if .claims}}<ul class="findir-card-claims">
          {{range .claims}}<li><span class="findir-claim-field">{{.field}}</span> <span class="findir-claim-value">{{.value}}{{if .unit}} {{.unit}}{{end}}</span>{{if .url}} <a href="{{.url}}" target="_blank" rel="noopener noreferrer" class="findir-claim-source">source</a>{{end}}</li>{{end}}
        </ul>{{end}}
      </div></article>
      {{end}}{{else}}<noscript>
        <p class="findir-empty">Enable JavaScript to see this directory.</p>
      </noscript>{{end}}
    </div>
    <div id="mortgage-lender-directory-listing-footer"></div>
  </div>
</section>
<script src="/tools/assets/mortgage-lender-directory-listing.js"></script>$html$,
    $js$(function() {
  function el(tag, opts) {
    var e = document.createElement(tag);
    opts = opts || {};
    if (opts.className) e.className = opts.className;
    if (opts.text) e.textContent = opts.text;
    if (opts.href) { e.href = opts.href; e.target = "_blank"; e.rel = "noopener noreferrer"; }
    return e;
  }
  function renderCard(entry) {
    var card = el("article", {className: "findir-card"});
    var content = el("div", {className: "findir-card-content"});
    var title = el("h3", {className: "findir-card-title", text: entry.name || ""});
    if (entry.owner && entry.owner !== entry.name) {
      title.appendChild(el("span", {className: "findir-card-owner", text: " " + entry.owner}));
    }
    content.appendChild(title);
    if (entry.summary) {
      content.appendChild(el("p", {className: "findir-card-summary", text: entry.summary}));
    }
    if (entry.claims && entry.claims.length > 0) {
      var list = document.createElement("ul");
      list.className = "findir-card-claims";
      entry.claims.forEach(function(c) {
        var li = document.createElement("li");
        li.appendChild(el("span", {className: "findir-claim-field", text: (c.field || "").split("_").join(" ")}));
        li.appendChild(document.createTextNode(" "));
        var valueText = c.value || "";
        if (c.unit) valueText += " " + c.unit;
        li.appendChild(el("span", {className: "findir-claim-value", text: valueText}));
        if (c.url) {
          li.appendChild(document.createTextNode(" "));
          li.appendChild(el("a", {className: "findir-claim-source", text: "source", href: c.url}));
        }
        list.appendChild(li);
      });
      content.appendChild(list);
    }
    card.appendChild(content);
    return card;
  }
  fetch("/data/mortgage-lender-directory-full.json")
    .then(function(r) { return r.json(); })
    .then(function(data) {
      var headlineEl = document.getElementById("mortgage-lender-directory-listing-headline");
      if (headlineEl && data.headline) headlineEl.textContent = data.headline;
      var container = document.getElementById("mortgage-lender-directory-listing-container");
      if (container && data.entries && data.entries.length > 0) {
        container.innerHTML = "";
        data.entries.forEach(function(entry) { container.appendChild(renderCard(entry)); });
      }
      var footer = document.getElementById("mortgage-lender-directory-listing-footer");
      if (footer && data.directory_url) {
        footer.innerHTML = "";
        var wrap = document.createElement("div");
        wrap.className = "findir-section-footer";
        var link = el("a", {className: "findir-more-link", text: data.directory_label || "Browse the full directory"});
        link.href = data.directory_url;
        wrap.appendChild(link);
        footer.appendChild(wrap);
      }
    })
    .catch(function() {});
})();$js$
WHERE NOT EXISTS (SELECT 1 FROM content_components WHERE function = 'mortgage-lender-directory-listing');

-- ═══════════════════════════════════════════════════════════════════════════
-- savings-provider-directory (homepage snippet, kind=savings-provider)
-- ═══════════════════════════════════════════════════════════════════════════
INSERT INTO content_components (
    name, display_name, description, function, category, component_level,
    section_type, render_mode, suitable_site_types, suitable_page_types,
    created_from, input_schema, html_template, js_content
)
SELECT
    'UK Savings Provider Directory', 'Savings Provider Directory', 'Homepage snippet: cited directory of UK savings providers (regulator status, product types, protection scheme — non-price facts only), server-rendered from query.savings_provider_directory, refreshed client-side from data/savings-provider-directory.json',
    'savings-provider-directory', 'content', 'section', 'savings-provider-directory', 'template',
    '["brochure"]'::jsonb, '[]'::jsonb, 'manual',
    $schema${
  "notes": "entries are server-rendered from query.savings_provider_directory (Phase B, DIR-001); savings-provider-directory.js refreshes client-side from data/savings-provider-directory.json. Resolver output is pre-escaped for the template; the JSON path is raw text, escaped client-side via textContent/createElement — never innerHTML string-building (researched third-party text). NON-PRICE facts only: the closed per-kind field vocabulary is enforced at registration (financeKindFieldAllowlist), so no price-shaped claim can reach these cards.",
  "fields": {
    "entries": {
      "type": "array",
      "items": {
        "slug": {"type": "text"}, "name": {"type": "text"}, "owner": {"type": "text"},
        "summary": {"type": "text"}, "claims": {"type": "array"},
        "docs_url": {"type": "url"}, "video_urls": {"type": "array"}
      },
      "limit": 12,
      "source": "query.savings_provider_directory",
      "required": false,
      "on_missing": "skip_field"
    },
    "headline": {
      "type": "text", "source": "llm", "default": "UK savings providers, with cited facts", "required": true,
      "description": "Section heading — generated by content writer, tailored to site identity"
    },
    "subheadline": {
      "type": "text", "source": "llm", "required": false,
      "description": "One honest sentence on what this directory is: named UK providers, every fact cited to its source. Never mention rates — the directory carries none by design. May carry the honesty clause: a citation proves where a fact came from, not that it is correct."
    }
  },
  "data_source": "/data/savings-provider-directory.json",
  "render_action": "render_directory",
  "refresh_interval": "6h"
}$schema$::jsonb,
    $html$<style>
.findir-section { padding: var(--spacing-section, 4rem 0); }
.findir-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 1.5rem;
    margin-top: 2rem;
}
.findir-card {
    border: 1px solid var(--section-border, var(--color-border, rgba(0,0,0,0.12)));
    border-radius: 8px;
    background: var(--section-surface, var(--color-surface, rgba(0,0,0,0.02)));
    overflow: hidden;
    transition: transform 0.2s, box-shadow 0.2s;
}
.findir-card:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(0,0,0,0.08); }
.findir-card-content { padding: 1.25rem 1.5rem 1.5rem; }
.findir-card-title {
    margin: 0 0 0.5rem;
    font-size: 1.15rem;
    line-height: 1.3;
    color: var(--section-heading, var(--color-heading, inherit));
}
.findir-card-owner {
    display: block; font-size: 0.8rem; font-weight: 500;
    letter-spacing: 0.04em; text-transform: uppercase; opacity: 0.65; margin-top: 0.25rem;
}
.findir-card-summary { margin: 0 0 1rem; font-size: 0.95rem; line-height: 1.55; color: var(--section-text, inherit); }
.findir-card-claims {
    list-style: none; margin: 0 0 0.5rem; padding: 0;
    border-top: 1px solid var(--section-border, rgba(0,0,0,0.08));
}
.findir-card-claims li {
    display: flex; flex-wrap: wrap; align-items: baseline; gap: 0.4rem;
    padding: 0.5rem 0; border-bottom: 1px solid var(--section-border, rgba(0,0,0,0.08));
    font-size: 0.9rem;
}
.findir-claim-field { flex: 1 1 45%; opacity: 0.7; text-transform: capitalize; }
.findir-claim-value { font-weight: 600; }
.findir-claim-source {
    font-size: 0.75rem; text-decoration: none; opacity: 0.6;
    border-bottom: 1px dotted currentColor;
}
.findir-claim-source:hover { opacity: 1; }
.findir-section-footer { margin-top: 2rem; text-align: center; }
.findir-more-link {
    display: inline-block; font-weight: 600; text-decoration: none;
    color: var(--color-primary, #1e40af);
}
.findir-more-link:hover { text-decoration: underline; }
.findir-empty { opacity: 0.7; }
@media (max-width: 600px) { .findir-grid { grid-template-columns: 1fr; } }
</style>
<!-- savings-provider-directory component -->
<section data-component="savings-provider-directory" class="findir-section section-padding">
  <div class="container">
    <h2 class="section-heading" id="savings-provider-directory-headline">{{.headline}}</h2>
    {{if .subheadline}}<p class="section-subheadline" id="savings-provider-directory-subheadline">{{.subheadline}}</p>{{end}}
    <div class="findir-grid" id="savings-provider-directory-container">
      {{if .entries}}{{range .entries}}
      <article class="findir-card"><div class="findir-card-content">
        <h3 class="findir-card-title">{{.name}}{{if .owner}} <span class="findir-card-owner">{{.owner}}</span>{{end}}</h3>
        {{if .summary}}<p class="findir-card-summary">{{.summary}}</p>{{end}}
        {{if .claims}}<ul class="findir-card-claims">
          {{range .claims}}<li><span class="findir-claim-field">{{.field}}</span> <span class="findir-claim-value">{{.value}}{{if .unit}} {{.unit}}{{end}}</span>{{if .url}} <a href="{{.url}}" target="_blank" rel="noopener noreferrer" class="findir-claim-source">source</a>{{end}}</li>{{end}}
        </ul>{{end}}
      </div></article>
      {{end}}{{else}}<noscript>
        <p class="findir-empty">Enable JavaScript to see this directory.</p>
      </noscript>{{end}}
    </div>
    <div id="savings-provider-directory-footer"></div>
  </div>
</section>
<script src="/tools/assets/savings-provider-directory.js"></script>$html$,
    $js$(function() {
  function el(tag, opts) {
    var e = document.createElement(tag);
    opts = opts || {};
    if (opts.className) e.className = opts.className;
    if (opts.text) e.textContent = opts.text;
    if (opts.href) { e.href = opts.href; e.target = "_blank"; e.rel = "noopener noreferrer"; }
    return e;
  }
  function renderCard(entry) {
    var card = el("article", {className: "findir-card"});
    var content = el("div", {className: "findir-card-content"});
    var title = el("h3", {className: "findir-card-title", text: entry.name || ""});
    if (entry.owner && entry.owner !== entry.name) {
      title.appendChild(el("span", {className: "findir-card-owner", text: " " + entry.owner}));
    }
    content.appendChild(title);
    if (entry.summary) {
      content.appendChild(el("p", {className: "findir-card-summary", text: entry.summary}));
    }
    if (entry.claims && entry.claims.length > 0) {
      var list = document.createElement("ul");
      list.className = "findir-card-claims";
      entry.claims.forEach(function(c) {
        var li = document.createElement("li");
        li.appendChild(el("span", {className: "findir-claim-field", text: (c.field || "").split("_").join(" ")}));
        li.appendChild(document.createTextNode(" "));
        var valueText = c.value || "";
        if (c.unit) valueText += " " + c.unit;
        li.appendChild(el("span", {className: "findir-claim-value", text: valueText}));
        if (c.url) {
          li.appendChild(document.createTextNode(" "));
          li.appendChild(el("a", {className: "findir-claim-source", text: "source", href: c.url}));
        }
        list.appendChild(li);
      });
      content.appendChild(list);
    }
    card.appendChild(content);
    return card;
  }
  fetch("/data/savings-provider-directory.json")
    .then(function(r) { return r.json(); })
    .then(function(data) {
      var headlineEl = document.getElementById("savings-provider-directory-headline");
      if (headlineEl && data.headline) headlineEl.textContent = data.headline;
      var container = document.getElementById("savings-provider-directory-container");
      if (container && data.entries && data.entries.length > 0) {
        container.innerHTML = "";
        data.entries.forEach(function(entry) { container.appendChild(renderCard(entry)); });
      }
      var footer = document.getElementById("savings-provider-directory-footer");
      if (footer && data.directory_url) {
        footer.innerHTML = "";
        var wrap = document.createElement("div");
        wrap.className = "findir-section-footer";
        var link = el("a", {className: "findir-more-link", text: data.directory_label || "Browse the full directory"});
        link.href = data.directory_url;
        wrap.appendChild(link);
        footer.appendChild(wrap);
      }
    })
    .catch(function() {});
})();$js$
WHERE NOT EXISTS (SELECT 1 FROM content_components WHERE function = 'savings-provider-directory');

-- ═══════════════════════════════════════════════════════════════════════════
-- savings-provider-directory-listing (dedicated page, kind=savings-provider, full depth)
-- ═══════════════════════════════════════════════════════════════════════════
INSERT INTO content_components (
    name, display_name, description, function, category, component_level,
    section_type, render_mode, suitable_site_types, suitable_page_types,
    created_from, input_schema, html_template, js_content
)
SELECT
    'UK Savings Provider Directory (full listing)', 'Savings Provider Directory — Full Listing', 'Dedicated savings-providers page: every listed UK provider with its cited non-price facts, server-rendered from query.savings_provider_directory_full, refreshed client-side from data/savings-provider-directory-full.json',
    'savings-provider-directory-listing', 'content', 'section', 'savings-provider-directory-listing', 'template',
    '["brochure"]'::jsonb, '["savings-providers"]'::jsonb, 'manual',
    $schema${
  "notes": "entries are server-rendered from query.savings_provider_directory_full (Phase B, DIR-001); savings-provider-directory-listing.js refreshes client-side from data/savings-provider-directory-full.json. Resolver output is pre-escaped for the template; the JSON path is raw text, escaped client-side via textContent/createElement — never innerHTML string-building (researched third-party text). NON-PRICE facts only: the closed per-kind field vocabulary is enforced at registration (financeKindFieldAllowlist), so no price-shaped claim can reach these cards.",
  "fields": {
    "entries": {
      "type": "array",
      "items": {
        "slug": {"type": "text"}, "name": {"type": "text"}, "owner": {"type": "text"},
        "summary": {"type": "text"}, "claims": {"type": "array"},
        "docs_url": {"type": "url"}, "video_urls": {"type": "array"}
      },
      "limit": 50,
      "source": "query.savings_provider_directory_full",
      "required": false,
      "on_missing": "skip_field"
    },
    "headline": {
      "type": "text", "source": "llm", "default": "UK savings providers, with cited facts", "required": true,
      "description": "Section heading — generated by content writer, tailored to site identity"
    },
    "subheadline": {
      "type": "text", "source": "llm", "required": false,
      "description": "One honest sentence on what this directory is: named UK providers, every fact cited to its source. Never mention rates — the directory carries none by design. May carry the honesty clause: a citation proves where a fact came from, not that it is correct."
    }
  },
  "data_source": "/data/savings-provider-directory-full.json",
  "render_action": "render_directory",
  "refresh_interval": "6h"
}$schema$::jsonb,
    $html$<style>
.findir-section { padding: var(--spacing-section, 4rem 0); }
.findir-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 1.5rem;
    margin-top: 2rem;
}
.findir-card {
    border: 1px solid var(--section-border, var(--color-border, rgba(0,0,0,0.12)));
    border-radius: 8px;
    background: var(--section-surface, var(--color-surface, rgba(0,0,0,0.02)));
    overflow: hidden;
    transition: transform 0.2s, box-shadow 0.2s;
}
.findir-card:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(0,0,0,0.08); }
.findir-card-content { padding: 1.25rem 1.5rem 1.5rem; }
.findir-card-title {
    margin: 0 0 0.5rem;
    font-size: 1.15rem;
    line-height: 1.3;
    color: var(--section-heading, var(--color-heading, inherit));
}
.findir-card-owner {
    display: block; font-size: 0.8rem; font-weight: 500;
    letter-spacing: 0.04em; text-transform: uppercase; opacity: 0.65; margin-top: 0.25rem;
}
.findir-card-summary { margin: 0 0 1rem; font-size: 0.95rem; line-height: 1.55; color: var(--section-text, inherit); }
.findir-card-claims {
    list-style: none; margin: 0 0 0.5rem; padding: 0;
    border-top: 1px solid var(--section-border, rgba(0,0,0,0.08));
}
.findir-card-claims li {
    display: flex; flex-wrap: wrap; align-items: baseline; gap: 0.4rem;
    padding: 0.5rem 0; border-bottom: 1px solid var(--section-border, rgba(0,0,0,0.08));
    font-size: 0.9rem;
}
.findir-claim-field { flex: 1 1 45%; opacity: 0.7; text-transform: capitalize; }
.findir-claim-value { font-weight: 600; }
.findir-claim-source {
    font-size: 0.75rem; text-decoration: none; opacity: 0.6;
    border-bottom: 1px dotted currentColor;
}
.findir-claim-source:hover { opacity: 1; }
.findir-section-footer { margin-top: 2rem; text-align: center; }
.findir-more-link {
    display: inline-block; font-weight: 600; text-decoration: none;
    color: var(--color-primary, #1e40af);
}
.findir-more-link:hover { text-decoration: underline; }
.findir-empty { opacity: 0.7; }
@media (max-width: 600px) { .findir-grid { grid-template-columns: 1fr; } }
</style>
<!-- savings-provider-directory-listing component -->
<section data-component="savings-provider-directory-listing" class="findir-section section-padding">
  <div class="container">
    <h2 class="section-heading" id="savings-provider-directory-listing-headline">{{.headline}}</h2>
    {{if .subheadline}}<p class="section-subheadline" id="savings-provider-directory-listing-subheadline">{{.subheadline}}</p>{{end}}
    <div class="findir-grid" id="savings-provider-directory-listing-container">
      {{if .entries}}{{range .entries}}
      <article class="findir-card"><div class="findir-card-content">
        <h3 class="findir-card-title">{{.name}}{{if .owner}} <span class="findir-card-owner">{{.owner}}</span>{{end}}</h3>
        {{if .summary}}<p class="findir-card-summary">{{.summary}}</p>{{end}}
        {{if .claims}}<ul class="findir-card-claims">
          {{range .claims}}<li><span class="findir-claim-field">{{.field}}</span> <span class="findir-claim-value">{{.value}}{{if .unit}} {{.unit}}{{end}}</span>{{if .url}} <a href="{{.url}}" target="_blank" rel="noopener noreferrer" class="findir-claim-source">source</a>{{end}}</li>{{end}}
        </ul>{{end}}
      </div></article>
      {{end}}{{else}}<noscript>
        <p class="findir-empty">Enable JavaScript to see this directory.</p>
      </noscript>{{end}}
    </div>
    <div id="savings-provider-directory-listing-footer"></div>
  </div>
</section>
<script src="/tools/assets/savings-provider-directory-listing.js"></script>$html$,
    $js$(function() {
  function el(tag, opts) {
    var e = document.createElement(tag);
    opts = opts || {};
    if (opts.className) e.className = opts.className;
    if (opts.text) e.textContent = opts.text;
    if (opts.href) { e.href = opts.href; e.target = "_blank"; e.rel = "noopener noreferrer"; }
    return e;
  }
  function renderCard(entry) {
    var card = el("article", {className: "findir-card"});
    var content = el("div", {className: "findir-card-content"});
    var title = el("h3", {className: "findir-card-title", text: entry.name || ""});
    if (entry.owner && entry.owner !== entry.name) {
      title.appendChild(el("span", {className: "findir-card-owner", text: " " + entry.owner}));
    }
    content.appendChild(title);
    if (entry.summary) {
      content.appendChild(el("p", {className: "findir-card-summary", text: entry.summary}));
    }
    if (entry.claims && entry.claims.length > 0) {
      var list = document.createElement("ul");
      list.className = "findir-card-claims";
      entry.claims.forEach(function(c) {
        var li = document.createElement("li");
        li.appendChild(el("span", {className: "findir-claim-field", text: (c.field || "").split("_").join(" ")}));
        li.appendChild(document.createTextNode(" "));
        var valueText = c.value || "";
        if (c.unit) valueText += " " + c.unit;
        li.appendChild(el("span", {className: "findir-claim-value", text: valueText}));
        if (c.url) {
          li.appendChild(document.createTextNode(" "));
          li.appendChild(el("a", {className: "findir-claim-source", text: "source", href: c.url}));
        }
        list.appendChild(li);
      });
      content.appendChild(list);
    }
    card.appendChild(content);
    return card;
  }
  fetch("/data/savings-provider-directory-full.json")
    .then(function(r) { return r.json(); })
    .then(function(data) {
      var headlineEl = document.getElementById("savings-provider-directory-listing-headline");
      if (headlineEl && data.headline) headlineEl.textContent = data.headline;
      var container = document.getElementById("savings-provider-directory-listing-container");
      if (container && data.entries && data.entries.length > 0) {
        container.innerHTML = "";
        data.entries.forEach(function(entry) { container.appendChild(renderCard(entry)); });
      }
      var footer = document.getElementById("savings-provider-directory-listing-footer");
      if (footer && data.directory_url) {
        footer.innerHTML = "";
        var wrap = document.createElement("div");
        wrap.className = "findir-section-footer";
        var link = el("a", {className: "findir-more-link", text: data.directory_label || "Browse the full directory"});
        link.href = data.directory_url;
        wrap.appendChild(link);
        footer.appendChild(wrap);
      }
    })
    .catch(function() {});
})();$js$
WHERE NOT EXISTS (SELECT 1 FROM content_components WHERE function = 'savings-provider-directory-listing');

-- ═══════════════════════════════════════════════════════════════════════════
-- health-insurer-directory (homepage snippet, kind=health-insurer)
-- ═══════════════════════════════════════════════════════════════════════════
INSERT INTO content_components (
    name, display_name, description, function, category, component_level,
    section_type, render_mode, suitable_site_types, suitable_page_types,
    created_from, input_schema, html_template, js_content
)
SELECT
    'UK Health Insurer Directory', 'Health Insurer Directory', 'Homepage snippet: cited directory of UK health insurers (regulator status, cover types, underwriter — non-price facts only), server-rendered from query.health_insurer_directory, refreshed client-side from data/health-insurer-directory.json',
    'health-insurer-directory', 'content', 'section', 'health-insurer-directory', 'template',
    '["brochure"]'::jsonb, '[]'::jsonb, 'manual',
    $schema${
  "notes": "entries are server-rendered from query.health_insurer_directory (Phase B, DIR-001); health-insurer-directory.js refreshes client-side from data/health-insurer-directory.json. Resolver output is pre-escaped for the template; the JSON path is raw text, escaped client-side via textContent/createElement — never innerHTML string-building (researched third-party text). NON-PRICE facts only: the closed per-kind field vocabulary is enforced at registration (financeKindFieldAllowlist), so no price-shaped claim can reach these cards.",
  "fields": {
    "entries": {
      "type": "array",
      "items": {
        "slug": {"type": "text"}, "name": {"type": "text"}, "owner": {"type": "text"},
        "summary": {"type": "text"}, "claims": {"type": "array"},
        "docs_url": {"type": "url"}, "video_urls": {"type": "array"}
      },
      "limit": 12,
      "source": "query.health_insurer_directory",
      "required": false,
      "on_missing": "skip_field"
    },
    "headline": {
      "type": "text", "source": "llm", "default": "UK health insurers, with cited facts", "required": true,
      "description": "Section heading — generated by content writer, tailored to site identity"
    },
    "subheadline": {
      "type": "text", "source": "llm", "required": false,
      "description": "One honest sentence on what this directory is: named UK insurers, every fact cited to its source. Never mention premiums — the directory carries none by design. May carry the honesty clause: a citation proves where a fact came from, not that it is correct."
    }
  },
  "data_source": "/data/health-insurer-directory.json",
  "render_action": "render_directory",
  "refresh_interval": "6h"
}$schema$::jsonb,
    $html$<style>
.findir-section { padding: var(--spacing-section, 4rem 0); }
.findir-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 1.5rem;
    margin-top: 2rem;
}
.findir-card {
    border: 1px solid var(--section-border, var(--color-border, rgba(0,0,0,0.12)));
    border-radius: 8px;
    background: var(--section-surface, var(--color-surface, rgba(0,0,0,0.02)));
    overflow: hidden;
    transition: transform 0.2s, box-shadow 0.2s;
}
.findir-card:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(0,0,0,0.08); }
.findir-card-content { padding: 1.25rem 1.5rem 1.5rem; }
.findir-card-title {
    margin: 0 0 0.5rem;
    font-size: 1.15rem;
    line-height: 1.3;
    color: var(--section-heading, var(--color-heading, inherit));
}
.findir-card-owner {
    display: block; font-size: 0.8rem; font-weight: 500;
    letter-spacing: 0.04em; text-transform: uppercase; opacity: 0.65; margin-top: 0.25rem;
}
.findir-card-summary { margin: 0 0 1rem; font-size: 0.95rem; line-height: 1.55; color: var(--section-text, inherit); }
.findir-card-claims {
    list-style: none; margin: 0 0 0.5rem; padding: 0;
    border-top: 1px solid var(--section-border, rgba(0,0,0,0.08));
}
.findir-card-claims li {
    display: flex; flex-wrap: wrap; align-items: baseline; gap: 0.4rem;
    padding: 0.5rem 0; border-bottom: 1px solid var(--section-border, rgba(0,0,0,0.08));
    font-size: 0.9rem;
}
.findir-claim-field { flex: 1 1 45%; opacity: 0.7; text-transform: capitalize; }
.findir-claim-value { font-weight: 600; }
.findir-claim-source {
    font-size: 0.75rem; text-decoration: none; opacity: 0.6;
    border-bottom: 1px dotted currentColor;
}
.findir-claim-source:hover { opacity: 1; }
.findir-section-footer { margin-top: 2rem; text-align: center; }
.findir-more-link {
    display: inline-block; font-weight: 600; text-decoration: none;
    color: var(--color-primary, #1e40af);
}
.findir-more-link:hover { text-decoration: underline; }
.findir-empty { opacity: 0.7; }
@media (max-width: 600px) { .findir-grid { grid-template-columns: 1fr; } }
</style>
<!-- health-insurer-directory component -->
<section data-component="health-insurer-directory" class="findir-section section-padding">
  <div class="container">
    <h2 class="section-heading" id="health-insurer-directory-headline">{{.headline}}</h2>
    {{if .subheadline}}<p class="section-subheadline" id="health-insurer-directory-subheadline">{{.subheadline}}</p>{{end}}
    <div class="findir-grid" id="health-insurer-directory-container">
      {{if .entries}}{{range .entries}}
      <article class="findir-card"><div class="findir-card-content">
        <h3 class="findir-card-title">{{.name}}{{if .owner}} <span class="findir-card-owner">{{.owner}}</span>{{end}}</h3>
        {{if .summary}}<p class="findir-card-summary">{{.summary}}</p>{{end}}
        {{if .claims}}<ul class="findir-card-claims">
          {{range .claims}}<li><span class="findir-claim-field">{{.field}}</span> <span class="findir-claim-value">{{.value}}{{if .unit}} {{.unit}}{{end}}</span>{{if .url}} <a href="{{.url}}" target="_blank" rel="noopener noreferrer" class="findir-claim-source">source</a>{{end}}</li>{{end}}
        </ul>{{end}}
      </div></article>
      {{end}}{{else}}<noscript>
        <p class="findir-empty">Enable JavaScript to see this directory.</p>
      </noscript>{{end}}
    </div>
    <div id="health-insurer-directory-footer"></div>
  </div>
</section>
<script src="/tools/assets/health-insurer-directory.js"></script>$html$,
    $js$(function() {
  function el(tag, opts) {
    var e = document.createElement(tag);
    opts = opts || {};
    if (opts.className) e.className = opts.className;
    if (opts.text) e.textContent = opts.text;
    if (opts.href) { e.href = opts.href; e.target = "_blank"; e.rel = "noopener noreferrer"; }
    return e;
  }
  function renderCard(entry) {
    var card = el("article", {className: "findir-card"});
    var content = el("div", {className: "findir-card-content"});
    var title = el("h3", {className: "findir-card-title", text: entry.name || ""});
    if (entry.owner && entry.owner !== entry.name) {
      title.appendChild(el("span", {className: "findir-card-owner", text: " " + entry.owner}));
    }
    content.appendChild(title);
    if (entry.summary) {
      content.appendChild(el("p", {className: "findir-card-summary", text: entry.summary}));
    }
    if (entry.claims && entry.claims.length > 0) {
      var list = document.createElement("ul");
      list.className = "findir-card-claims";
      entry.claims.forEach(function(c) {
        var li = document.createElement("li");
        li.appendChild(el("span", {className: "findir-claim-field", text: (c.field || "").split("_").join(" ")}));
        li.appendChild(document.createTextNode(" "));
        var valueText = c.value || "";
        if (c.unit) valueText += " " + c.unit;
        li.appendChild(el("span", {className: "findir-claim-value", text: valueText}));
        if (c.url) {
          li.appendChild(document.createTextNode(" "));
          li.appendChild(el("a", {className: "findir-claim-source", text: "source", href: c.url}));
        }
        list.appendChild(li);
      });
      content.appendChild(list);
    }
    card.appendChild(content);
    return card;
  }
  fetch("/data/health-insurer-directory.json")
    .then(function(r) { return r.json(); })
    .then(function(data) {
      var headlineEl = document.getElementById("health-insurer-directory-headline");
      if (headlineEl && data.headline) headlineEl.textContent = data.headline;
      var container = document.getElementById("health-insurer-directory-container");
      if (container && data.entries && data.entries.length > 0) {
        container.innerHTML = "";
        data.entries.forEach(function(entry) { container.appendChild(renderCard(entry)); });
      }
      var footer = document.getElementById("health-insurer-directory-footer");
      if (footer && data.directory_url) {
        footer.innerHTML = "";
        var wrap = document.createElement("div");
        wrap.className = "findir-section-footer";
        var link = el("a", {className: "findir-more-link", text: data.directory_label || "Browse the full directory"});
        link.href = data.directory_url;
        wrap.appendChild(link);
        footer.appendChild(wrap);
      }
    })
    .catch(function() {});
})();$js$
WHERE NOT EXISTS (SELECT 1 FROM content_components WHERE function = 'health-insurer-directory');

-- ═══════════════════════════════════════════════════════════════════════════
-- health-insurer-directory-listing (dedicated page, kind=health-insurer, full depth)
-- ═══════════════════════════════════════════════════════════════════════════
INSERT INTO content_components (
    name, display_name, description, function, category, component_level,
    section_type, render_mode, suitable_site_types, suitable_page_types,
    created_from, input_schema, html_template, js_content
)
SELECT
    'UK Health Insurer Directory (full listing)', 'Health Insurer Directory — Full Listing', 'Dedicated health-insurers page: every listed UK insurer with its cited non-price facts, server-rendered from query.health_insurer_directory_full, refreshed client-side from data/health-insurer-directory-full.json',
    'health-insurer-directory-listing', 'content', 'section', 'health-insurer-directory-listing', 'template',
    '["brochure"]'::jsonb, '["health-insurers"]'::jsonb, 'manual',
    $schema${
  "notes": "entries are server-rendered from query.health_insurer_directory_full (Phase B, DIR-001); health-insurer-directory-listing.js refreshes client-side from data/health-insurer-directory-full.json. Resolver output is pre-escaped for the template; the JSON path is raw text, escaped client-side via textContent/createElement — never innerHTML string-building (researched third-party text). NON-PRICE facts only: the closed per-kind field vocabulary is enforced at registration (financeKindFieldAllowlist), so no price-shaped claim can reach these cards.",
  "fields": {
    "entries": {
      "type": "array",
      "items": {
        "slug": {"type": "text"}, "name": {"type": "text"}, "owner": {"type": "text"},
        "summary": {"type": "text"}, "claims": {"type": "array"},
        "docs_url": {"type": "url"}, "video_urls": {"type": "array"}
      },
      "limit": 50,
      "source": "query.health_insurer_directory_full",
      "required": false,
      "on_missing": "skip_field"
    },
    "headline": {
      "type": "text", "source": "llm", "default": "UK health insurers, with cited facts", "required": true,
      "description": "Section heading — generated by content writer, tailored to site identity"
    },
    "subheadline": {
      "type": "text", "source": "llm", "required": false,
      "description": "One honest sentence on what this directory is: named UK insurers, every fact cited to its source. Never mention premiums — the directory carries none by design. May carry the honesty clause: a citation proves where a fact came from, not that it is correct."
    }
  },
  "data_source": "/data/health-insurer-directory-full.json",
  "render_action": "render_directory",
  "refresh_interval": "6h"
}$schema$::jsonb,
    $html$<style>
.findir-section { padding: var(--spacing-section, 4rem 0); }
.findir-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 1.5rem;
    margin-top: 2rem;
}
.findir-card {
    border: 1px solid var(--section-border, var(--color-border, rgba(0,0,0,0.12)));
    border-radius: 8px;
    background: var(--section-surface, var(--color-surface, rgba(0,0,0,0.02)));
    overflow: hidden;
    transition: transform 0.2s, box-shadow 0.2s;
}
.findir-card:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(0,0,0,0.08); }
.findir-card-content { padding: 1.25rem 1.5rem 1.5rem; }
.findir-card-title {
    margin: 0 0 0.5rem;
    font-size: 1.15rem;
    line-height: 1.3;
    color: var(--section-heading, var(--color-heading, inherit));
}
.findir-card-owner {
    display: block; font-size: 0.8rem; font-weight: 500;
    letter-spacing: 0.04em; text-transform: uppercase; opacity: 0.65; margin-top: 0.25rem;
}
.findir-card-summary { margin: 0 0 1rem; font-size: 0.95rem; line-height: 1.55; color: var(--section-text, inherit); }
.findir-card-claims {
    list-style: none; margin: 0 0 0.5rem; padding: 0;
    border-top: 1px solid var(--section-border, rgba(0,0,0,0.08));
}
.findir-card-claims li {
    display: flex; flex-wrap: wrap; align-items: baseline; gap: 0.4rem;
    padding: 0.5rem 0; border-bottom: 1px solid var(--section-border, rgba(0,0,0,0.08));
    font-size: 0.9rem;
}
.findir-claim-field { flex: 1 1 45%; opacity: 0.7; text-transform: capitalize; }
.findir-claim-value { font-weight: 600; }
.findir-claim-source {
    font-size: 0.75rem; text-decoration: none; opacity: 0.6;
    border-bottom: 1px dotted currentColor;
}
.findir-claim-source:hover { opacity: 1; }
.findir-section-footer { margin-top: 2rem; text-align: center; }
.findir-more-link {
    display: inline-block; font-weight: 600; text-decoration: none;
    color: var(--color-primary, #1e40af);
}
.findir-more-link:hover { text-decoration: underline; }
.findir-empty { opacity: 0.7; }
@media (max-width: 600px) { .findir-grid { grid-template-columns: 1fr; } }
</style>
<!-- health-insurer-directory-listing component -->
<section data-component="health-insurer-directory-listing" class="findir-section section-padding">
  <div class="container">
    <h2 class="section-heading" id="health-insurer-directory-listing-headline">{{.headline}}</h2>
    {{if .subheadline}}<p class="section-subheadline" id="health-insurer-directory-listing-subheadline">{{.subheadline}}</p>{{end}}
    <div class="findir-grid" id="health-insurer-directory-listing-container">
      {{if .entries}}{{range .entries}}
      <article class="findir-card"><div class="findir-card-content">
        <h3 class="findir-card-title">{{.name}}{{if .owner}} <span class="findir-card-owner">{{.owner}}</span>{{end}}</h3>
        {{if .summary}}<p class="findir-card-summary">{{.summary}}</p>{{end}}
        {{if .claims}}<ul class="findir-card-claims">
          {{range .claims}}<li><span class="findir-claim-field">{{.field}}</span> <span class="findir-claim-value">{{.value}}{{if .unit}} {{.unit}}{{end}}</span>{{if .url}} <a href="{{.url}}" target="_blank" rel="noopener noreferrer" class="findir-claim-source">source</a>{{end}}</li>{{end}}
        </ul>{{end}}
      </div></article>
      {{end}}{{else}}<noscript>
        <p class="findir-empty">Enable JavaScript to see this directory.</p>
      </noscript>{{end}}
    </div>
    <div id="health-insurer-directory-listing-footer"></div>
  </div>
</section>
<script src="/tools/assets/health-insurer-directory-listing.js"></script>$html$,
    $js$(function() {
  function el(tag, opts) {
    var e = document.createElement(tag);
    opts = opts || {};
    if (opts.className) e.className = opts.className;
    if (opts.text) e.textContent = opts.text;
    if (opts.href) { e.href = opts.href; e.target = "_blank"; e.rel = "noopener noreferrer"; }
    return e;
  }
  function renderCard(entry) {
    var card = el("article", {className: "findir-card"});
    var content = el("div", {className: "findir-card-content"});
    var title = el("h3", {className: "findir-card-title", text: entry.name || ""});
    if (entry.owner && entry.owner !== entry.name) {
      title.appendChild(el("span", {className: "findir-card-owner", text: " " + entry.owner}));
    }
    content.appendChild(title);
    if (entry.summary) {
      content.appendChild(el("p", {className: "findir-card-summary", text: entry.summary}));
    }
    if (entry.claims && entry.claims.length > 0) {
      var list = document.createElement("ul");
      list.className = "findir-card-claims";
      entry.claims.forEach(function(c) {
        var li = document.createElement("li");
        li.appendChild(el("span", {className: "findir-claim-field", text: (c.field || "").split("_").join(" ")}));
        li.appendChild(document.createTextNode(" "));
        var valueText = c.value || "";
        if (c.unit) valueText += " " + c.unit;
        li.appendChild(el("span", {className: "findir-claim-value", text: valueText}));
        if (c.url) {
          li.appendChild(document.createTextNode(" "));
          li.appendChild(el("a", {className: "findir-claim-source", text: "source", href: c.url}));
        }
        list.appendChild(li);
      });
      content.appendChild(list);
    }
    card.appendChild(content);
    return card;
  }
  fetch("/data/health-insurer-directory-full.json")
    .then(function(r) { return r.json(); })
    .then(function(data) {
      var headlineEl = document.getElementById("health-insurer-directory-listing-headline");
      if (headlineEl && data.headline) headlineEl.textContent = data.headline;
      var container = document.getElementById("health-insurer-directory-listing-container");
      if (container && data.entries && data.entries.length > 0) {
        container.innerHTML = "";
        data.entries.forEach(function(entry) { container.appendChild(renderCard(entry)); });
      }
      var footer = document.getElementById("health-insurer-directory-listing-footer");
      if (footer && data.directory_url) {
        footer.innerHTML = "";
        var wrap = document.createElement("div");
        wrap.className = "findir-section-footer";
        var link = el("a", {className: "findir-more-link", text: data.directory_label || "Browse the full directory"});
        link.href = data.directory_url;
        wrap.appendChild(link);
        footer.appendChild(wrap);
      }
    })
    .catch(function() {});
})();$js$
WHERE NOT EXISTS (SELECT 1 FROM content_components WHERE function = 'health-insurer-directory-listing');

COMMIT;

-- ── Post-apply verification ────────────────────────────────────────────────
--   SELECT function, component_level, section_type FROM content_components
--   WHERE function LIKE '%-directory%' AND function NOT LIKE 'model-%'
--   ORDER BY function;
-- Expect the six finance rows, all component_level='section'.
