apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-generator-adapter
spec:
  template:
    spec:
      serviceAccountName: ai-persona-app
      imagePullSecrets:
        - name: docker-hub-creds
      containers:
        - name: image-generator-adapter
          env:
            - name: KAFKA_BROKERS
              value: "personae-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"