# Default configuration - will be overridden by ConfigMap mount in Kubernetes
# This file is included in the Docker image as a fallback
server:
  http_port: 8080
  grpc_port: 9090
  shutdown_timeout: 5s

logger:
  level: "info"
  format: "json"

kafka:
  brokers: "${KAFKA_BROKERS:-localhost:9092}"  # Default to localhost, expects env var

# API configurations
# stability_api:
#   api_key: "${STABILITY_API_KEY}"