apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: personae-kafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/kraft: "enabled"
spec:
  kafka:
    version: 3.9.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      # Single-node compatible settings
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.9"
      log.retention.hours: 160
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
    resources:
      requests:
        memory: 512Mi
        cpu: 300m
      limits:
        memory: 1000Mi
        cpu: 500m
    # KRaft mode - no separate ZooKeeper needed
    metadataVersion: 3.9-IV4
  # No zookeeper section needed for KRaft
  entityOperator:
    topicOperator:
      reconciliationIntervalMs: 90000
    userOperator: {}