// FILE: platform/orchestration/actions/adopt_verbatim.go
//
// Byte-preserving adoption — the implementation behind `--fidelity locked`.
//
// The default adoption path (ApplyAdoptionPlanAction, sections 4-5) is a
// RECREATE: it canonicalises every page identity through
// datahelpers.CanonicalisePage, which synthesises a fresh URL
// (/tools/<slug>/index.html) and discards the one the crawl found, then marks
// each page mode:"recreate" and hands it to page-build-handler or
// tool-recreation-handler to be regenerated by an LLM. For a site adopted for
// its own sake — a hand-built site whose pages already work and whose URLs are
// already indexed and linked — both halves of that are wrong: the URLs break
// and the working pages are rewritten.
//
// doc 028 always described a fidelity dial (locked/high/medium/low/new) to
// express exactly this difference, and 082_submit_domain_unified.sh has always
// accepted --fidelity, recorded it in input_data, and said in its own NOTE that
// nothing read it. This file is the missing consumer of the `locked` setting.
//
// It is OPT-IN: absent fidelity=locked, ApplyAdoptionPlanAction behaves exactly
// as before. Nothing reaches this code path unless a submission asks for it.
//
// Row shapes follow cmd/webdesignport/import.go, which established the
// owned-page pattern (pages.rebuild_policy='owned' + a single 'ported-page'
// component). The difference is what is STORED in the component: webdesignport
// stores a body FRAGMENT and relies on the chassis assembling site chrome
// around it, whereas this stores the complete crawled document and marks it
// content_data.deploy_mode='verbatim' so RerenderSinglePageAction ships those
// bytes untouched. See the deploy_mode contract in that action.
package actions

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"html"
	"net/url"
	"path"
	"regexp"
	"sort"
	"strings"

	"github.com/google/uuid"
	"go.uber.org/zap"

	"github.com/gqls/agentchassis/platform/orchestration/datahelpers"
)

const (
	// fidelityLocked is the input_data.fidelity value selecting byte-preserving
	// adoption. Compared case-insensitively after trimming.
	fidelityLocked = "locked"

	// portedPageSlot is the page_components.slot_name owned pages use, shared
	// with cmd/webdesignport so both porters land in the same slot and a page
	// ported by either is recognised by the other.
	portedPageSlot = "ported-page"

	// deployModeVerbatim in a ported component's content_data tells
	// RerenderSinglePageAction to ship rendered_html byte-for-byte instead of
	// assembling chrome around it.
	deployModeVerbatim = "verbatim"
)

// adoptionFidelity reads input_data.fidelity from the orchestration envelope.
// Returns "" when unset, which means "behave as before".
func adoptionFidelity(collectedData map[string]interface{}) string {
	raw := datahelpers.ExtractNestedFieldString(collectedData, "input_data.fidelity")
	return strings.ToLower(strings.TrimSpace(raw))
}

var (
	// Regex rather than a DOM parse: this package does not otherwise depend on
	// an HTML parser, and both values are only used to populate pages.title /
	// pages.meta_description for listings. The page itself is stored and served
	// byte-for-byte either way, so a miss here costs a nicer title, not content.
	verbatimTitleRe = regexp.MustCompile(`(?is)<title[^>]*>(.*?)</title>`)
	verbatimMetaRe  = regexp.MustCompile(
		`(?is)<meta[^>]+name\s*=\s*["']description["'][^>]*content\s*=\s*["']([^"']*)["']`)
)

// extractHTMLTitle returns the document's <title> text, collapsed to one line.
func extractHTMLTitle(rawHTML string) string {
	m := verbatimTitleRe.FindStringSubmatch(rawHTML)
	if len(m) < 2 {
		return ""
	}
	return collapseWhitespace(html.UnescapeString(m[1]))
}

// extractHTMLMetaDescription returns the meta description, if the document has one.
func extractHTMLMetaDescription(rawHTML string) string {
	m := verbatimMetaRe.FindStringSubmatch(rawHTML)
	if len(m) < 2 {
		return ""
	}
	return collapseWhitespace(html.UnescapeString(m[1]))
}

func collapseWhitespace(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

// crawlPathIndex reduces the crawl index — which deliberately keys the same
// content under several aliases (absolute URL, path-only, sourceURL) so
// matchCrawlContent can find it however the plan spells a page — down to one
// entry per distinct PATH.
//
// Deduplication is by content pointer, not by string: buildCrawlPageIndex
// stores the identical *crawlPageContent under every alias for a page, so
// pointer identity is what actually distinguishes "two aliases of one page"
// from "two pages". Deduplicating by URL string instead would create a page per
// alias — three pages for every one crawled.
//
// Only entries carrying rawHtml are returned; a markdown-only entry cannot be
// preserved verbatim, and silently adopting it as an empty page would be worse
// than reporting it missing.
func crawlPathIndex(index map[string]*crawlPageContent) (map[string]*crawlPageContent, []string) {
	byPath := make(map[string]*crawlPageContent)
	seen := make(map[*crawlPageContent]string) // content -> chosen path
	var skipped []string

	// Sort the keys so the chosen alias for a page is deterministic across runs
	// (map iteration order is random; without this, re-running adoption could
	// pick a different alias and therefore a different pages.url).
	keys := make([]string, 0, len(index))
	for k := range index {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, key := range keys {
		content := index[key]
		if content == nil {
			continue
		}
		p, ok := urlToDeployPath(key)
		if !ok {
			continue
		}
		if content.RawHTML == "" {
			if _, already := seen[content]; !already {
				skipped = append(skipped, p)
				seen[content] = "" // remember so we report it once
			}
			continue
		}
		if chosen, already := seen[content]; already {
			// Same page under another alias. Prefer the shorter path — the
			// canonical form ("/a.html" over "/a.html?utm=x").
			if chosen != "" && len(p) >= len(chosen) {
				continue
			}
			delete(byPath, chosen)
		}
		byPath[p] = content
		seen[content] = p
	}
	return byPath, skipped
}

// urlToDeployPath turns a crawled URL or path into the path a static host
// serves it at.
//
// The homepage is the case that matters: a crawl reports the root as "/" or
// "https://host/", and storing pages.url="/" would be silently fatal —
// RerenderSinglePageAction derives the deploy filename as
// strings.TrimPrefix(url, "/"), so "/" yields an EMPTY filename and the commit
// would carry a file with no name. Directory paths therefore resolve to their
// index.html.
func urlToDeployPath(raw string) (string, bool) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return "", false
	}

	p := raw
	if strings.Contains(raw, "://") {
		u, err := url.Parse(raw)
		if err != nil {
			return "", false
		}
		p = u.Path
	} else if idx := strings.IndexAny(p, "?#"); idx >= 0 {
		p = p[:idx]
	}

	if p == "" || p == "/" {
		return "/index.html", true
	}
	if !strings.HasPrefix(p, "/") {
		p = "/" + p
	}
	// Strip query/fragment that survived a scheme-less input.
	if idx := strings.IndexAny(p, "?#"); idx >= 0 {
		p = p[:idx]
	}
	p = path.Clean(p)

	// A directory URL ("/guides/" or an extensionless "/guides") serves its
	// index.html.
	if strings.HasSuffix(raw, "/") || path.Ext(p) == "" {
		p = path.Join(p, "index.html")
	}
	if !strings.HasPrefix(p, "/") {
		p = "/" + p
	}
	return p, true
}

// verbatimPageIdentity derives (name, pageType) from a deploy path, leaving the
// path itself to be stored as pages.url unchanged.
//
// Names mirror CanonicalisePage's prefixes ("tool-x", "guide-x", "index") so an
// adopted page is named the way a planner-built page of the same kind would be
// — that is what lets downstream consumers keyed on the name prefix (tool
// eligibility, for one) see adopted tools at all. Only the URL differs, which
// is the whole point of this path.
func verbatimPageIdentity(deployPath string) (name, pageType string, ok bool) {
	trimmed := strings.Trim(deployPath, "/")
	if trimmed == "" {
		return "", "", false
	}

	// Drop a trailing /index.html so "/tools/x/index.html" and "/tools/x.html"
	// yield the same identity shape.
	trimmed = strings.TrimSuffix(trimmed, "/index.html")
	trimmed = strings.TrimSuffix(trimmed, ".html")
	if trimmed == "" || trimmed == "index" {
		return "index", "landing", true
	}

	segs := strings.Split(trimmed, "/")
	slug := slugifyPathSegments(segs)
	if slug == "" {
		return "", "", false
	}

	switch segs[0] {
	case "tools", "tool":
		bare := slugifyPathSegments(segs[1:])
		if bare == "" {
			return "tools-index", "section-index", true
		}
		return "tool-" + bare, "tool", true
	case "guides", "guide":
		bare := slugifyPathSegments(segs[1:])
		if bare == "" {
			return "guides-index", "section-index", true
		}
		return "guide-" + bare, "guide", true
	}
	return slug, "content", true
}

// slugifyPathSegments joins path segments into a single kebab-case name. The
// pages.page_type CHECK requires kebab-case, and pages.name is used in work
// item keys, so both must be free of slashes and stray punctuation.
func slugifyPathSegments(segs []string) string {
	var parts []string
	for _, s := range segs {
		s = strings.TrimSuffix(s, ".html")
		s = strings.ToLower(strings.TrimSpace(s))
		var b strings.Builder
		lastDash := false
		for _, r := range s {
			switch {
			case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
				b.WriteRune(r)
				lastDash = false
			default:
				if !lastDash && b.Len() > 0 {
					b.WriteByte('-')
					lastDash = true
				}
			}
		}
		seg := strings.Trim(b.String(), "-")
		if seg != "" {
			parts = append(parts, seg)
		}
	}
	return strings.Join(parts, "-")
}

// portedPageComponentID finds the shared passthrough component row that owned
// pages point at.
//
// It deliberately does NOT create one when missing. The lookup that
// cmd/webdesignport uses takes the most recent match, so a second 'ported-page'
// row would silently repoint every future port at whichever was created last —
// the reason to fail loudly here rather than seed a duplicate.
// Returns the count alongside the id so the caller can report ambiguity rather
// than resolve it silently — picking one of several without saying so is how a
// fleet ends up with two porters writing different components and nobody aware.
func portedPageComponentID(ctx context.Context, tx *sql.Tx) (id uuid.UUID, found int, err error) {
	rows, err := tx.QueryContext(ctx, `
		SELECT id FROM content_components
		WHERE function = $1 AND COALESCE(is_active, true)
		ORDER BY created_at
	`, portedPageSlot)
	if err != nil {
		return uuid.Nil, 0, fmt.Errorf("look up %s component: %w", portedPageSlot, err)
	}
	defer rows.Close()

	var ids []uuid.UUID
	for rows.Next() {
		var got uuid.UUID
		if err := rows.Scan(&got); err != nil {
			return uuid.Nil, 0, err
		}
		ids = append(ids, got)
	}
	if err := rows.Err(); err != nil {
		return uuid.Nil, 0, err
	}
	if len(ids) == 0 {
		return uuid.Nil, 0, fmt.Errorf(
			"no active content_components row with function=%q — verbatim adoption needs the shared passthrough component; seed it once, do not create a second",
			portedPageSlot)
	}
	// Oldest wins, deterministically. cmd/webdesignport's own lookup takes the
	// NEWEST, so a second row would split the two porters — hence the count.
	return ids[0], len(ids), nil
}

// applyVerbatimAdoption creates owned pages and their ported components
// directly from the crawl, then queues one assemble-mode page_rerender per page
// so the existing deploy path ships them.
//
// It runs INSTEAD OF ApplyAdoptionPlanAction's sections 4-5. The specs written
// before it (identity, site_archetype, design_reference, design_intent) still
// apply — they describe the site and cost nothing here — but the classifier
// handoff is deliberately NOT queued: that cascade exists to design a site, and
// running it against a site being preserved verbatim would restyle exactly what
// the caller asked to keep.
func applyVerbatimAdoption(
	ctx context.Context,
	tx *sql.Tx,
	siteID uuid.UUID,
	domain string,
	sourceDomain string,
	crawlPages map[string]*crawlPageContent,
	batchID uuid.UUID,
	logger *zap.Logger,
) (pagesCreated int, itemsQueued int, err error) {

	byPath, skipped := crawlPathIndex(crawlPages)
	if len(byPath) == 0 {
		return 0, 0, fmt.Errorf(
			"verbatim adoption found no crawled pages carrying rawHtml (crawl index had %d aliases) — the crawl must request scrapeOptions.formats including rawHtml",
			len(crawlPages))
	}
	if len(skipped) > 0 {
		// Not fatal, but never silent: a page present in the crawl yet
		// unpreservable is exactly what a caller asking for verbatim needs told.
		logger.Warn("Verbatim adoption: crawled pages without rawHtml were SKIPPED",
			zap.Int("skipped", len(skipped)),
			zap.Strings("paths", skipped))
	}

	componentID, componentsFound, err := portedPageComponentID(ctx, tx)
	if err != nil {
		return 0, 0, err
	}
	if componentsFound > 1 {
		logger.Warn("Verbatim adoption: MORE THAN ONE active ported-page component — using the oldest; cmd/webdesignport takes the NEWEST, so the two porters are now writing different components",
			zap.Int("found", componentsFound),
			zap.String("using", componentID.String()))
	}

	// Deterministic order so logs and any partial failure are reproducible.
	paths := make([]string, 0, len(byPath))
	for p := range byPath {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	type queued struct {
		pageID   uuid.UUID
		pageName string
		filename string
	}
	var toRerender []queued
	usedNames := make(map[string]string) // name -> path, to catch collisions

	for _, deployPath := range paths {
		content := byPath[deployPath]

		pageName, pageType, ok := verbatimPageIdentity(deployPath)
		if !ok {
			logger.Warn("Verbatim adoption: could not derive an identity, skipping",
				zap.String("path", deployPath))
			continue
		}
		if prev, clash := usedNames[pageName]; clash {
			// Two distinct paths reducing to one name would silently overwrite
			// each other through ON CONFLICT (site_id, name).
			logger.Warn("Verbatim adoption: page name collision, skipping later path",
				zap.String("name", pageName),
				zap.String("kept", prev),
				zap.String("skipped", deployPath))
			continue
		}
		usedNames[pageName] = deployPath

		title := extractHTMLTitle(content.RawHTML)
		if title == "" {
			title = strings.TrimSuffix(path.Base(deployPath), ".html")
		}
		metaDesc := extractHTMLMetaDescription(content.RawHTML)

		sectionsJSON, _ := json.Marshal([]string{portedPageSlot})

		// build_status='deployed' not 'planned': a 'planned' page is collected
		// by write_build_items and handed to the generic build pipeline, which
		// is precisely what an owned page must never enter.
		// in_header/in_footer=false: the source document carries its own
		// navigation, so platform nav must not also inject it.
		var pageID uuid.UUID
		err = tx.QueryRowContext(ctx, `
			INSERT INTO pages (
				site_id, name, url, title, page_type, status,
				meta_description, sections, rebuild_policy, build_status,
				in_header, in_footer, updated_at
			) VALUES ($1, $2, $3, $4, $5, 'active',
			          $6, $7::jsonb, 'owned', 'deployed',
			          false, false, NOW())
			ON CONFLICT (site_id, name) DO UPDATE SET
				url = EXCLUDED.url,
				title = EXCLUDED.title,
				page_type = EXCLUDED.page_type,
				meta_description = EXCLUDED.meta_description,
				sections = EXCLUDED.sections,
				rebuild_policy = 'owned',
				build_status = 'deployed',
				updated_at = NOW()
			RETURNING id
		`, siteID, pageName, deployPath, title, pageType,
			metaDesc, string(sectionsJSON)).Scan(&pageID)
		if err != nil {
			return pagesCreated, itemsQueued,
				fmt.Errorf("upsert verbatim page %s (%s): %w", pageName, deployPath, err)
		}

		sum := sha256.Sum256([]byte(content.RawHTML))
		contentData, _ := json.Marshal(map[string]interface{}{
			"schema":      "ported-page.v1",
			"deploy_mode": deployModeVerbatim,
			"source_url":  fmt.Sprintf("https://%s%s", sourceDomain, deployPath),
			"sha256":      hex.EncodeToString(sum[:]),
			"generator":   "adoption-locked/1",
		})

		// Keyed by (page_id, slot_name): there is no unique index on that pair,
		// so this is a lookup-then-write rather than an upsert.
		var instanceID uuid.NullUUID
		if err := tx.QueryRowContext(ctx,
			`SELECT id FROM page_components WHERE page_id = $1 AND slot_name = $2`,
			pageID, portedPageSlot).Scan(&instanceID); err != nil && err != sql.ErrNoRows {
			return pagesCreated, itemsQueued, fmt.Errorf("find ported component for %s: %w", pageName, err)
		}

		if instanceID.Valid {
			// Respect an operator lock: pageComponentAgentWritableSQL is the
			// shared predicate for "automation may write this row".
			res, err := tx.ExecContext(ctx, `
				UPDATE page_components
				   SET rendered_html = $1, content_data = $2::jsonb,
				       component_id = $3, build_status = 'approved',
				       updated_at = NOW()
				 WHERE id = $4 AND `+pageComponentAgentWritableSQL(""),
				content.RawHTML, string(contentData), componentID, instanceID.UUID)
			if err != nil {
				return pagesCreated, itemsQueued, fmt.Errorf("update ported component for %s: %w", pageName, err)
			}
			if n, _ := res.RowsAffected(); n == 0 {
				// A locked row is a deliberate human edit. Leave it and say so,
				// rather than reporting a success that did not happen.
				logger.Warn("Verbatim adoption: component is locked, left untouched",
					zap.String("page", pageName), zap.String("path", deployPath))
				pagesCreated++
				continue
			}
		} else {
			if _, err := tx.ExecContext(ctx, `
				INSERT INTO page_components (
					page_id, component_id, position, slot_name,
					rendered_html, content_data, build_status
				) VALUES ($1, $2, 0, $3, $4, $5::jsonb, 'approved')
			`, pageID, componentID, portedPageSlot,
				content.RawHTML, string(contentData)); err != nil {
				return pagesCreated, itemsQueued, fmt.Errorf("insert ported component for %s: %w", pageName, err)
			}
		}

		pagesCreated++
		toRerender = append(toRerender, queued{
			pageID:   pageID,
			pageName: pageName,
			filename: strings.TrimPrefix(deployPath, "/"),
		})
	}

	// Queue the deploy. page_rerender + page-rerender handler is the existing
	// route to git-adapter; with deploy_mode='verbatim' the rerender ships the
	// stored bytes rather than reassembling them.
	//
	// The spec carries domain/page_id/page_name/filename because that is the
	// shape a page_rerender consumer reads (page_id is needed in the spec AND
	// the column — the column alone is not enough).
	for _, q := range toRerender {
		specJSON, _ := json.Marshal(map[string]interface{}{
			"domain":    domain,
			"page_id":   q.pageID.String(),
			"page_name": q.pageName,
			"filename":  q.filename,
			"reason":    "verbatim_adoption_deploy",
		})
		inserted, err := insertPageRerenderItem(ctx, tx, siteID, q.pageID,
			"adoption", "medium",
			fmt.Sprintf("Deploy adopted page %s verbatim (%s)", q.pageName, q.filename),
			string(specJSON),
			pageRerenderItemKey(q.pageName, siteID, "verbatim-adoption"),
			batchID)
		if err != nil {
			return pagesCreated, itemsQueued, fmt.Errorf("queue rerender for %s: %w", q.pageName, err)
		}
		if inserted {
			itemsQueued++
		}
	}

	logger.Info("Verbatim adoption complete",
		zap.String("domain", domain),
		zap.String("source_domain", sourceDomain),
		zap.Int("pages", pagesCreated),
		zap.Int("rerender_items", itemsQueued),
		zap.Int("skipped_no_rawhtml", len(skipped)),
		zap.String("fidelity", fidelityLocked))

	return pagesCreated, itemsQueued, nil
}
