// FILE: platform/orchestration/actions/deploy_tool_action.go
//
// DeployToolToSiteAction forks a library tool into a site-owned copy,
// creates a page for it with content sections, and inserts the page_component.
//
// The tool page includes surrounding content sections (hero, guide intro, CTA)
// generated by page-content-writer. A companion guide article is also created
// as a separate blog-post page that links back to the tool.
//
// Fork-on-deploy model:
//   - Library tool: content_components WHERE component_level='tool' AND forked_from IS NULL
//   - Site fork:    new content_components row with forked_from = library tool ID
//   - Changes to the library tool do NOT cascade to existing forks
//
// Creates three outputs:
//   1. Tool page with sections: hero-tool, tool-guide-intro, [tool widget], tool-cta
//   2. needs_content_page work item for content around the tool
//   3. Companion guide article page + needs_content_page work item
//
// Config:
//   - nav_section: string (default "Tools") — nav group for the tool page
//   - in_header:   bool (default true) — show in header nav under Tools
//   - in_footer:   bool (default false)
//
// Data inputs (via ActionInputSpec):
//   - site_id             (required) — target site
//   - tool_component_id   (required) — library tool to fork (from work item spec)
//
// Resolved from work item spec or explicit input:
//   - page_name           (optional) — override auto-generated page name
//   - page_title          (optional) — override auto-generated page title

package actions

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"github.com/gqls/agentchassis/platform/orchestration/datahelpers"
	"go.uber.org/zap"
)

// ============================================================================
// ActionInputSpec
// ============================================================================

var DeployToolToSiteInputSpec = datahelpers.ActionInputSpec{
	Required: []string{"site_id", "tool_component_id"},
	// related_pages: the add_tool item's own suggestion field. Read here so the
	// tool's cross-link items can be emitted from THIS path, which knows the
	// page's real URL, instead of at suggestion time where it can only be
	// guessed (bugs_open/029).
	Optional:   []string{"page_name", "page_title", "related_pages"},
	Defaults:   map[string]interface{}{},
	Deprecated: map[string]string{},
}

func init() {
	datahelpers.RegisterActionInputSpec("deploy_tool_to_site", DeployToolToSiteInputSpec)
}

// ============================================================================
// ACTION: deploy_tool_to_site
// ============================================================================

func DeployToolToSiteAction(ctx context.Context, params ActionParams) (interface{}, error) {
	logger := params.Logger.With(
		zap.String("action", "deploy_tool_to_site"),
		zap.String("step_name", params.ExecutionContext.StepName),
	)

	logger.Info("DeployToolToSiteAction: Starting")

	if params.ExecutionContext.Action == "initialize" {
		return map[string]interface{}{"status": "initialized"}, nil
	}
	if params.DB == nil {
		return nil, fmt.Errorf("database connection required")
	}

	// --- Resolve inputs ---
	inputs, err := datahelpers.ExtractActionInputs(
		params.CollectedData,
		params.StepConfig.Config,
		DeployToolToSiteInputSpec,
		logger,
	)
	if err != nil {
		return nil, fmt.Errorf("input extraction failed: %w", err)
	}

	siteIDStr := inputs.Get("site_id")
	siteID, err := uuid.Parse(siteIDStr)
	if err != nil {
		return nil, fmt.Errorf("invalid site_id: %w", err)
	}

	toolIDStr := inputs.Get("tool_component_id")
	toolID, err := uuid.Parse(toolIDStr)
	if err != nil {
		return nil, fmt.Errorf("invalid tool_component_id: %w", err)
	}

	pageNameOverride := inputs.Get("page_name")
	pageTitleOverride := inputs.Get("page_title")

	config := params.StepConfig.Config
	navSection := "Tools"
	if v, ok := config["nav_section"].(string); ok && v != "" {
		navSection = v
	}
	inHeader := true
	if v, ok := config["in_header"].(bool); ok {
		inHeader = v
	}
	inFooter := false
	if v, ok := config["in_footer"].(bool); ok {
		inFooter = v
	}

	// --- Load site domain for logging and URL construction ---
	var siteDomain string
	_ = params.DB.QueryRowContext(ctx,
		`SELECT domain FROM sites WHERE id = $1`, siteID,
	).Scan(&siteDomain)

	logger.Info("DeployToolToSiteAction: Deploying tool",
		zap.String("site_id", siteIDStr),
		zap.String("domain", siteDomain),
		zap.String("tool_component_id", toolIDStr),
	)

	// --- 1. Load library tool ---
	var toolName, toolDisplayName, toolFunction, toolCategory string
	var toolDescription, toolHTMLTemplate sql.NullString
	var toolSemanticTags, toolInputSchema sql.NullString

	err = params.DB.QueryRowContext(ctx, `
		SELECT name, display_name, function, category,
		       description, html_template, semantic_tags::text, input_schema::text
		FROM content_components
		WHERE id = $1
		  AND component_level = 'tool'
		  AND is_active = true
	`, toolID).Scan(
		&toolName, &toolDisplayName, &toolFunction, &toolCategory,
		&toolDescription, &toolHTMLTemplate, &toolSemanticTags, &toolInputSchema,
	)
	if err != nil {
		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("tool component %s not found or not a tool", toolIDStr)
		}
		return nil, fmt.Errorf("load tool: %w", err)
	}

	if !toolHTMLTemplate.Valid || toolHTMLTemplate.String == "" {
		return nil, fmt.Errorf("tool %s has no HTML template", toolFunction)
	}

	// A tool whose script addresses elements its own template does not contain
	// is broken before it is deployed: the script throws on load and the
	// visitor gets a tool with no controls. Refusing here is the cheapest place
	// to stop it — the alternative is a live page that renders, returns 200 and
	// passes every downstream check while doing nothing (webdesign.co.uk shipped
	// ten of those; see datahelpers/element_refs.go for the evidence).
	//
	// A tool widget is self-contained by design — tool_health already flags
	// external dependencies — so the template alone is the right unit to judge,
	// unlike the deployed-page check, which must see every component plus the
	// chrome before it can call an id missing.
	//
	// Hard refusal rather than a warning, on measured grounds: all 32 library
	// and fork tool templates were run through this on 2026-07-29 and NONE
	// flagged, so this cannot fire on anything that exists today. It is a guard
	// against a future bad template, not a change to current behaviour. If it
	// ever does fire, the fix is the template, not this check: the ids it names
	// are what the script requires and the markup must provide.
	if orphans := datahelpers.OrphanElementRefs(toolHTMLTemplate.String); len(orphans) > 0 {
		logger.Error("DeployToolToSiteAction: refusing to deploy a tool whose script addresses absent elements",
			zap.String("tool_function", toolFunction),
			zap.Strings("missing_element_ids", orphans))
		return nil, fmt.Errorf(
			"tool %s addresses %d element(s) its template does not contain (%s) — "+
				"the script would throw on load and the tool would render no controls",
			toolFunction, len(orphans), strings.Join(orphans, ", "))
	}

	// --- 1b. requires-backend gate, deploy-time half ---
	// Migration 406 gates the suggestion; this gates the deploy itself, before
	// anything is written, so an add_tool item from any source cannot ship a
	// widget against a backend the site cannot have. Predicates, refusal
	// wording and the follow-on provision item: tool_backend_provision.go.
	requiresBackend := toolRequiresBackend(toolSemanticTags.String)
	var eligibility backendEligibility
	if requiresBackend {
		eligibility, err = loadBackendEligibility(ctx, params.DB, siteID)
		if err != nil {
			return nil, fmt.Errorf("requires-backend eligibility check: %w", err)
		}
		if refusal := backendEligibilityRefusal(eligibility, toolFunction, siteDomain); refusal != nil {
			logger.Error("DeployToolToSiteAction: refusing to deploy a requires-backend tool to an ineligible site",
				zap.Bool("backend_capable", eligibility.Capable),
				zap.Int("facts_count", eligibility.FactsCount),
				zap.String("semantic_tags", toolSemanticTags.String))
			return nil, refusal
		}
	}

	// --- 2. Check for existing fork and deployment status ---
	// Two-stage check:
	//   a) Does a fork of this tool exist for this site? (catches orphans from partial failures)
	//   b) If so, is it fully deployed (linked to a page via page_component)?
	// If fully deployed → return early.
	// If fork exists but not linked → reuse the fork, continue with page creation.
	// If no fork exists → create one.

	forkName := toolName + "-" + domainSlug(siteDomain)
	forkID := uuid.New()

	var existingForkID sql.NullString
	err = params.DB.QueryRowContext(ctx, `
		SELECT id::text
		FROM content_components
		WHERE forked_from = $1
		  AND name = $2
		  AND is_active = true
		LIMIT 1
	`, toolID, forkName).Scan(&existingForkID)

	if err == nil && existingForkID.Valid {
		// Fork exists — reuse it
		if parsed, parseErr := uuid.Parse(existingForkID.String); parseErr == nil {
			forkID = parsed
		}
		logger.Info("DeployToolToSiteAction: Found existing fork",
			zap.String("fork_id", forkID.String()),
			zap.String("fork_name", forkName))

		// Check if fully deployed (fork linked to a page on this site)
		var deployedPageID sql.NullString
		_ = params.DB.QueryRowContext(ctx, `
			SELECT p.id::text
			FROM page_components pc
			JOIN pages p ON pc.page_id = p.id
			WHERE pc.component_id = $1
			  AND p.site_id = $2
			LIMIT 1
		`, forkID, siteID).Scan(&deployedPageID)

		if deployedPageID.Valid {
			logger.Info("DeployToolToSiteAction: Tool already fully deployed",
				zap.String("fork_id", forkID.String()))

			// Cross-links are emitted even on this early return: re-running the
			// deployer is the supported way to backfill them for a tool that was
			// deployed before bugs_open/029 was fixed. The URL is read from the
			// page row, never constructed, and dedup makes the repeat harmless.
			crossLinks := 0
			if toolPageID, toolPageURL, found := resolveToolPageURL(ctx, params.DB, siteID, toolFunction); found {
				crossLinks = emitToolCrossLinkItems(ctx, params, logger, toolCrossLinkRequest{
					siteID:       siteID,
					toolFunction: toolFunction,
					toolName:     toolDisplayName,
					toolDesc:     toolDescription.String,
					toolPageID:   toolPageID,
					toolPageURL:  toolPageURL,
					relatedPages: relatedPagesFromInputs(inputs, params.CollectedData),
					emittedBy:    "tool-deployer",
				})
			}

			// backend_required only: the provision item was raised when this
			// fork first deployed, and re-minting on a backfill re-run would
			// ask the operator to provision a backend that is already running.
			return map[string]interface{}{
				"site_id":           siteIDStr,
				"tool_function":     toolFunction,
				"already_deployed":  true,
				"fork_id":           forkID.String(),
				"needs_rerender":    false,
				"cross_links_added": crossLinks,
				"backend_required":  requiresBackend,
			}, nil
		}

		// Fork exists but not linked to a page — continue with page creation
		logger.Info("DeployToolToSiteAction: Fork exists but not fully deployed, continuing",
			zap.String("fork_id", forkID.String()))
	} else {
		// --- 3. Fork the tool (create site-owned copy) ---
		// source_* = the DEPLOYING actor (creation provenance for the fork);
		// forked_from carries the library lineage. NOTE (flagged, unchanged):
		// created_from is not set here so forks default to 'manual' — the
		// CHECK allows 'forked' if that's ever wanted, but changing it is a
		// behaviour change beyond this patch. js_content is also not copied
		// (the known landmine — see 019 correction); harmless while tools
		// stay inline.
		_, err = params.DB.ExecContext(ctx, `
			INSERT INTO content_components (
				id, name, display_name, function, category, component_level, render_mode,
				is_dark_section, is_active, description,
				semantic_tags, html_template, input_schema, forked_from,
				source_agent_type, source_orchestration_id
			)
			SELECT
				$1,
				$2,
				display_name,
				function,
				category,
				component_level,
				render_mode,
				is_dark_section,
				true,
				description,
				semantic_tags,
				html_template,
				input_schema,
				$3,
				$4,
				$5
			FROM content_components
			WHERE id = $3
		`, forkID, forkName, toolID,
			nullIfEmpty(params.ExecutionContext.Sender.AgentType),
			nullIfEmpty(params.ExecutionContext.OrchestrationID))
		if err != nil {
			return nil, fmt.Errorf("fork tool: %w", err)
		}

		logger.Info("DeployToolToSiteAction: Tool forked",
			zap.String("fork_id", forkID.String()),
			zap.String("fork_name", forkName),
			zap.String("forked_from", toolIDStr),
		)
	}

	// --- 4. Create tool page ---
	//
	// bugs_open/080 (concept register TL-010): this arm used to hand-roll
	// `<bare>` @ /tools/<bare>.html while its sibling create_tool_component
	// writes the canonical `tool-<bare>` @ /tools/<bare>/index.html — the same
	// divergent-identity class the gap-planner was fixed for, on a different
	// pair of surfaces. A NEW tool page now takes the canonical identity from
	// datahelpers.CanonicalisePage. An EXISTING row under either name keeps its
	// identity untouched (12 live legacy-shape rows, measured 2026-08-03):
	// re-deploying under the canonical name while the legacy row stands would
	// mint a second row — the exact duplicate this bug is about — so the lookup
	// below reuses whatever identity is already there.
	pageName := pageNameOverride
	var pageURL string
	if pageName != "" {
		// Caller-supplied identity is an explicit escape hatch and keeps the
		// historical URL shape.
		pageURL = "/tools/" + pageName + ".html"
	} else {
		var err error
		pageName, pageURL, err = resolveToolPageIdentity(ctx, params.DB, siteID, toolFunction,
			siteUsesFlatURLs(ctx, params.DB, siteID, params.Logger))
		if err != nil {
			return nil, err
		}
	}

	pageTitle := pageTitleOverride
	if pageTitle == "" {
		pageTitle = toolDisplayName
	}

	// Get next nav order for tools section
	var maxNavOrder int
	_ = params.DB.QueryRowContext(ctx,
		`SELECT COALESCE(MAX(nav_order), 0) FROM pages WHERE site_id = $1 AND url LIKE '/tools/%'`,
		siteID,
	).Scan(&maxNavOrder)

	// Tool page has content sections around the tool widget:
	//   position 0: hero-tool (headline + brief intro)
	//   position 1: tool-guide-intro (educational content about the concept)
	//   position 2: the tool itself (interactive widget)
	//   position 3: tool-cta (call to action, link to companion guide)
	sectionsJSON := fmt.Sprintf(
		`["hero-tool", "tool-guide-intro", "%s", "tool-cta"]`,
		toolFunction,
	)

	// bugs_open/103. The tool's own description is the BUILD BRIEF, so it is
	// checked before it can reach a public column, and a rejection is LOGGED —
	// the council objected, correctly, that a silent swap is a new silent-drop
	// path introduced by the fix for a silent-content problem.
	toolMeta, metaReplaced := datahelpers.PublicMetaDescription(
		toolDescription.String,
		composedToolMetaDescription(toolDisplayName),
	)
	if metaReplaced {
		logger.Warn("DeployToolToSiteAction: tool description rejected as a build brief, composed copy used instead",
			zap.String("tool_function", toolFunction),
			zap.Int("rejected_length", len(toolDescription.String)),
			zap.String("published", toolMeta))
	}

	// bugs_open/175. The DO UPDATE SET here named url, title and sections but NOT
	// page_type, so deploying a tool onto a name already held by a page of another
	// role wrote the tool's sections and url into that page and left it typed as
	// whatever it was — orphaned from every gate that keys on page_type='tool',
	// while its old content was gone. UpsertPageForRole turns that collision into
	// an explicit branch; see page_role_upsert.go.
	toolPage, err := UpsertPageForRole(ctx, params.DB, PageRoleUpsert{
		SiteID:   siteID,
		Domain:   siteDomain,
		Name:     pageName,
		PageType: "tool",
		Source:   "tool-deployer",
		// Declared: the role is this arm's constant, so an unshipped page of
		// another role holding this name is one this arm may take over (RFC_010).
		AdoptUnshippedRows: true,
		Columns: []PageColumn{
			Col("url", pageURL),
			Col("title", pageTitle),
			Col("nav_label", navSection+" / "+toolDisplayName),
			Col("nav_order", maxNavOrder+1),
			Col("in_header", inHeader),
			Col("in_footer", inFooter),
			Col("meta_description", toolMeta),
			JSONCol("sections", sectionsJSON),
			Col("build_status", "planned"),
			Col("status", "active"),
		},
		Refresh: []string{"url", "title", "sections"},
	}, logger)
	if err != nil {
		return nil, fmt.Errorf("create tool page: %w", err)
	}
	if toolPage.Refused() {
		// The tool has been forked already, but nothing was written to the live
		// page and a human decision is filed. Failing is the honest outcome — the
		// alternative is the overwrite this bug is about.
		return nil, fmt.Errorf("tool page %q not created: %s", pageName, toolPage.Reason)
	}
	pageID := toolPage.PageID

	logger.Info("DeployToolToSiteAction: Page created",
		zap.String("page_id", pageID.String()),
		zap.String("page_name", pageName),
		zap.String("url", pageURL),
	)

	// --- 4b. Ask for the nav rebuild the declaration needs (bugs_open/149 A6) ---
	//
	// This action records in_header/in_footer above and, until 2026-07-31, wrote
	// nothing else: no nav row and no request, so a deployed tool waited for a
	// discovery sweep to notice it was orphaned. Its sibling
	// create_tool_component did the opposite — hand-wrote a nav row and left the
	// flags to the schema default. Each did half the job, and neither made the
	// link ship. Both now do the same whole thing: declare on the page row,
	// request the rebuild. See nav_rebuild_request.go.
	if inHeader || inFooter {
		RequestNavRebuild(ctx, params.DB, NavRebuildRequest{
			SiteID:      siteID,
			PageID:      pageID,
			PageName:    pageName,
			PageURL:     pageURL,
			InHeader:    inHeader,
			InFooter:    inFooter,
			RequestedBy: "tool-deployer",
		}, logger)
	}

	// --- 5. Create page_component linking fork to page ---
	// Position 2: the tool widget sits between intro content and CTA
	var pcID uuid.UUID
	err = params.DB.QueryRowContext(ctx, `
		INSERT INTO page_components (
			page_id, component_id, position, slot_name,
			rendered_html, content_data, build_status
		) VALUES (
			$1, $2, 2, $3,
			$4, '{}'::jsonb, 'deployed'
		)
		ON CONFLICT DO NOTHING
		RETURNING id
	`, pageID, forkID, toolFunction,
		toolHTMLTemplate.String,
	).Scan(&pcID)
	if err != nil {
		// May be a conflict — check if already exists
		logger.Warn("DeployToolToSiteAction: page_component insert issue",
			zap.Error(err))
	}

	// --- 5b. Ask for the backend the widget now needs (requires-backend only) ---
	// The widget is live from the page_component insert above; from here until
	// an operator provisions its backend on the box it fails closed to the
	// site's contact details. The item is that handover — the in-cluster
	// pipeline cannot reach the box by design. See tool_backend_provision.go.
	backendProvision := ""
	if requiresBackend {
		backendProvision = raiseBackendProvisionItem(ctx, params, logger, backendProvisionRequest{
			siteID:       siteID,
			domain:       siteDomain,
			pageID:       pageID,
			pageURL:      pageURL,
			toolFunction: toolFunction,
			displayName:  toolDisplayName,
			forkID:       forkID,
			eligibility:  eligibility,
		})
	}

	// --- 6. Create work item for content around the tool ---
	// page-content-writer generates hero, intro, and CTA sections.
	// The tool section (position 2) already has content — the writer skips it.
	//
	// bugs_open/177 routed this through the shared guard. Behaviour on THIS arm
	// is unchanged: the page written above declares hero-tool, tool-guide-intro
	// and tool-cta alongside the widget, so the guard resolves three prose
	// sections and raises exactly the item it always did. The seam exists because
	// the sibling path declares nothing and must not raise — one guard rather
	// than two emitters that agree only by luck. See tool_content_item.go.
	contentItem := raiseToolContentItem(ctx, params, logger, toolContentItemRequest{
		siteID:       siteID,
		pageID:       pageID,
		pageName:     pageName,
		toolFunction: toolFunction,
		displayName:  toolDisplayName,
		description:  toolDescription.String,
		pageURL:      pageURL,
		source:       "tool-deployer",
	})

	// --- 6b. Cross-link the tool from its related pages (bugs_open/029) ---
	// Emitted HERE, after the page row and its content build item exist, so the
	// rewrite instruction carries the page's real URL and only runs once the
	// page is live. tool-suggester used to emit these at suggestion time from a
	// constructed /tools/{function}.html, which matched no page on any of the
	// three URL shapes this platform produces.
	crossLinksAdded := emitToolCrossLinkItems(ctx, params, logger, toolCrossLinkRequest{
		siteID:       siteID,
		toolFunction: toolFunction,
		toolName:     toolDisplayName,
		toolDesc:     toolDescription.String,
		toolPageID:   pageID,
		toolPageURL:  pageURL,
		relatedPages: relatedPagesFromInputs(inputs, params.CollectedData),
		emittedBy:    "tool-deployer",
	})

	// --- 7. Create companion guide article ---
	// A blog-post that explains the concept in depth and links to the tool.
	// Identity via the shared canonicaliser (bugs_open/080) — byte-identical to
	// the old sprintf for every existing guide, and the single authority now.
	guideName, guideURL, guideIDErr := companionGuideIdentity(pageName)
	if guideIDErr != nil {
		logger.Warn("DeployToolToSiteAction: companion guide identity failed canonicalisation, guide skipped (non-fatal)",
			zap.Error(guideIDErr))
	}
	guideTitle := fmt.Sprintf("Understanding %s | Guide", toolDisplayName)

	// bugs_open/175, and this is the arm with the live exposure: the guide name is
	// `<tool page name>-guide`, and robot-hands.com carries two DEPLOYED pages —
	// `gripper-selection-guide` and `selection-guide` — typed `content`. Under the
	// old upsert, deploying a tool named `gripper-selection` there would have
	// re-titled a live page and written a companion-guide work item against it,
	// leaving it typed `content`. It now refuses instead, and says so.
	//
	// Refresh is `title` ALONE, deliberately: a guide that has already been
	// written must not lose its sections to a tool redeploy. That is the existing
	// behaviour, preserved.
	var guidePage PageRoleResult
	guideErr := guideIDErr
	if guideErr == nil {
		guidePage, guideErr = UpsertPageForRole(ctx, params.DB, PageRoleUpsert{
			SiteID:             siteID,
			Domain:             siteDomain,
			Name:               guideName,
			PageType:           "blog-post",
			Source:             "tool-deployer",
			AdoptUnshippedRows: true,
			Columns: []PageColumn{
				Col("url", guideURL),
				Col("title", guideTitle),
				Col("nav_order", 200),
				Col("in_header", false),
				Col("in_footer", false),
				Col("meta_description", composedGuideMetaDescription(toolDisplayName)),
				JSONCol("sections", `["hero", "article-body", "call-to-action"]`),
				Col("build_status", "planned"),
				Col("status", "active"),
			},
			Refresh: []string{"title"},
		}, logger)
	}

	switch {
	case guideErr != nil:
		logger.Warn("DeployToolToSiteAction: Failed to create companion guide page (non-fatal)", zap.Error(guideErr))
	case guidePage.Refused():
		// Non-fatal, like every other failure on this arm — but no longer silent,
		// and no longer an overwrite. The decision is filed as a work item.
		logger.Warn("DeployToolToSiteAction: companion guide refused — a live page holds that name under another role",
			zap.String("guide_name", guideName),
			zap.String("existing_page_type", guidePage.ExistingType),
			zap.String("reason", guidePage.Reason))
	default:
		guidePageID := guidePage.PageID
		// Create work item for the guide article
		guideSpec, _ := json.Marshal(map[string]interface{}{
			"page_name":         guideName,
			"page_id":           guidePageID.String(),
			"page_type":         "blog-post",
			"tool_function":     toolFunction,
			"tool_display_name": toolDisplayName,
			"tool_page_url":     pageURL,
			"source":            "tool-deployer",
			// bugs_open/271: "suggestion" is the key page-build-handler reads
			// and forwards to the writer prompt; "content_guidance" had none.
			"suggestion": fmt.Sprintf(
				"Write an in-depth guide about %s. Explain the concept, why it matters, common mistakes people make, "+
					"and practical tips. At relevant points, reference the interactive %s tool at %s — "+
					"e.g. 'Use our %s to see how this applies to your situation.' "+
					"The article should stand alone as useful content even without the tool.",
				strings.TrimPrefix(toolDisplayName, "UK "),
				strings.ToLower(toolDisplayName), pageURL,
				strings.ToLower(toolDisplayName),
			),
		})

		_, err = params.DB.ExecContext(ctx, `
			INSERT INTO site_work_items (
				site_id, source, pipeline, item_type, severity, summary,
				spec, page_id, priority, handler_agent, status, created_by, item_key
			) VALUES (
				$1, 'tool-deployer', 'build', 'needs_content_page', 'low',
				$2, $3::jsonb, $4, 70, 'page-build-handler', 'triaged', 'tool-deployer', $5
			) ON CONFLICT DO NOTHING
		`, siteID,
			fmt.Sprintf("Write companion guide: %s", guideTitle),
			string(guideSpec), guidePageID,
			fmt.Sprintf("tool_guide:%s:%s", toolFunction, siteID),
		)
		if err != nil {
			logger.Warn("DeployToolToSiteAction: Failed to create guide work item (non-fatal)", zap.Error(err))
		} else {
			logger.Info("DeployToolToSiteAction: Companion guide created",
				zap.String("guide_page_id", guidePageID.String()),
				zap.String("guide_url", guideURL))
		}
	}

	logger.Info("DeployToolToSiteAction: Tool deployed",
		zap.String("site_id", siteIDStr),
		zap.String("domain", siteDomain),
		zap.String("tool", toolFunction),
		zap.String("fork_id", forkID.String()),
		zap.String("page_id", pageID.String()),
	)

	result := map[string]interface{}{
		"site_id":           siteIDStr,
		"domain":            siteDomain,
		"tool_function":     toolFunction,
		"tool_display_name": toolDisplayName,
		"fork_id":           forkID.String(),
		"page_id":           pageID.String(),
		"page_url":          pageURL,
		"guide_url":         guideURL,
		"already_deployed":  false,
		"needs_rerender":    true,
		"cross_links_added": crossLinksAdded,
		"content_item":      contentItem,
		"backend_required":  requiresBackend,
	}
	if requiresBackend {
		// The disposition is output, not just a log line: a requires-backend
		// tool whose provision request was never filed is a permanently dead
		// widget that reads as a successful deploy everywhere else.
		result["backend_provision"] = backendProvision
	}
	return result, nil
}

// companionGuideIdentity derives the (name, url) for a tool's companion guide
// through the shared canonicaliser — bugs_open/080: both tool surfaces used to
// sprintf "/guides/<name>-guide.html" by hand, in two files. For role=blog-post
// under parent "guides" the helper returns exactly that shape (measured
// byte-convergent 2026-08-03), so this is convergence-enforcement, not a
// behaviour change — and the helper is the single authority if the convention
// ever moves.
func companionGuideIdentity(toolPageName string) (string, string, error) {
	name, url, _ := datahelpers.CanonicalisePage(datahelpers.PageDescriptor{
		Role:          "blog-post",
		Slug:          toolPageName + "-guide",
		ParentSection: "guides",
	})
	if name == "" {
		return "", "", fmt.Errorf("companion guide for %q failed canonicalisation", toolPageName)
	}
	return name, url, nil
}

// resolveToolPageIdentity returns the (name, url) a tool page should be
// written under.
//
// bugs_open/080 / TL-010: a NEW tool takes the canonical identity from
// datahelpers.CanonicalisePage — `tool-<bare>` @ /tools/<bare>/index.html —
// converging this arm with create_tool_component. An EXISTING row under either
// the legacy name (`<bare>`) or the canonical one keeps its stored identity
// untouched: writing the canonical name while a legacy row stands would not
// conflict on (site_id, name) and so would INSERT A SECOND ROW — the exact
// duplicate-page failure this bug is about. 12 live legacy-shape rows measured
// 2026-08-03; none may move.
//
// If both names exist (a collision the page_canonical_collision discovery
// check reports), the canonical row wins.
//
// flatURLs is the site's url_shape flag (siteUsesFlatURLs) — the caller reads
// it once per action run and threads it here rather than this helper querying
// again, so the sqlmock tests keep their one-query expectation. It only shapes
// the NEW-tool arm; an existing row keeps its stored identity regardless.
func resolveToolPageIdentity(ctx context.Context, db *sql.DB, siteID uuid.UUID, toolFunction string, flatURLs bool) (string, string, error) {
	legacyName := strings.TrimPrefix(toolFunction, "tool-")
	canonicalName, canonicalURL, _ := datahelpers.CanonicalisePage(datahelpers.PageDescriptor{
		Role:     "tool",
		Slug:     toolFunction,
		FlatURLs: flatURLs,
	})
	if canonicalName == "" {
		return "", "", fmt.Errorf("tool function %q failed canonicalisation", toolFunction)
	}
	var existingName, existingURL string
	err := db.QueryRowContext(ctx, `
		SELECT name, url FROM pages
		WHERE site_id = $1 AND name IN ($2, $3)
		ORDER BY (name = $3) DESC
		LIMIT 1
	`, siteID, legacyName, canonicalName).Scan(&existingName, &existingURL)
	switch {
	case err == sql.ErrNoRows:
		return canonicalName, canonicalURL, nil
	case err != nil:
		return "", "", fmt.Errorf("resolve existing tool page identity: %w", err)
	}
	return existingName, existingURL, nil
}

// domainSlug returns a slug-safe version of the full domain.
// The full domain is preserved because .co.uk and .uk are different sites
// and the TLD may be the only differentiator.
// e.g. "website-design.co.uk" → "website-design-co-uk"
//
//	"website-design.uk"    → "website-design-uk"
func domainSlug(domain string) string {
	if domain == "" {
		return "site"
	}
	return strings.ReplaceAll(domain, ".", "-")
}

// composedToolMetaDescription builds the visitor-facing description for a tool
// page when the tool's own `description` cannot be published (bugs_open/103).
//
// It is shared by the two surfaces that create tool pages — DeployToolToSiteAction
// and CreateToolComponentAction — because they had the SAME defect and the bug
// file only named one of them. A second, unguarded call site is how this platform
// has repeatedly shipped half a fix (bugs_open/093, bugs_open/112), so the copy
// lives in one function rather than being written out twice.
//
// The register deliberately matches the companion guide page's long-standing
// composed line: plain, specific, and true of every tool — the visitor uses it in
// the browser and there is always a guide.
// Rewritten 2026-07-27 against the house voice, which went live the same evening
// (`voice_style_block` in agent_default_configs; see platform/voicestyle and
// bugs_open/121). The first version read "Use our free interactive X in your
// browser — a Y tool, with a companion guide explaining how it works" and broke
// three of those rules at once: an em dash, which the block bans outright and
// without exception; "free interactive", which is word-weight the claim has not
// earned; and "explaining how it works", the vague gesture the block asks you to
// replace with the named action. It also gave the reader no reason to care,
// which the block calls out directly.
//
// The wording is IDENTICAL to the backfill that repaired the 17 live rows
// (sql_for_agents/242). Two registers for one sentence is the drift this whole
// area keeps producing; if this line changes, change that file with it.
//
// The `category` argument is gone rather than left unread. It only fed the
// em-dash branch, and a parameter that survives as decoration is exactly the
// trap bugs_open/105 was filed about.
func composedToolMetaDescription(displayName string) string {
	// Strip a nav suffix if one rides along. display_name is usually clean, but
	// the sibling backfill had to strip " | Tools" from pages.title, and the two
	// should not disagree about what a tool is called.
	name := displayName
	if i := strings.Index(name, "|"); i >= 0 {
		name = name[:i]
	}
	name = strings.TrimSpace(strings.TrimPrefix(strings.TrimSpace(name), "UK "))
	if name == "" {
		return ""
	}
	return fmt.Sprintf(
		"An interactive %s, free to run in the browser. The companion guide sets out "+
			"the method behind it, so you can check the working.", name)
}

// composedGuideMetaDescription is the companion guide page's description.
//
// It was inline `fmt.Sprintf` in BOTH deploy_tool_action.go and
// create_tool_component_action.go — the same sentence written out twice. The
// council's reuse_agent and prior_art_librarian seats both objected that
// composedToolMetaDescription "mirrors" this logic rather than reusing it, and
// asked whether the guide composer was already a callable function. It was not;
// it was duplicated. Extracting it means this change removes an existing
// duplication instead of adding a third copy of the idea.
func composedGuideMetaDescription(displayName string) string {
	// The em dash this used to carry is now a house-voice violation ("no em
	// dashes, anywhere, ever"). A colon is explicitly allowed where a list
	// genuinely follows, and one does. "our" drops out as marketing weight the
	// sentence does not need.
	//
	// This only governs guide pages created FROM NOW ON. 26 live guide pages
	// across 9 sites still carry the em-dash wording, and 40 live meta
	// descriptions contain an em dash in total — recorded in bugs_open/103, not
	// rewritten here: that is the voice thread's estate-wide call, not a side
	// effect of a tool-page fix.
	return fmt.Sprintf(
		"A practical guide to %s: what it means, how it works, and how to use the interactive %s.",
		strings.TrimPrefix(displayName, "UK "),
		strings.ToLower(displayName))
}
