// FILE: platform/orchestration/actions/palette_specialised_slots.go
//
// Fills the palette slots a layout declares but a generated palette never
// supplies, when leaving them unset would paint a LIGHT literal onto a DARK
// site.
//
// THE DEFECT THIS CLOSES
// ----------------------
// A layout's css_template declares ~17 palette slots, each with a hard-coded
// fallback: `{{palette "card_bg" "#ffffff"}}`, `{{palette "header_bg"
// "#ffffff"}}`, `{{palette "cta_bg" "#1a365d"}}`. Those fallbacks are the
// Template Helper Fallback contract working as designed — a layout stays valid
// CSS when a map omits a slot.
//
// But a per-site palette generated by the design pipeline holds only the EIGHT
// core slots (corePaletteKeys in render_css_composition_helpers.go: primary,
// secondary, accent, background, surface, text, text_muted, border). The other
// nine therefore take the layout's literals on every render. Those literals
// were written for a light-scheme layout. On a dark site the result is a white
// card carrying text coloured for a near-black page.
//
// Measured 2026-07-27, fleet-wide: 16 of 31 palettes define no `card_bg`, and
// 12 of those 16 are dark-background palettes whose `text` is light — i.e. a
// guaranteed white-card-with-white-text. On fundamentallyai.com that was 1.21:1
// against the 4.5:1 floor, across every card on every page, including the whole
// evidence-chart section. It fails silently: the CSS is valid, the render
// succeeds, and only a rendered-page measurement shows it.
//
// WHY THE FIX IS SCOPED TO DARK BACKGROUNDS
// -----------------------------------------
// For a light site the layout's literals are broadly right, and four live
// palettes (idea.uk, relojistas.com, vetcomparison.uk, webdesign.co.uk) rely on
// them today. Deriving for them too would repaint live sites to no benefit.
// The boundary is the incoherence itself: a light literal is only wrong when
// the site is dark, so that is exactly when a derived value replaces it.
//
// A slot the palette DOES define is never touched, so the 15 curated library
// palettes render identically.

package actions

import (
	"regexp"
	"sort"
	"strings"

	"go.uber.org/zap"
)

// derivedSlot describes how one specialised slot is derived when a dark-scheme
// palette omits it.
//
// Two kinds:
//   - copy: take the value of another slot verbatim (a card is a surface).
//   - ink:  pick a foreground that clears AA against a named slot's colour
//     (text on a card, text on the accent).
type derivedSlot struct {
	name    string
	from    string // the slot supplying the value, or the background for an ink
	isInk   bool
	comment string
}

// darkSchemeDerivations is applied in order. `from` may itself be a slot filled
// earlier in this list (cta_text derives against cta_bg), so order matters and
// the slice is deliberately not a map.
var darkSchemeDerivations = []derivedSlot{
	{name: "card_bg", from: "surface", comment: "a card is a raised surface"},
	{name: "header_bg", from: "background", comment: "chrome sits on the page"},
	{name: "cta_bg", from: "surface", comment: "an emphasis band is a surface"},
	{name: "footer_bg", from: "background", comment: "chrome sits on the page"},
	{name: "background_alt", from: "surface"},
	{name: "surface_alt", from: "surface"},

	// NOT HERE: icon_chip_bg. I added it, then measured, and it would have been
	// dead config — the exact shape that looks live and is not.
	//
	// The palette reaches the stylesheet only through `{{palette "X" "literal"}}`
	// calls in a LAYOUT template, so a slot no layout names is never emitted and
	// the component's own `var(--color-icon-chip-bg, #EEF2F8)` fallback ships
	// regardless of what this list says. Measured 2026-07-29 across all 18
	// layouts: card_bg declared by 18, surface_alt by 3, **icon_chip_bg by 0**.
	//
	// The literal is also far narrower than it looks: `icon-chip-bg` appears in
	// exactly ONE active component fleet-wide (`info-card-grid`, and only in its
	// image variant). `image-hover-card-grid` — the component image cards
	// actually use — already reads `var(--color-surface-alt, var(--color-surface))`,
	// which IS derived above. So the generated icon ground (flatKindPaletteClause
	// asks for `surface`) and the tile it lands in already agree on the path that
	// matters.
	//
	// Fixing info-card-grid's image variant means editing a fleet-shared
	// component template with 23 placements across 11 sites. That is its own
	// change with its own review, not a passenger on this one.

	{name: "primary_hover", from: "primary", comment: "hover keeps the family"},
	{name: "secondary_hover", from: "secondary"},

	{name: "heading", from: "text", comment: "headings are the reading colour"},
	{name: "hero_title", from: "text"},
	{name: "hero_subtitle", from: "text_muted"},

	// Inks: each must contrast with the colour it lands on. These are the
	// pairs the component library assumes exist — `--color-primary-text` on a
	// primary-filled button, `--color-accent-text` on an accent-filled one.
	{name: "primary_text", from: "primary", isInk: true},
	{name: "secondary_text", from: "secondary", isInk: true},
	{name: "header_text", from: "header_bg", isInk: true},
	{name: "cta_text", from: "cta_bg", isInk: true},
	{name: "footer_text", from: "footer_bg", isInk: true},

	// accent_text has no layout consuming it yet. It is emitted so a component
	// can stop hard-coding white over an accent fill: `.form-submit` does
	// exactly that on 12 sites and scores 2.81:1 on this site's amber.
	{name: "accent_text", from: "accent", isInk: true},
}

// inkMinContrast is the WCAG AA floor for normal-size body text. An ink slot
// is text sitting on a filled control or band, so AA is the right bar — these
// are not decorative large headings.
const inkMinContrast = 4.5

// fillDarkSchemeSpecialisedSlots adds the specialised slots a dark palette
// omits, deriving each from the core slots it does define. It mutates and
// returns the merged palette.
//
// Inert unless the merged background is dark. Never overwrites a slot the
// palette already defines. Logs exactly one line naming what it filled, so a
// stylesheet's provenance stays readable — a derived value and a curated one
// are indistinguishable in the output CSS, which is the property that let the
// original defect hide.
func fillDarkSchemeSpecialisedSlots(palette map[string]string, logger *zap.Logger) map[string]string {
	if palette == nil {
		return palette
	}
	bg, ok := palette["background"]
	if !ok || bg == "" || !isDarkHex(bg) {
		return palette
	}

	filled := make([]string, 0, len(darkSchemeDerivations))
	skipped := make([]string, 0)
	for _, d := range darkSchemeDerivations {
		if existing, ok := palette[d.name]; ok && existing != "" {
			continue
		}
		source, ok := palette[d.from]
		if !ok || source == "" {
			// The source slot is itself missing, so there is nothing to derive
			// from and the layout's literal ships after all. That is the SAME
			// outcome as doing nothing, and it must not look like success:
			// council f17b0a77, bug_historian (high) — "a silent no-op fallback
			// path sits right next to the loud one this plan is adding, and
			// nothing distinguishes 'derived' from 'fell through to the light
			// literal' in the output CSS".
			skipped = append(skipped, d.name+"<-"+d.from)
			continue
		}
		if d.isInk {
			ink, _ := pickInkOn(source, palette)
			palette[d.name] = ink
		} else {
			palette[d.name] = source
		}
		filled = append(filled, d.name)
	}

	if len(filled) > 0 {
		sort.Strings(filled)
		logger.Info("fillDarkSchemeSpecialisedSlots: derived slots a dark palette omitted, "+
			"instead of letting the layout's light literals through",
			zap.String("background", bg),
			zap.Strings("derived", filled))
	}
	if len(skipped) > 0 {
		sort.Strings(skipped)
		logger.Warn("fillDarkSchemeSpecialisedSlots: could NOT derive one or more slots because "+
			"the core slot each derives from is itself missing — the layout's own literal will "+
			"ship for these, which on a dark site is the defect this function exists to prevent",
			zap.String("background", bg),
			zap.Strings("undeliverable", skipped))
	}
	return palette
}

// paletteHelperCall matches a layout template's {{palette "slot" "fallback"}}.
// Both arguments are captured: the slot name says what the layout wants, and
// the fallback says what ships when nothing supplies it.
var paletteHelperCall = regexp.MustCompile(`\{\{\s*palette\s+"([a-z_]+)"\s+"([^"]*)"\s*\}\}`)

// warnLightLiteralsOnDarkSite reports every slot a layout declares that this
// dark palette does not supply and darkSchemeDerivations does not cover, where
// the layout's own fallback is a LIGHT colour — i.e. exactly the cases that
// will ship a light value onto a dark page.
//
// WHY THIS EXISTS RATHER THAN A LONGER DERIVATION TABLE (council f17b0a77,
// bug_historian, medium): the derivation table fixes the nine specialised slots
// all 18 active layouts share, but `{{palette "X" "<light literal>"}}` is a
// GENERIC construct and the fleet's layouts declare 60+ further slot names
// between them — `badge_bg`, `chip_bg`, `input_pane_bg`, `trust_bar_bg`,
// `callout_bg`, `code_bg`, `success`, `warn`. Enumerating those would be
// guesswork: nobody can say from here what `badge_deal` should be on a dark
// site, and deriving `success` from `surface` would be actively wrong.
//
// So this does not guess. It makes the fall-through VISIBLE, which is the
// property whose absence let the original defect hide for as long as it did —
// a derived value, a curated value and a layout literal are indistinguishable
// in the finished CSS. A slot named here is a palette-authoring decision
// somebody has not made yet, and now has to be told about.
func warnLightLiteralsOnDarkSite(layoutTemplate string, palette map[string]string, logger *zap.Logger) {
	bg, ok := palette["background"]
	if !ok || bg == "" || !isDarkHex(bg) {
		return
	}
	covered := make(map[string]struct{}, len(darkSchemeDerivations))
	for _, d := range darkSchemeDerivations {
		covered[d.name] = struct{}{}
	}

	// Council f17b0a77 round 2, raised independently by bug_historian and
	// guardian: this scanner recognises ONE spelling of the helper call, so a
	// layout written with different whitespace, quoting, argument order or a
	// computed fallback would match nothing and report nothing — "a second
	// silent-fallthrough of the same shape this round is trying to eliminate".
	//
	// Verified 2026-07-27 that the strict pattern matches every call in all 18
	// active layouts (raw `{{palette` occurrences == regexp matches, per
	// layout: 25/25, 24/24, 23/23, 22/22 ×4, 21/21 ×2, 20/20 ×2, 19/19, 18/18
	// ×2, 17/17 ×4). That is true today and is exactly the kind of fact that
	// stops being true quietly, so it is asserted here rather than trusted:
	// a template whose declarations this scanner cannot parse says so.
	rawCalls := strings.Count(layoutTemplate, "{{palette") + strings.Count(layoutTemplate, "{{ palette")
	matches := paletteHelperCall.FindAllStringSubmatch(layoutTemplate, -1)
	if rawCalls > len(matches) {
		logger.Warn("layout declares palette slots in a form this scanner cannot parse — "+
			"the unparsed ones are NOT covered by the light-literal check below, and a slot "+
			"nobody checks is how the original defect survived",
			zap.Int("palette_calls_found", rawCalls),
			zap.Int("parsed", len(matches)),
			zap.Int("unparsed", rawCalls-len(matches)))
	}

	seen := make(map[string]struct{})
	offenders := make([]string, 0)
	for _, m := range matches {
		slot, fallback := m[1], m[2]
		if _, dup := seen[slot]; dup {
			continue
		}
		seen[slot] = struct{}{}
		if v, ok := palette[slot]; ok && v != "" {
			continue // the palette supplies it; the literal is unreachable
		}
		if _, ok := covered[slot]; ok {
			continue // derived above
		}
		// Only a LIGHT literal is a problem on a dark site. A fallback that is
		// itself dark, or is not a plain hex (a gradient, a var(), an rgba),
		// is left alone rather than guessed at.
		if _, _, _, err := parseHexColor(fallback); err != nil {
			continue
		}
		if !isDarkHex(fallback) {
			offenders = append(offenders, slot+"="+fallback)
		}
	}
	if len(offenders) == 0 {
		return
	}
	sort.Strings(offenders)
	logger.Warn("layout declares palette slots this dark palette does not supply, and their "+
		"fallbacks are LIGHT literals — they will ship as-is and are indistinguishable from a "+
		"curated choice in the finished CSS; each is a palette-authoring decision, not a bug "+
		"this renderer can safely guess",
		zap.String("background", bg),
		zap.Int("count", len(offenders)),
		zap.Strings("light_literals", offenders))
}

// pickInkOn returns a foreground for bgHex, preferring a colour already in the
// palette so the site keeps its character, and falling back to black or white
// when nothing in the palette clears AA.
//
// Deliberately distinct from pickReadableOnBackground: that one serves
// --section-* defaults and walks a preference order tuned for section body
// copy. This one is for text on a filled control, where the only question is
// which of the palette's own colours is legible on the fill.
func pickInkOn(bgHex string, palette map[string]string) (hex, source string) {
	for _, key := range []string{"text", "background", "text_muted"} {
		val, ok := palette[key]
		if !ok || val == "" {
			continue
		}
		ratio, err := wcagContrastRatio(val, bgHex)
		if err != nil {
			continue
		}
		if ratio >= inkMinContrast {
			return val, "palette:" + key
		}
	}
	whiteRatio, _ := wcagContrastRatio("#ffffff", bgHex)
	blackRatio, _ := wcagContrastRatio("#000000", bgHex)
	if whiteRatio >= blackRatio {
		return "#ffffff", "fallback:white"
	}
	return "#000000", "fallback:black"
}

// warnUnusablePrimary logs when `primary` cannot be read as a foreground on the
// site's own background.
//
// The component library uses --color-primary as a FOREGROUND (eyebrows, links,
// card titles, section headings) far more often than as a fill — 53 uses
// against 26 on the pages of fundamentallyai.com. A palette whose primary sits
// in the same family as its background therefore renders those invisible while
// every fill still looks correct, so the site reads as "missing text" rather
// than "wrong colour".
//
// Measured fleet-wide 2026-07-27: 4 of 31 palettes score below 1.25:1, all of
// them generated dark palettes (dartsonline.com, fundamentallyai.com,
// robot-hands.com, oufe.com).
//
// This warns rather than fails: unlike a scheme violation, there is no single
// correct repair — the palette's author has to decide whether primary is the
// brand's fill colour or its foreground colour. The discovery check
// `palette_primary_unreadable` files it as durable work.
func warnUnusablePrimary(palette map[string]string, logger *zap.Logger) {
	primary, okP := palette["primary"]
	bg, okB := palette["background"]
	if !okP || !okB || primary == "" || bg == "" {
		return
	}
	ratio, err := wcagContrastRatio(primary, bg)
	if err != nil {
		return
	}
	if ratio >= 3.0 {
		return
	}
	logger.Warn("palette primary is unusable as a foreground on its own background — "+
		"every component that colours an eyebrow, link or card title with --color-primary "+
		"will render it near-invisible; fills using primary are unaffected, so this looks "+
		"like missing text rather than a colour fault",
		zap.String("primary", primary),
		zap.String("background", bg),
		zap.Float64("contrast_ratio", ratio),
		zap.Float64("minimum", 3.0))
}
