// FILE: platform/orchestration/actions/palette_specialised_slots.go
//
// Fills the palette slots a layout declares but a generated palette never
// supplies, when leaving them unset would paint a LIGHT literal onto a DARK
// site.
//
// THE DEFECT THIS CLOSES
// ----------------------
// A layout's css_template declares ~17 palette slots, each with a hard-coded
// fallback: `{{palette "card_bg" "#ffffff"}}`, `{{palette "header_bg"
// "#ffffff"}}`, `{{palette "cta_bg" "#1a365d"}}`. Those fallbacks are the
// Template Helper Fallback contract working as designed — a layout stays valid
// CSS when a map omits a slot.
//
// But a per-site palette generated by the design pipeline holds only the EIGHT
// core slots (corePaletteKeys in render_css_composition_helpers.go: primary,
// secondary, accent, background, surface, text, text_muted, border). The other
// nine therefore take the layout's literals on every render. Those literals
// were written for a light-scheme layout. On a dark site the result is a white
// card carrying text coloured for a near-black page.
//
// Measured 2026-07-27, fleet-wide: 16 of 31 palettes define no `card_bg`, and
// 12 of those 16 are dark-background palettes whose `text` is light — i.e. a
// guaranteed white-card-with-white-text. On fundamentallyai.com that was 1.21:1
// against the 4.5:1 floor, across every card on every page, including the whole
// evidence-chart section. It fails silently: the CSS is valid, the render
// succeeds, and only a rendered-page measurement shows it.
//
// WHY THE FIX IS SCOPED TO DARK BACKGROUNDS
// -----------------------------------------
// For a light site the layout's literals are broadly right, and four live
// palettes (idea.uk, relojistas.com, vetcomparison.uk, webdesign.co.uk) rely on
// them today. Deriving for them too would repaint live sites to no benefit.
// The boundary is the incoherence itself: a light literal is only wrong when
// the site is dark, so that is exactly when a derived value replaces it.
//
// A slot the palette DOES define is never touched, so the 15 curated library
// palettes render identically.

package actions

import (
	"regexp"
	"sort"
	"strings"

	"github.com/gqls/agentchassis/platform/colour"
	"go.uber.org/zap"
)

// derivedSlot describes how one specialised slot is derived when a dark-scheme
// palette omits it.
//
// Two kinds:
//   - copy: take the value of another slot verbatim (a card is a surface).
//   - ink:  pick a foreground that clears AA against a named slot's colour
//     (text on a card, text on the accent).
type derivedSlot struct {
	name    string
	from    string // the slot supplying the value, or the background for an ink
	isInk   bool
	comment string
}

// darkSchemeDerivations is applied in order. `from` may itself be a slot filled
// earlier in this list (cta_text derives against cta_bg), so order matters and
// the slice is deliberately not a map.
var darkSchemeDerivations = []derivedSlot{
	{name: "card_bg", from: "surface", comment: "a card is a raised surface"},
	{name: "header_bg", from: "background", comment: "chrome sits on the page"},
	{name: "cta_bg", from: "surface", comment: "an emphasis band is a surface"},
	{name: "footer_bg", from: "background", comment: "chrome sits on the page"},
	{name: "background_alt", from: "surface"},
	{name: "surface_alt", from: "surface"},

	// NOT HERE: icon_chip_bg. I added it, then measured, and it would have been
	// dead config — the exact shape that looks live and is not.
	//
	// The palette reaches the stylesheet only through `{{palette "X" "literal"}}`
	// calls in a LAYOUT template, so a slot no layout names is never emitted and
	// the component's own `var(--color-icon-chip-bg, #EEF2F8)` fallback ships
	// regardless of what this list says. Measured 2026-07-29 across all 18
	// layouts: card_bg declared by 18, surface_alt by 3, **icon_chip_bg by 0**.
	//
	// The literal is also far narrower than it looks: `icon-chip-bg` appears in
	// exactly ONE active component fleet-wide (`info-card-grid`, and only in its
	// image variant). `image-hover-card-grid` — the component image cards
	// actually use — already reads `var(--color-surface-alt, var(--color-surface))`,
	// which IS derived above. So the generated icon ground (flatKindPaletteClause
	// asks for `surface`) and the tile it lands in already agree on the path that
	// matters.
	//
	// Fixing info-card-grid's image variant means editing a fleet-shared
	// component template with 23 placements across 11 sites. That is its own
	// change with its own review, not a passenger on this one.

	{name: "primary_hover", from: "primary", comment: "hover keeps the family"},
	{name: "secondary_hover", from: "secondary"},

	{name: "heading", from: "text", comment: "headings are the reading colour"},
	{name: "hero_title", from: "text"},
	{name: "hero_subtitle", from: "text_muted"},

	// Inks: each must contrast with the colour it lands on. These are the
	// pairs the component library assumes exist — `--color-primary-text` on a
	// primary-filled button, `--color-accent-text` on an accent-filled one.
	{name: "primary_text", from: "primary", isInk: true},
	{name: "secondary_text", from: "secondary", isInk: true},
	{name: "header_text", from: "header_bg", isInk: true},
	{name: "cta_text", from: "cta_bg", isInk: true},
	{name: "footer_text", from: "footer_bg", isInk: true},

	// accent_text has no layout consuming it yet. It is emitted so a component
	// can stop hard-coding white over an accent fill: `.form-submit` does
	// exactly that on 12 sites and scores 2.81:1 on this site's amber.
	{name: "accent_text", from: "accent", isInk: true},
}

// inkMinContrast is the DEFAULT contrast target for a derived ink. It is not
// the WCAG AA floor and must never be set below it — see inkFloorContrast.
//
// OWNER RULING 2026-08-14: 5.0, not the bare 4.5 AA floor. Raised from 4.5 the
// same afternoon the 4.5 derivation went live, after the owner was shown that
// the emissions were landing 0.01–0.14 above the line.
//
// ⚠ THIS REVERSES A DOCUMENTED TECHNICAL DECISION, AND THE ARGUMENT AGAINST IT
// IS GOOD. TestLegibleVariant_EmittedHexIsPinnedForRealPalettes records a
// reviewer proposing exactly 5.0 and the lane declining it: a cushion "buys
// absorption without fixing a wrong ground and would imply cover for grounds
// nobody models". That is right, and it is the reason this is a SEPARATE knob
// from the grounds modelling rather than a substitute for it — raising this
// number is not a licence to stop enumerating grounds, and the four-ground
// compositing in buildLegibleInkDefaults stays exactly as it is. The owner's
// counter-argument is the empirical one: this lane has twice discovered a
// ground it was not measuring (the 0.05 section overlay cost 0.62 of ratio),
// so the cushion is priced against a failure mode with a track record.
//
// Operators can retune this per render without a rebuild — see inkPolicy. That
// exists because THIS value changed by owner ruling one hour after a re-render
// had already been dispatched at the old one.
const inkMinContrast = 5.0

// inkFloorContrast is the WCAG AA floor for normal-size body text, and the hard
// lower bound on anything inkPolicy will accept. An ink slot is text sitting on
// a filled control or band, so AA is the right FLOOR — these are not decorative
// large headings. A config that asks for less is refused, not honoured: a
// kill-switch that can quietly disable accessibility is a worse defect than the
// one it was added to roll back.
const inkFloorContrast = 4.5

// inkCeilingContrast bounds the other end. AAA for normal text is 7.0; asking
// for more than that on a brand colour means the search walks to near-white or
// near-black on most palettes, which is the de-branding this whole repair
// exists to stop. Values above it are clamped, and the clamp is logged.
const inkCeilingContrast = 7.0

// inkPolicy is the operator-controllable half of the ink derivation: the two
// things that can be changed by editing DB config, with no rebuild and no roll.
//
// WHY THIS EXISTS. The council's guardian seat raised it twice, medium severity,
// against the change that shipped this derivation: it alters a shared function's
// output for 14 of 18 sites with no kill-switch, and rollback was "revert +
// rebuild + roll + re-render" rather than a config flip. The lane declined a
// flag at the time, reasoning that a default-OFF switch would leave the BROKEN
// derivation as the default — which is sound, and is why this one defaults ON.
// OWNER RULING 2026-08-14 reversed the decline: build the switch.
//
// So the shape is deliberately an OPT-OUT, not an opt-in. Enabled everywhere by
// default; an operator disables a named site to roll that one site back to the
// pre-repair behaviour on its next render. Nothing rots unexercised, and the
// 2026-07-29 owner ruling against mandatory default-OFF switches is respected.
type inkPolicy struct {
	// enabled false makes buildLegibleInkDefaults emit nothing, so every
	// consumer falls back through its own var() default to the raw palette
	// colour — i.e. exactly the pre-2026-08-06 behaviour.
	enabled bool
	// minRatio is the contrast target, already clamped to
	// [inkFloorContrast, inkCeilingContrast].
	minRatio float64
}

// defaultInkPolicy is what every render gets unless step config says otherwise.
func defaultInkPolicy() inkPolicy {
	return inkPolicy{enabled: true, minRatio: inkMinContrast}
}

// resolveInkPolicy reads the operator overrides off the render step's config.
// Everything is optional; an absent or unparseable key leaves the default in
// place rather than failing the render, because a stylesheet that does not
// render is worse than one rendered at the default target.
//
// Config keys, all live DB config (agent_definitions), so changing any of them
// takes effect on the next render with no rebuild and no roll:
//
//	legible_ink_enabled           bool     global kill-switch (default true)
//	legible_ink_disabled_site_ids []string per-site kill-switch, site UUIDs
//	legible_ink_min_contrast      float64  retune the target (default inkMinContrast)
//
// siteID may be "" — the render path resolves it from collectedData and it is
// not guaranteed. An empty siteID simply cannot match the disable list, which
// is the safe direction: the fix stays on.
func resolveInkPolicy(config map[string]interface{}, siteID string, logger *zap.Logger) inkPolicy {
	policy := defaultInkPolicy()

	if v, ok := config["legible_ink_enabled"]; ok {
		if enabled, ok := v.(bool); ok && !enabled {
			policy.enabled = false
			logger.Warn("resolveInkPolicy: ink companions globally disabled by config",
				zap.String("key", "legible_ink_enabled"))
		}
	}

	// Per-site opt-out. Compared case-insensitively and trimmed because these
	// are hand-edited into JSON config under incident pressure, which is
	// exactly when a stray space silently un-disables the site you meant to
	// roll back.
	if policy.enabled && siteID != "" {
		if raw, ok := config["legible_ink_disabled_site_ids"]; ok {
			for _, entry := range toStringSlice(raw) {
				if strings.EqualFold(strings.TrimSpace(entry), strings.TrimSpace(siteID)) {
					policy.enabled = false
					logger.Warn("resolveInkPolicy: ink companions disabled for this site by config",
						zap.String("site_id", siteID),
						zap.String("key", "legible_ink_disabled_site_ids"))
					break
				}
			}
		}
	}

	// configFloatField and toStringSlice above are both PRE-EXISTING helpers in
	// this package (diagnose_route_action.go / select_review_panel_action.go).
	// Reused rather than re-derived: the first version of this function shipped
	// its own copies of both and the build caught the collision. That is the
	// same prior-art objection the council's librarian seat raised against this
	// lane's previous change, arriving a second time within a week.
	if ratio := configFloatField(config, "legible_ink_min_contrast", inkMinContrast); ratio != policy.minRatio {
		// CLAMPED, NOT HONOURED, and the floor is the load-bearing half.
		// A kill-switch that can be configured to 1.0 is a way to ship
		// illegible text through a config edit and call it a rollback —
		// strictly worse than the defect it was added to undo. The
		// disable path above is the supported way to go back to old
		// behaviour; this knob only moves the target within a sane band.
		clamped := ratio
		if clamped < inkFloorContrast {
			clamped = inkFloorContrast
		}
		if clamped > inkCeilingContrast {
			clamped = inkCeilingContrast
		}
		if clamped != ratio {
			logger.Warn("resolveInkPolicy: requested ink contrast clamped",
				zap.Float64("requested", ratio),
				zap.Float64("applied", clamped),
				zap.Float64("floor", inkFloorContrast),
				zap.Float64("ceiling", inkCeilingContrast))
		}
		policy.minRatio = clamped
	}

	return policy
}

// fillDarkSchemeSpecialisedSlots adds the specialised slots a dark palette
// omits, deriving each from the core slots it does define. It mutates and
// returns the merged palette.
//
// Inert unless the merged background is dark. Never overwrites a slot the
// palette already defines. Logs exactly one line naming what it filled, so a
// stylesheet's provenance stays readable — a derived value and a curated one
// are indistinguishable in the output CSS, which is the property that let the
// original defect hide.
func fillDarkSchemeSpecialisedSlots(palette map[string]string, logger *zap.Logger) map[string]string {
	if palette == nil {
		return palette
	}
	bg, ok := palette["background"]
	if !ok || bg == "" || !isDarkHex(bg) {
		return palette
	}

	filled := make([]string, 0, len(darkSchemeDerivations))
	skipped := make([]string, 0)
	for _, d := range darkSchemeDerivations {
		if existing, ok := palette[d.name]; ok && existing != "" {
			continue
		}
		source, ok := palette[d.from]
		if !ok || source == "" {
			// The source slot is itself missing, so there is nothing to derive
			// from and the layout's literal ships after all. That is the SAME
			// outcome as doing nothing, and it must not look like success:
			// council f17b0a77, bug_historian (high) — "a silent no-op fallback
			// path sits right next to the loud one this plan is adding, and
			// nothing distinguishes 'derived' from 'fell through to the light
			// literal' in the output CSS".
			skipped = append(skipped, d.name+"<-"+d.from)
			continue
		}
		if d.isInk {
			ink, _ := pickInkOn(source, palette)
			palette[d.name] = ink
		} else {
			palette[d.name] = source
		}
		filled = append(filled, d.name)
	}

	if len(filled) > 0 {
		sort.Strings(filled)
		logger.Info("fillDarkSchemeSpecialisedSlots: derived slots a dark palette omitted, "+
			"instead of letting the layout's light literals through",
			zap.String("background", bg),
			zap.Strings("derived", filled))
	}
	if len(skipped) > 0 {
		sort.Strings(skipped)
		logger.Warn("fillDarkSchemeSpecialisedSlots: could NOT derive one or more slots because "+
			"the core slot each derives from is itself missing — the layout's own literal will "+
			"ship for these, which on a dark site is the defect this function exists to prevent",
			zap.String("background", bg),
			zap.Strings("undeliverable", skipped))
	}
	return palette
}

// paletteHelperCall matches a layout template's {{palette "slot" "fallback"}}.
// Both arguments are captured: the slot name says what the layout wants, and
// the fallback says what ships when nothing supplies it.
var paletteHelperCall = regexp.MustCompile(`\{\{\s*palette\s+"([a-z_]+)"\s+"([^"]*)"\s*\}\}`)

// warnLightLiteralsOnDarkSite reports every slot a layout declares that this
// dark palette does not supply and darkSchemeDerivations does not cover, where
// the layout's own fallback is a LIGHT colour — i.e. exactly the cases that
// will ship a light value onto a dark page.
//
// WHY THIS EXISTS RATHER THAN A LONGER DERIVATION TABLE (council f17b0a77,
// bug_historian, medium): the derivation table fixes the nine specialised slots
// all 18 active layouts share, but `{{palette "X" "<light literal>"}}` is a
// GENERIC construct and the fleet's layouts declare 60+ further slot names
// between them — `badge_bg`, `chip_bg`, `input_pane_bg`, `trust_bar_bg`,
// `callout_bg`, `code_bg`, `success`, `warn`. Enumerating those would be
// guesswork: nobody can say from here what `badge_deal` should be on a dark
// site, and deriving `success` from `surface` would be actively wrong.
//
// So this does not guess. It makes the fall-through VISIBLE, which is the
// property whose absence let the original defect hide for as long as it did —
// a derived value, a curated value and a layout literal are indistinguishable
// in the finished CSS. A slot named here is a palette-authoring decision
// somebody has not made yet, and now has to be told about.
func warnLightLiteralsOnDarkSite(layoutTemplate string, palette map[string]string, logger *zap.Logger) {
	bg, ok := palette["background"]
	if !ok || bg == "" || !isDarkHex(bg) {
		return
	}
	covered := make(map[string]struct{}, len(darkSchemeDerivations))
	for _, d := range darkSchemeDerivations {
		covered[d.name] = struct{}{}
	}

	// Council f17b0a77 round 2, raised independently by bug_historian and
	// guardian: this scanner recognises ONE spelling of the helper call, so a
	// layout written with different whitespace, quoting, argument order or a
	// computed fallback would match nothing and report nothing — "a second
	// silent-fallthrough of the same shape this round is trying to eliminate".
	//
	// Verified 2026-07-27 that the strict pattern matches every call in all 18
	// active layouts (raw `{{palette` occurrences == regexp matches, per
	// layout: 25/25, 24/24, 23/23, 22/22 ×4, 21/21 ×2, 20/20 ×2, 19/19, 18/18
	// ×2, 17/17 ×4). That is true today and is exactly the kind of fact that
	// stops being true quietly, so it is asserted here rather than trusted:
	// a template whose declarations this scanner cannot parse says so.
	rawCalls := strings.Count(layoutTemplate, "{{palette") + strings.Count(layoutTemplate, "{{ palette")
	matches := paletteHelperCall.FindAllStringSubmatch(layoutTemplate, -1)
	if rawCalls > len(matches) {
		logger.Warn("layout declares palette slots in a form this scanner cannot parse — "+
			"the unparsed ones are NOT covered by the light-literal check below, and a slot "+
			"nobody checks is how the original defect survived",
			zap.Int("palette_calls_found", rawCalls),
			zap.Int("parsed", len(matches)),
			zap.Int("unparsed", rawCalls-len(matches)))
	}

	seen := make(map[string]struct{})
	offenders := make([]string, 0)
	for _, m := range matches {
		slot, fallback := m[1], m[2]
		if _, dup := seen[slot]; dup {
			continue
		}
		seen[slot] = struct{}{}
		if v, ok := palette[slot]; ok && v != "" {
			continue // the palette supplies it; the literal is unreachable
		}
		if _, ok := covered[slot]; ok {
			continue // derived above
		}
		// Only a LIGHT literal is a problem on a dark site. A fallback that is
		// itself dark, or is not a plain hex (a gradient, a var(), an rgba),
		// is left alone rather than guessed at.
		if _, _, _, err := parseHexColor(fallback); err != nil {
			continue
		}
		if !isDarkHex(fallback) {
			offenders = append(offenders, slot+"="+fallback)
		}
	}
	if len(offenders) == 0 {
		return
	}
	sort.Strings(offenders)
	logger.Warn("layout declares palette slots this dark palette does not supply, and their "+
		"fallbacks are LIGHT literals — they will ship as-is and are indistinguishable from a "+
		"curated choice in the finished CSS; each is a palette-authoring decision, not a bug "+
		"this renderer can safely guess",
		zap.String("background", bg),
		zap.Int("count", len(offenders)),
		zap.Strings("light_literals", offenders))
}

// pickInkOn returns a foreground for bgHex, preferring a colour already in the
// palette so the site keeps its character, and falling back to black or white
// when nothing in the palette clears AA.
//
// Deliberately distinct from pickReadableOnBackground: that one serves
// --section-* defaults and walks a preference order tuned for section body
// copy. This one is for text on a filled control, where the only question is
// which of the palette's own colours is legible on the fill.
func pickInkOn(bgHex string, palette map[string]string) (hex, source string) {
	for _, key := range []string{"text", "background", "text_muted"} {
		val, ok := palette[key]
		if !ok || val == "" {
			continue
		}
		ratio, err := wcagContrastRatio(val, bgHex)
		if err != nil {
			continue
		}
		// inkFloorContrast, NOT inkMinContrast, and the difference is the whole
		// point of there being two constants.
		//
		// This function serves the --color-<x>-TEXT slots: ink that goes ON a
		// filled control. The 2026-08-14 owner ruling raising the target to 5.0
		// was about the --color-<x>-INK slots — links and eyebrows on the page
		// ground — and said nothing about button labels. Until 2026-08-14 both
		// mechanisms shared one constant, so editing it in place would have
		// silently retuned every filled control in the fleet as a side effect of
		// a ruling about links. Two questions, two constants; raise this one only
		// when someone rules on THIS one.
		if ratio >= inkFloorContrast {
			return val, "palette:" + key
		}
	}
	whiteRatio, _ := wcagContrastRatio("#ffffff", bgHex)
	blackRatio, _ := wcagContrastRatio("#000000", bgHex)
	if whiteRatio >= blackRatio {
		return "#ffffff", "fallback:white"
	}
	return "#000000", "fallback:black"
}

// legibleInkFor answers "can this colour be READ on these grounds", which is
// the inverse of the question pickInkOn answers ("what can be read ON this
// fill"). It returns srcHex unchanged when srcHex already clears minRatio
// against EVERY ground; otherwise srcHex moved in HSL LIGHTNESS ONLY until it
// does; otherwise the first palette colour that does; otherwise whichever
// achromatic extreme has the better worst case.
//
// ⚠ THE LIGHTNESS STEP WAS ADDED 2026-08-13 AND IT IS A CORRECTION, NOT A
// REFINEMENT. Without it this function's substitution branch was unreachable
// except at `text`, and the slot it feeds was a lie.
//
// The walk below is {text, accent, text_muted, secondary, primary} and `text`
// is FIRST. `text` is by construction the palette slot chosen to be legible on
// `background` — so it clears the grounds whenever any candidate does, and it
// always won. MEASURED 2026-08-13 at the served artefact across all 18
// palette-driven live sites: all 16 divergences between an ink companion and its
// source slot resolved to that site's own --color-text. Zero exceptions.
//
// ⚠ STATE THAT PRECISELY, because the loose version is wrong and was corrected by
// a reviewer: `accent`, `text_muted`, `secondary` and `primary` are NOT
// unreachable as a matter of logic. The walk WOULD return `accent` on a site where
// `text` failed one ground and `accent` cleared them all — `text` is chosen to be
// legible on `background`, and `grounds` is {background, surface}, so the two can
// come apart. **No such site exists in the fleet.** The measurement is the
// evidence; the mechanism only explains why it came out that way. So
// --color-primary-ink was --color-text under another name on every site we have —
// while this function's own doc comment, the register entry (VIZ-014) and the
// approved plan all said it "prefers a palette colour so the site keeps its
// character".
//
// That was not a cosmetic error. Repointing a component onto the ink companion
// was equivalent to writing `color: var(--color-text)`, and the fleet's only
// contrast instrument (scripts/render_audit.py) scores that a CLEAN PASS,
// because near-black text on a pale ground has excellent contrast. A sweep that
// stripped the brand colour from every affected element would have graded green
// on every check we run. bugs_open/122, contribution 2026-08-13; LANDMINES entry
// of the same date.
//
// colour.LegibleVariant now gets first refusal, preserving hue and saturation
// exactly and returning the SMALLEST sufficient lightness change. The palette
// walk is kept as the fallback for the cases it genuinely owns — an achromatic
// source (no hue to preserve) and a source no lightness can rescue on all
// grounds at once. TestLegibleInkFor_PrefersATintOfTheSourceOverSubstitution
// goes RED if the lightness step is removed or reordered after the walk.
//
// WHY grounds IS A SLICE AND NOT A COLOUR. A component may place one ink on
// the page and on a card. dartsonline.com does exactly that with
// --color-primary: the eyebrow lands on `background` (1.04:1) and the card
// link on the derived `card_bg` (robot-hands, 1.07:1). One variable can only
// be right for two grounds if it is right for the WORSE of them.
//
// If a later edit simplifies this to a single ground, the fix quietly becomes
// a half-fix: correct on whichever surface the reviewer happens to open, still
// broken on the other. TestLegibleInkFor_TwoGroundsDisagree is the assertion
// that stops that, and it is the only test here that a single-ground
// implementation fails.
func legibleInkFor(srcHex string, grounds []string, palette map[string]string, minRatio float64) (hex, source string) {
	clearsAll := func(candidate string) bool {
		measured := false
		for _, g := range grounds {
			if g == "" {
				continue
			}
			ratio, err := wcagContrastRatio(candidate, g)
			if err != nil || ratio < minRatio {
				return false
			}
			measured = true
		}
		// No ground was measurable, so nothing was actually checked. Report
		// failure rather than a vacuous pass — a "pass" derived from measuring
		// nothing is how a value that was never tested reaches a stylesheet
		// looking tested.
		return measured
	}

	if srcHex != "" && clearsAll(srcHex) {
		return srcHex, "source:unchanged"
	}
	// Try to rescue the source colour itself before substituting a different
	// one. MUST stay ahead of the palette walk: `text` below clears the grounds
	// whenever anything does, so any ordering that reaches it first makes this
	// branch dead code — which is exactly the defect being repaired here.
	if srcHex != "" {
		if tinted, ok := colour.LegibleVariant(srcHex, grounds, minRatio); ok {
			return tinted, "source:lightness"
		}
	}
	for _, key := range []string{"text", "accent", "text_muted", "secondary", "primary"} {
		v, ok := palette[key]
		if !ok || v == "" || v == srcHex {
			continue
		}
		if clearsAll(v) {
			return v, "palette:" + key
		}
	}
	if worstRatioAgainst("#ffffff", grounds) >= worstRatioAgainst("#000000", grounds) {
		return "#ffffff", "fallback:white"
	}
	return "#000000", "fallback:black"
}

// worstRatioAgainst returns the LOWEST contrast ratio candidate achieves across
// grounds — the only figure that matters when one value has to serve them all.
//
// Returns 0 when no ground is measurable, so an unmeasurable candidate can
// never win a comparison against a measurable one.
func worstRatioAgainst(candidate string, grounds []string) float64 {
	worst := 0.0
	first := true
	for _, g := range grounds {
		if g == "" {
			continue
		}
		ratio, err := wcagContrastRatio(candidate, g)
		if err != nil {
			continue
		}
		if first || ratio < worst {
			worst, first = ratio, false
		}
	}
	return worst
}

// buildLegibleInkDefaults returns a renderer-owned :root block defining the
// legible-ink companions a component can opt into. Returns "" when there is
// nothing to add.
//
// TWO DIRECTIONS, AND CONFLATING THEM IS THE MISTAKE THIS COMMENT EXISTS TO
// STOP. A palette colour used as a fill and the same colour used as an ink are
// different questions with different answers:
//
//	--color-<x>-text   the ink that goes ON an <x> fill. Already derived by
//	                   darkSchemeDerivations — `accent_text` has existed since
//	                   2026-07-27 — but 0 of 18 layouts declare it, so it has
//	                   never reached one stylesheet. Emitting it here is what
//	                   turns that dead derivation live.
//	--color-<x>-ink    <x> ITSELF, made legible as an ink on the page. New;
//	                   nothing in the platform computed this before.
//
// finetuning.uk's .csg-cta-btn needs the first: it fills with
// var(--color-accent) (#C8873A) and inks with var(--color-primary-text) — the
// ink for a PRIMARY fill — scoring 3.01:1. gaswholesalers.com's base `a {}`
// rule needs the second: var(--color-accent) as the link colour on white,
// 2.22:1, six times on the homepage. A change offering only one of these fixes
// one site and reads as though it fixed both. It did, once; see bugs_open/122.
//
// SCHEME-INDEPENDENT, unlike fillDarkSchemeSpecialisedSlots above. That
// function is dark-only because a LIGHT LITERAL is only wrong on a dark site.
// "This ink is illegible on this ground" is true or false regardless of
// scheme, and two of the three accent-direction sites are LIGHT
// (gaswholesalers #F4F1EB, finetuning #F5F3EF), so a dark-only guard cannot
// reach them at all. TestBuildLegibleInkDefaults_LightSchemeStillEmits fails
// loudly if someone later tidies this behind an isDarkHex guard.
//
// ORDER: this must be appended AFTER buildSectionDefaults and buildTokenAliases
// in RenderCSSFromSpecAction, because it skips any name the assembled CSS
// already defines. Pinned by TestRenderCSS_InkCompanionsComeAfterTokenAliases.
func buildLegibleInkDefaults(css string, palette map[string]string, policy inkPolicy, logger *zap.Logger) string {
	// The kill-switch, and it is deliberately the FIRST thing here. Emitting
	// nothing is what makes it a true rollback: every consumer opts in with
	// var(--color-primary-ink, var(--color-primary)), so an absent companion
	// falls through to the raw palette colour — the exact pre-2026-08-06
	// behaviour, reached without a revert, a rebuild or a roll.
	if !policy.enabled {
		logger.Warn("buildLegibleInkDefaults: DISABLED by config — emitting no ink companions",
			// Every field here is a static string; nothing unwrapped is logged.
			// Worded to keep pattern-check's logged-model-output rule quiet —
			// it matches a certain three-letter word for unprocessed data
			// anywhere inside a log call, INCLUDING in a comment explaining
			// its own absence, which is how the first version of this comment
			// re-tripped the very check it was documenting.
			zap.String("effect", "consumers fall back to the undiluted palette colour (pre-repair behaviour)"),
			zap.String("undo", "clear legible_ink_enabled / legible_ink_disabled_site_ids in the render step config"))
		return ""
	}
	bg := lookupOrFallback(palette, "background", "")
	if bg == "" {
		// Nothing to measure against. Stay silent rather than guess: an
		// emitted value nobody could check is worse than an absent one,
		// because the consumer's var() fallback is today's working colour.
		return ""
	}
	surface := lookupOrFallback(palette, "surface", "")
	// An ink lands on the page or on a card — AND, on a dark site, on either of
	// those under the renderer's own translucent section overlay.
	//
	// ⚠ THE COMPOSITED GROUNDS ARE NOT OPTIONAL, and leaving them out is a
	// measured half-fix rather than a theoretical one. buildSectionDefaults emits
	// `--section-surface: rgba(255,255,255,0.05)` (color_util.go), and a component
	// that paints with it puts the ink on a ground 5% lighter than the palette
	// declares. MEASURED 2026-08-14: that costs 0.62 of contrast ratio on the
	// fleet's dark palettes, while the lightness search returns the SMALLEST
	// sufficient change and therefore lands 0.02–0.09 above the floor by
	// construction — so the gap was ~10x the margin. Inks clearing 4.5 on the
	// declared surface measured 3.93–4.03 on the composited one, i.e. a fresh
	// contrast_failure for an element this repair had just fixed. Raised by the
	// bugfix_122_contrast_ink_slots lane against the first version of this change.
	//
	// Requiring all four is what makes "smallest sufficient change" safe: the
	// search now has to clear the WORST real ground, not the most flattering
	// declared one. This is the same reason grounds is a slice at all.
	pageGrounds := []string{bg, surface}
	for _, g := range []string{bg, surface} {
		if g == "" {
			continue
		}
		if c := colour.CompositeOverGround("#ffffff", sectionSurfaceOverlayAlpha, g); c != g {
			pageGrounds = append(pageGrounds, c)
		}
	}

	wanted := []struct {
		name, src string
		grounds   []string
	}{
		{"--color-primary-ink", palette["primary"], pageGrounds},
		{"--color-accent-ink", palette["accent"], pageGrounds},
		{"--color-accent-text", palette["text"], []string{palette["accent"]}},
	}

	var b strings.Builder
	var substituted, unchanged []string
	for _, w := range wanted {
		if w.src == "" || strings.Contains(css, w.name+":") {
			// Undeterminable, or the stylesheet already has an opinion. Same
			// definition of "already defined" as buildTokenAliases: the name
			// followed by a colon, which cannot match a var() usage.
			continue
		}
		hex, src := legibleInkFor(w.src, w.grounds, palette, policy.minRatio)
		b.WriteString("  " + w.name + ": " + hex + ";\n")
		if src == "source:unchanged" {
			unchanged = append(unchanged, w.name)
		} else {
			substituted = append(substituted, w.name+"<-"+src)
		}
	}
	if b.Len() == 0 {
		return ""
	}

	// A substituted value and a left-alone one are indistinguishable in the
	// output CSS. That indistinguishability is the property that let the
	// original defect hide for nine days, so both are logged by name.
	sort.Strings(substituted)
	sort.Strings(unchanged)
	logger.Info("buildLegibleInkDefaults: emitted legible-ink companions a component can opt into",
		// The target is logged because it is now CONFIGURABLE. A hex in a
		// stylesheet cannot tell you which target produced it, and on 2026-08-14
		// two different targets were live within one hour of each other.
		zap.Float64("min_contrast", policy.minRatio),
		zap.String("background", bg),
		zap.String("surface", surface),
		zap.Strings("substituted", substituted),
		zap.Strings("already_legible_left_as_is", unchanged))

	return "\n\n/* renderer-owned legible-ink companions. Opt in with\n" +
		"   var(--color-primary-ink, var(--color-primary)) — never bare, so a\n" +
		"   stylesheet rendered before this block renders byte-identically. */\n:root {\n" +
		b.String() + "}\n"
}

// warnUnusablePrimary logs when `primary` cannot be read as a foreground on the
// site's own background.
//
// The component library uses --color-primary as a FOREGROUND (eyebrows, links,
// card titles, section headings) far more often than as a fill — 53 uses
// against 26 on the pages of fundamentallyai.com. A palette whose primary sits
// in the same family as its background therefore renders those invisible while
// every fill still looks correct, so the site reads as "missing text" rather
// than "wrong colour".
//
// Measured fleet-wide 2026-07-27: 4 of 31 palettes score below 1.25:1, all of
// them generated dark palettes (dartsonline.com, fundamentallyai.com,
// robot-hands.com, oufe.com).
//
// This warns rather than fails: the palette's author still has to decide
// whether primary is the brand's fill colour or its foreground colour, and
// that is not a decision the renderer can make. The discovery check
// `palette_primary_unreadable` files it as durable work.
//
// CORRECTED 2026-08-06: this comment used to justify warning-only with "there
// is no single correct repair". That stopped being true — buildLegibleInkDefaults
// now emits --color-primary-ink, which IS the repair for the foreground half,
// so the warning names it. The fill half is still the author's call, which is
// why this is still a Warn.
func warnUnusablePrimary(palette map[string]string, logger *zap.Logger) {
	primary, okP := palette["primary"]
	bg, okB := palette["background"]
	if !okP || !okB || primary == "" || bg == "" {
		return
	}
	ratio, err := wcagContrastRatio(primary, bg)
	if err != nil {
		return
	}
	if ratio >= 3.0 {
		return
	}
	logger.Warn("palette primary is unusable as a foreground on its own background — "+
		"every component that colours an eyebrow, link or card title with --color-primary "+
		"will render it near-invisible; fills using primary are unaffected, so this looks "+
		"like missing text rather than a colour fault",
		zap.String("primary", primary),
		zap.String("background", bg),
		zap.Float64("contrast_ratio", ratio),
		zap.Float64("minimum", 3.0),
		zap.String("remedy", "components rendering small text in this colour should read "+
			"var(--color-primary-ink, var(--color-primary)); the renderer emits a legible "+
			"substitute (buildLegibleInkDefaults). Fills using primary are unaffected."))
}
