-- SQL_2026-08-02_scoped_rerender_seven_contact_pages.sql — bugfix_140_contact_info_fabrication
--
-- NOT a migration (no schema or agent config changes) — a one-off DATA repair, so it
-- lives in the workstream directory rather than taking a sql_for_agents number.
--
-- WHY. Migration 287 stopped `contact-info` fabricating, but the SEVEN remaining live
-- sites still SERVE the invented "Monday – Friday, 9am – 6pm" because a stored render is
-- not regenerated by fixing a template. My first read — that they would self-correct once
-- the stalled page_rerender backlog drained — was REFUTED the same afternoon: the backlog
-- went 294 -> 0, six of the seven ran a COMPLETED page_rerender on their contact page,
-- and not one section updated (ai-agent-orchestration's is still stamped 2026-05-02).
--
-- THE DISCRIMINATOR, read from the live page-rerender agent's own router
-- (`check_rerender_mode`), not inferred:
--
--   condition: input_data.spec.reason == 'image_landed'
--           OR input_data.spec.reason == 'section_data_resolved'
--           OR input_data.spec.reason == 'cta_links_stale'
--   then_step: rerender_sections  -> rerender_page_sections  (REGENERATES from template)
--   else_step: render_page        -> rerender_single_page    (assembles STORED html)
--
-- So the consumer routes on `spec.reason` ALONE. The `&& componentIDStr != ""` clause in
-- create_rerender_items_action.go:219 is a PRODUCER-side gate deciding when that creator
-- stamps the reason; it is not a condition the page-rerender agent applies. Items created
-- here therefore need only the reason — matching the shape of the scoped items already
-- observed working on vetcomparison.uk.
--
-- WHAT IT DOES. One `page_rerender` work item per affected contact page, seven in total,
-- each carrying reason='section_data_resolved' so it takes the rerender_sections branch.
-- Blast radius is one page's sections each — the narrowest repair available (CGV-001).
--
-- WHAT IT DOES NOT DO. It does not touch page_components directly. Per-instance patching
-- was 140's own fix candidate 3 and is the wrong tool: it competes with the render path
-- rather than using it, and it would need redoing on the next legitimate rerender.
--
-- OTHER LANES. Six of these seven sites belong to other lanes. This is a write against
-- their live output and was authorised explicitly by the owner (2026-08-02) after the
-- earlier decision to hold off — taken when the queue was stalled — was invalidated by
-- the queue draining without repairing anything.
--
-- ROLLBACK: DELETE FROM site_work_items WHERE item_key LIKE 'bug140_contact_rerender:%';
--   (safe only while they are still `triaged`; once claimed, let them finish.)

BEGIN;

INSERT INTO site_work_items
    (site_id, page_id, item_type, source, pipeline, severity, priority,
     handler_agent, status, item_key, created_by, summary, spec)
SELECT p.site_id,
       p.id,
       'page_rerender',
       'bugfix_140',
       'build',
       'high',
       10,
       'page-rerender',
       'triaged',
       'bug140_contact_rerender:' || p.id::text,
       'bugfix-140',
       'bugs_open/140: re-render contact sections so the repaired contact-info template replaces the fabricated phone/hours',
       jsonb_build_object(
           'domain',    s.domain,
           'reason',    'section_data_resolved',
           'page_id',   p.id::text,
           'page_name', p.name,
           'filename',  COALESCE(NULLIF(ltrim(p.url,'/'),''), p.name || '.html')
       )
  FROM page_components pc
  JOIN pages p ON p.id = pc.page_id
  JOIN sites s ON s.id = p.site_id
  JOIN content_components cc ON cc.id = pc.component_id
 WHERE cc.function = 'contact-info'
   AND pc.locked_at IS NULL
   -- Only pages still carrying the fabrication. Self-limiting: re-running this file
   -- after the repair inserts nothing, and it cannot touch a page already corrected.
   AND pc.rendered_html LIKE '%Monday%9am%6pm%'
ON CONFLICT DO NOTHING;

DO $guard$
DECLARE
    n_items int;
    n_bad   int;
    n_left  int;
BEGIN
    SELECT count(*) INTO n_items FROM site_work_items
     WHERE item_key LIKE 'bug140_contact_rerender:%';

    SELECT count(*) INTO n_left FROM page_components pc
      JOIN content_components cc ON cc.id = pc.component_id
     WHERE cc.function='contact-info' AND pc.locked_at IS NULL
       AND pc.rendered_html LIKE '%Monday%9am%6pm%';

    -- One item per still-fabricating page, and no more.
    IF n_items <> n_left THEN
        RAISE EXCEPTION '140: expected 1 item per fabricating page (% pages), found % items',
                        n_left, n_items;
    END IF;

    -- Every item must carry the reason that routes it to rerender_sections. Without it
    -- the agent takes render_page and redeploys the stale HTML — the exact no-op this
    -- file exists to avoid, and the thing I got wrong the first time.
    SELECT count(*) INTO n_bad FROM site_work_items
     WHERE item_key LIKE 'bug140_contact_rerender:%'
       AND COALESCE(spec->>'reason','') <> 'section_data_resolved';
    IF n_bad > 0 THEN
        RAISE EXCEPTION '140: % item(s) lack reason=section_data_resolved and would deploy stale HTML', n_bad;
    END IF;

    RAISE NOTICE '140: % scoped page_rerender item(s) queued for the fabricating contact pages', n_items;
END
$guard$;

COMMIT;
