apiVersion: v1
kind: Service
metadata:
  name: render-audit-adapter
  labels:
    app: render-audit-adapter
spec:
  type: ClusterIP
  selector:
    app: render-audit-adapter
  ports:
    - port: 8080
      targetPort: 8080
      name: http
