// internal/adapters/imagegenerator/routing.go
//
// bugs_open/011 R1 — image provider routing policy, as data plus one pure
// function. Kept out of dynamic_adapter.go deliberately: routing is decided
// per request and had, until this file existed, no test that did not require a
// Kafka consumer and two live provider clients.
//
// WHY THIS IS A TABLE AND NOT A SWITCH. The previous form was a hand-maintained
// switch whose `default:` branch silently routed to Stability. That default is
// the mechanism behind two separate shipped defects — content_hero (found at
// the D13 card gate) and then hero (bugs_open/011, found when a gibberish
// diagram shipped as a client homepage). In both cases the kind simply was
// never added to the Banana branch, and nothing anywhere said so: generation
// reported success, brand anchors were dropped without a word, and the defect
// surfaced only when a human looked at the image.
//
// A table makes the routed set enumerable, so "is this kind routed?" is a
// question the code can actually ask — which is what lets routeProvider flag an
// unmigrated kind instead of quietly serving it from the weaker provider.
// Adding a kind is still a code change; noticing that you forgot is no longer
// left to chance.
package imagegenerator

import (
	"sort"
	"strings"
)

// Provider names as they appear in routing decisions and in the
// imagery_style_guide's `provider` field. These are the only two accepted
// spellings — aliases were considered and dropped (council gate e996bf0a,
// editquality): the field is written by planners and humans against this
// documented contract, so an alias set is surface area with no caller.
const (
	providerBanana    = "banana"
	providerStability = "stability"
)

// kindProviderRouting maps an image kind to the provider that serves it.
//
// Everything with a declared kind is on Banana: it renders legible text, holds
// a flat-illustration house style, and is the only provider that honours
// ReferenceImageURIs — without which per-site brand anchoring is structurally
// impossible, not merely degraded.
//
// The migration happened one kind at a time as each was found to be wrong:
//   - logo/illustration/infographic — 2026-07-10. A site's logo is the
//     reference image every other asset anchors to, so it has to be generated
//     by the provider that reads reference images (RUNNING_NOTES.md turn 4
//     decision A6; AUDIT_verified_facts.md C5).
//   - sprite_sheet — Phase I2. One coherent N×M grid of flat glyphs; Banana's
//     gridded-composition tendency is the feature.
//   - content_hero — Phase I3.1 (D14), after the D13 card gate failed on style
//     drift: SDXL ignores free-text style direction at card size.
//   - hero — 2026-07-18 (bugs_open/011). The last kind left behind, and left
//     by omission rather than decision. It was also the largest: 84 of 155
//     site_plan_imagery rows. Sites that genuinely want SDXL heroes set
//     provider:"stability" in their imagery_style_guide — data, not code.
var kindProviderRouting = map[string]string{
	"icon":         providerBanana,
	"logo":         providerBanana,
	"illustration": providerBanana,
	"infographic":  providerBanana,
	"sprite_sheet": providerBanana,
	"content_hero": providerBanana,
	"hero":         providerBanana,
}

// routingDecision is the outcome of routeProvider: which provider serves the
// request, and what the caller should warn about.
type routingDecision struct {
	// Provider is the resolved provider name (providerBanana | providerStability).
	Provider string

	// BadHint is true when a non-empty provider_hint was not understood. The
	// request still routes (by kind), because a typo in one site's style guide
	// must not take out image generation for that site.
	BadHint bool

	// UnmigratedKind is true when a non-empty kind is absent from
	// kindProviderRouting and therefore fell back to Stability. This is the
	// content_hero/hero failure shape and always deserves a loud warning.
	// An EMPTY kind sets MissingKind instead — a different defect with a
	// different fix (see below), so they are separate flags.
	UnmigratedKind bool

	// MissingKind is true when the request carried NO kind at all and the
	// table therefore could not decide. bugs_open/382.
	//
	// This flag, and the Banana default that goes with it, REPLACE a
	// documented exemption that was measured and refuted. Until 2026-08-24
	// this file asserted that "legacy callers that predate the field are a
	// documented, deliberate Stability path, not an oversight", routed them
	// to Stability, and reported nothing. The measurement says otherwise:
	// **15** hero assets on 5 sites (as of 2026-08-24) were generated by SDXL
	// after bugs_open/011's routing fix, the latest on 2026-08-11; NONE of
	// those sites carries the
	// sanctioned provider:"stability" opt-out in its imagery_style_guide, and
	// no live agent definition pins a Stability model. The traffic through
	// this branch was neither legacy nor deliberate — it was image-build-
	// handler's own hero-variant branch, which forwards no kind because the
	// `default_kind` key that looks like its safety net sits at the step
	// CONFIG level and is read by nothing (bugs_open/382 §2).
	//
	// So the default now goes to the STRONG provider and says so. A caller
	// that genuinely wants Stability still says provider:"stability" — data,
	// not code — exactly like everyone else, and the hint still wins.
	MissingKind bool
}

// routeProvider decides which provider serves a request.
//
// Precedence, highest first:
//  1. An explicit, understood provider_hint — the site's own preference,
//     resolved from its imagery_style_guide by GenerateImageAction. The
//     adapter has no DB access, so this is the only way site context reaches
//     the routing decision.
//  2. The kind's entry in kindProviderRouting.
//  3. A kind that is present but unrouted falls back to Stability, flagged
//     via UnmigratedKind — that means the kind was never added to the table.
//  4. NO kind at all resolves to Banana, flagged via MissingKind. The absent
//     case is a caller defect, not a provider preference, and the safe answer
//     to "nobody said" is the provider that renders text and honours
//     reference images. It is flagged so the caller can be found and fixed
//     rather than silently carried (bugs_open/382).
func routeProvider(kind, providerHint string) routingDecision {
	switch strings.ToLower(strings.TrimSpace(providerHint)) {
	case "":
		// No preference; fall through to kind routing.
	case providerBanana:
		return routingDecision{Provider: providerBanana}
	case providerStability:
		// A deliberate opt-out — e.g. a photographic site keeping SDXL heroes.
		// Not an unmigrated kind: someone chose this.
		return routingDecision{Provider: providerStability}
	default:
		// Understood as "no usable preference", but the caller warns.
		d := routeProvider(kind, "")
		d.BadHint = true
		return d
	}

	trimmedKind := strings.TrimSpace(kind)
	if p, ok := kindProviderRouting[trimmedKind]; ok {
		return routingDecision{Provider: p}
	}
	if trimmedKind == "" {
		// No kind supplied. Route to the strong provider and flag it.
		return routingDecision{Provider: providerBanana, MissingKind: true}
	}
	return routingDecision{
		Provider:       providerStability,
		UnmigratedKind: true,
	}
}

// knownRoutedKinds returns the routed kinds, sorted — for the unmigrated-kind
// warning, so the log line itself tells whoever reads it what the valid set is
// rather than sending them to the source.
func knownRoutedKinds() []string {
	kinds := make([]string, 0, len(kindProviderRouting))
	for k := range kindProviderRouting {
		kinds = append(kinds, k)
	}
	sort.Strings(kinds)
	return kinds
}

// reportedConditions turns a routing decision's warning flags into condition
// records for the response body's `reported_conditions` field, which the
// chassis coordinator persists to agent_error_log (persistReportedConditions,
// platform/orchestration/agent_error_log.go). That field name is the entire
// coupling between the two services.
//
// Council residual from bugs_open/011 R1 (gate e996bf0a, bug_historian): a
// warning that lives only in a pod log depends on someone tailing the right
// pod at the right moment — this repo's history says that is how defects
// survive for months. The adapter cannot persist these itself (it has no DB
// handle, deliberately), and the action layer must not re-derive them (it
// would be predicting a routing table deployed in a different binary — the
// dedup-index↔Go-list drift class). So: this binary DETECTS, against the
// table it actually ships; the chassis, which has the DB and the
// orchestration context, RECORDS.
//
// referenceCount is how many ReferenceImageURIs the request carried; the
// anchors-dropped condition is the same warn-then-forget class as the other
// two, detected from the same decision.
func reportedConditions(d routingDecision, kind, providerHint, prompt string, referenceCount int) []map[string]interface{} {
	var conditions []map[string]interface{}

	if d.UnmigratedKind {
		conditions = append(conditions, map[string]interface{}{
			"code":     "UNROUTED_IMAGE_KIND",
			"severity": "warning",
			"message": "image kind \"" + kind + "\" is not in kindProviderRouting and fell back to Stability, " +
				"which cannot render legible text and ignores reference images; " +
				"add it to the routing table if that is not what you want",
			"context": map[string]interface{}{
				"kind":         kind,
				"provider":     d.Provider,
				"routed_kinds": knownRoutedKinds(),
			},
		})
	}

	// bugs_open/382 — the ABSENT case. Its record is deliberately shaped for
	// the reader who has to find the caller: the row lands on the
	// image-generator's own orchestration (the adapter replies to it), so the
	// step that actually omitted the field is one hop away in the parent. The
	// prompt's opening words are the cheapest identifier the adapter has for
	// which producer built this request, so they travel with it, bounded.
	if d.MissingKind {
		promptHint := promptOpening(prompt)
		conditions = append(conditions, map[string]interface{}{
			"code":     "MISSING_IMAGE_KIND",
			"severity": "warning",
			"message": "image request carried NO kind, so the routing table could not decide; " +
				"it was served by " + providerBanana + " (the strong default) and the CALLER is what needs fixing — " +
				"a call_agent step reaches this action only through its input_mapping, so `kind` must be mapped there " +
				"(a `default_kind` key in the step config is read by nothing)",
			"context": map[string]interface{}{
				"provider":       d.Provider,
				"provider_hint":  providerHint,
				"routed_kinds":   knownRoutedKinds(),
				"prompt_opening": promptHint,
			},
		})
	}

	if d.BadHint {
		conditions = append(conditions, map[string]interface{}{
			"code":     "UNRECOGNISED_PROVIDER_HINT",
			"severity": "warning",
			"message": "provider_hint \"" + providerHint + "\" is not a recognised provider; " +
				"the request fell back to kind routing — fix the imagery_style_guide's provider field " +
				"(accepted: \"" + providerBanana + "\", \"" + providerStability + "\")",
			"context": map[string]interface{}{
				"kind":          kind,
				"provider_hint": providerHint,
				"provider":      d.Provider,
			},
		})
	}

	if referenceCount > 0 && d.Provider != providerBanana {
		conditions = append(conditions, map[string]interface{}{
			"code":     "REFERENCE_ANCHORS_DROPPED",
			"severity": "warning",
			"message": "request carried reference images but resolved to a provider that ignores them — " +
				"per-site brand anchoring was silently lost for this asset",
			"context": map[string]interface{}{
				"kind":            kind,
				"provider":        d.Provider,
				"reference_count": referenceCount,
			},
		})
	}

	return conditions
}

// promptOpening returns a bounded opening slice of a prompt, for the
// MISSING_IMAGE_KIND record's context.
//
// Why it is here at all: the adapter is the only place that KNOWS the kind was
// missing, and the only place that does NOT know who asked. The condition row
// it produces is written against the image-generator's own orchestration, whose
// collected_data holds nothing the chassis's error-context builder recognises
// (no item_type, no page_name, no spec.category), and orchestration_states is
// reaped in about a day — so "walk up to the parent" stops working overnight.
// The first few words of a prompt are stable per producer and are enough to
// tell a hero-variant request from a logo one without any join.
//
// Bounded because a condition record is not a place to copy a prompt to: the
// coordinator caps the number of conditions per response, not their size.
func promptOpening(prompt string) string {
	const maxPromptOpening = 120
	p := strings.TrimSpace(prompt)
	if len(p) <= maxPromptOpening {
		return p
	}
	return p[:maxPromptOpening] + "…"
}
