-- p4_03_lock_guide_patents.sql — lock the authored patents guide + the guides-hub copy.
--
-- RUN ONLY AFTER both pages are verified LIVE (p4_01 guide, p4_02 hub listing).
--
-- WHY LOCK THIS AND NOT JUST ANY PAGE. The patents guide body is HAND-AUTHORED UK legal guidance
-- (see the reasoning in p4_01's header): the platform's evidence gate for factual claims
-- (claims-verification V5) is built but INERT, and bugs_open/043 is a live fabricated-content lane.
-- An LLM copy pass over this page would not merely change the tone — it would generate legal
-- assertions with nothing behind them, on a live commercial site, under a heading that invites the
-- reader to rely on them. That is the single highest-consequence content on idea.uk.
--
-- WHAT THE LOCK ACTUALLY BUYS, stated honestly (same limits as p3_06):
--   * It protects against the likely clobbers: rebuild, re-plan, and an LLM copy rewrite.
--   * It does NOT stop a reason='cta_links_stale' rerender, which runs applyCTARecompute and merges
--     recomputed CTA targets LAST, overriding stored content_data — the generic resolver picks a
--     content hub, not /report.html. Same trap as the home page; the doc_note below extends the
--     existing warning to these two pages.
--   * bugs_open/058 (component lock gate) is COMMITTED but NOT YET LIVE, so lock enforcement is
--     incomplete across paths until that image rolls. The lock is still worth setting now — it costs
--     nothing and starts being honoured the moment the roll lands.
--
-- lock_type CHECK accepts permanent|timed|review only (NOT 'admin'). locked_by is free text, so
-- classification must be done on lock_type — do not parse locked_by.

\set ON_ERROR_STOP on

BEGIN;

-- SCOPE WIDENED 2026-07-25 (after p4_05/p4_06/p4_07): this now locks everything authored in the
-- p4_* batch, not just the patents guide — the copyright guide (equally high-stakes legal content)
-- and the patent-check tool page (whose section carries the gated verdict copy, and whose gating
-- logic a regeneration pass would flatten). Deliberately NOT locked: the two hubs' derived
-- listings, which must keep re-resolving as guides and tools are added.

DO $guard$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM pages
   WHERE site_id = '1244516d-014d-421c-88c6-090bb1e9552a'
     AND url IN ('/guides/patents/index.html','/guides/copyright/index.html',
                 '/tools/patent-check/index.html','/guides/index.html')
     AND build_status = 'deployed';
  IF n <> 4 THEN
    RAISE EXCEPTION 'ABORT: expected 4 deployed pages, found %. Verify each live before locking.', n;
  END IF;
END
$guard$;

-- Every authored section of the two guides and the tool page.
UPDATE page_components pc
SET locked_at = now(),
    locked_by = 'idea.uk ideas-pipeline (features_open/014, p4_01/p4_05/p4_06) — hand-authored UK legal guidance and gated tool copy, do not regenerate',
    lock_type = 'permanent'
FROM pages p
WHERE p.id = pc.page_id
  AND p.site_id = '1244516d-014d-421c-88c6-090bb1e9552a'
  AND p.url IN ('/guides/patents/index.html',
                '/guides/copyright/index.html',
                '/tools/patent-check/index.html');

-- The hub's listing copy (the items themselves stay query-resolved and must NOT be frozen —
-- the lock protects the surrounding copy, not the derived list).
UPDATE page_components pc
SET locked_at = now(),
    locked_by = 'idea.uk guides hub (p4_02) — authored copy; items stay query-resolved from pages_where_type:guide',
    lock_type = 'permanent'
FROM pages p
WHERE p.id = pc.page_id
  AND p.site_id = '1244516d-014d-421c-88c6-090bb1e9552a'
  AND p.url = '/guides/index.html'
  AND pc.slot_name = 'guide-list';

INSERT INTO doc_notes (subject_type, subject_key, body, categories, created_at)
VALUES (
  'pipeline', 'cta_link_integrity',
  'idea.uk /guides/patents/index.html, /guides/copyright/index.html, /tools/patent-check/index.html '
  || 'and /guides/index.html carry EXPLICIT business-intent CTA urls '
  || '(funnel to the paid /report.html tool + /tools.html#audience-check), set by p4_01/p4_02 and locked '
  || 'by p4_03. Do NOT fire a cta_links_stale recompute on these pages: applyCTARecompute would replace '
  || 'them with a content hub. Same standing exception as /index.html (p3_06). The guide body is '
  || 'hand-authored UK legal guidance and must not be regenerated by a content pass. '
  || 'See idea_uk_vm_site/RUNNING_NOTES and features_open/014.',
  '["cta-link-integrity","idea.uk","do-not-recompute","authored-legal-content"]'::jsonb,
  now()
);

COMMIT;

SELECT p.url, pc.position, pc.slot_name, pc.lock_type, pc.locked_at IS NOT NULL AS locked
FROM page_components pc JOIN pages p ON p.id = pc.page_id
WHERE p.site_id = '1244516d-014d-421c-88c6-090bb1e9552a'
  AND p.url IN ('/guides/patents/index.html','/guides/index.html')
ORDER BY p.url, pc.position;
